package org.inn.baner.persist.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.inn.baner.bean.Label;
import org.inn.baner.bean.LabelExample;

public interface LabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated
     */
    @SelectProvider(type=LabelSqlProvider.class, method="countByExample")
    long countByExample(LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated
     */
    @DeleteProvider(type=LabelSqlProvider.class, method="deleteByExample")
    int deleteByExample(LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated
     */
    @Delete({
        "delete from label",
        "where labelid = #{labelid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String labelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated
     */
    @Insert({
        "insert into label (labelid, labelname, ",
        "weight)",
        "values (#{labelid,jdbcType=VARCHAR}, #{labelname,jdbcType=VARCHAR}, ",
        "#{weight,jdbcType=INTEGER})"
    })
    int insert(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated
     */
    @InsertProvider(type=LabelSqlProvider.class, method="insertSelective")
    int insertSelective(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated
     */
    @SelectProvider(type=LabelSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="labelid", property="labelid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="labelname", property="labelname", jdbcType=JdbcType.VARCHAR),
        @Result(column="weight", property="weight", jdbcType=JdbcType.INTEGER)
    })
    List<Label> selectByExample(LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "labelid, labelname, weight",
        "from label",
        "where labelid = #{labelid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="labelid", property="labelid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="labelname", property="labelname", jdbcType=JdbcType.VARCHAR),
        @Result(column="weight", property="weight", jdbcType=JdbcType.INTEGER)
    })
    Label selectByPrimaryKey(String labelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated
     */
    @UpdateProvider(type=LabelSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Label record, @Param("example") LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated
     */
    @UpdateProvider(type=LabelSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Label record, @Param("example") LabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated
     */
    @UpdateProvider(type=LabelSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Label record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated
     */
    @Update({
        "update label",
        "set labelname = #{labelname,jdbcType=VARCHAR},",
          "weight = #{weight,jdbcType=INTEGER}",
        "where labelid = #{labelid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Label record);
}