package org.inn.baner.persist.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.inn.baner.bean.LabelSubject;
import org.inn.baner.bean.LabelSubjectExample;

public interface LabelSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_subject
     *
     * @mbg.generated
     */
    @SelectProvider(type=LabelSubjectSqlProvider.class, method="countByExample")
    long countByExample(LabelSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_subject
     *
     * @mbg.generated
     */
    @DeleteProvider(type=LabelSubjectSqlProvider.class, method="deleteByExample")
    int deleteByExample(LabelSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_subject
     *
     * @mbg.generated
     */
    @Delete({
        "delete from label_subject",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_subject
     *
     * @mbg.generated
     */
    @Insert({
        "insert into label_subject (id, labelid, ",
        "subjectid, subject)",
        "values (#{id,jdbcType=BIGINT}, #{labelid,jdbcType=VARCHAR}, ",
        "#{subjectid,jdbcType=VARCHAR}, #{subject,jdbcType=VARCHAR})"
    })
    int insert(LabelSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_subject
     *
     * @mbg.generated
     */
    @InsertProvider(type=LabelSubjectSqlProvider.class, method="insertSelective")
    int insertSelective(LabelSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_subject
     *
     * @mbg.generated
     */
    @SelectProvider(type=LabelSubjectSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="labelid", property="labelid", jdbcType=JdbcType.VARCHAR),
        @Result(column="subjectid", property="subjectid", jdbcType=JdbcType.VARCHAR),
        @Result(column="subject", property="subject", jdbcType=JdbcType.VARCHAR)
    })
    List<LabelSubject> selectByExample(LabelSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_subject
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, labelid, subjectid, subject",
        "from label_subject",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="labelid", property="labelid", jdbcType=JdbcType.VARCHAR),
        @Result(column="subjectid", property="subjectid", jdbcType=JdbcType.VARCHAR),
        @Result(column="subject", property="subject", jdbcType=JdbcType.VARCHAR)
    })
    LabelSubject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_subject
     *
     * @mbg.generated
     */
    @UpdateProvider(type=LabelSubjectSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") LabelSubject record, @Param("example") LabelSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_subject
     *
     * @mbg.generated
     */
    @UpdateProvider(type=LabelSubjectSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") LabelSubject record, @Param("example") LabelSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_subject
     *
     * @mbg.generated
     */
    @UpdateProvider(type=LabelSubjectSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(LabelSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label_subject
     *
     * @mbg.generated
     */
    @Update({
        "update label_subject",
        "set labelid = #{labelid,jdbcType=VARCHAR},",
          "subjectid = #{subjectid,jdbcType=VARCHAR},",
          "subject = #{subject,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(LabelSubject record);
}