package org.inn.baner.persist.mapper;

import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.inn.baner.persist.example.Post;
import org.inn.baner.persist.example.PostExample;

public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    @SelectProvider(type=PostSqlProvider.class, method="countByExample")
    long countByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    @DeleteProvider(type=PostSqlProvider.class, method="deleteByExample")
    int deleteByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    @Insert({
        "insert into post (postid, topicid, ",
        "creatormobileno, postname, ",
        "postdesc, zantimes, ",
        "createtime, updatetime, ",
        "context)",
        "values (#{postid,jdbcType=INTEGER}, #{topicid,jdbcType=INTEGER}, ",
        "#{creatormobileno,jdbcType=VARCHAR}, #{postname,jdbcType=VARCHAR}, ",
        "#{postdesc,jdbcType=VARCHAR}, #{zantimes,jdbcType=INTEGER}, ",
        "#{createtime,jdbcType=TIMESTAMP}, #{updatetime,jdbcType=TIMESTAMP}, ",
        "#{context,jdbcType=LONGVARBINARY})"
    })
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    @InsertProvider(type=PostSqlProvider.class, method="insertSelective")
    int insertSelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    @SelectProvider(type=PostSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="postid", property="postid", jdbcType=JdbcType.INTEGER),
        @Result(column="topicid", property="topicid", jdbcType=JdbcType.INTEGER),
        @Result(column="creatormobileno", property="creatormobileno", jdbcType=JdbcType.VARCHAR),
        @Result(column="postname", property="postname", jdbcType=JdbcType.VARCHAR),
        @Result(column="postdesc", property="postdesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="zantimes", property="zantimes", jdbcType=JdbcType.INTEGER),
        @Result(column="createtime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updatetime", property="updatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="context", property="context", jdbcType=JdbcType.LONGVARBINARY)
    })
    List<Post> selectByExampleWithBLOBs(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    @SelectProvider(type=PostSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="postid", property="postid", jdbcType=JdbcType.INTEGER),
        @Result(column="topicid", property="topicid", jdbcType=JdbcType.INTEGER),
        @Result(column="creatormobileno", property="creatormobileno", jdbcType=JdbcType.VARCHAR),
        @Result(column="postname", property="postname", jdbcType=JdbcType.VARCHAR),
        @Result(column="postdesc", property="postdesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="zantimes", property="zantimes", jdbcType=JdbcType.INTEGER),
        @Result(column="createtime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updatetime", property="updatetime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Post> selectByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PostSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PostSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    @UpdateProvider(type=PostSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Post record, @Param("example") PostExample example);
}