package org.inn.baner.persist.mapper;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import org.inn.baner.bean.Post;
import org.inn.baner.bean.PostExample.Criteria;
import org.inn.baner.bean.PostExample.Criterion;
import org.inn.baner.bean.PostExample;

public class PostSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    public String countByExample(PostExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("post");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    public String deleteByExample(PostExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("post");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    public String insertSelective(Post record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("post");
        
        if (record.getPostid() != null) {
            sql.VALUES("postid", "#{postid,jdbcType=VARCHAR}");
        }
        
        if (record.getTopicid() != null) {
            sql.VALUES("topicid", "#{topicid,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatormobileno() != null) {
            sql.VALUES("creatormobileno", "#{creatormobileno,jdbcType=VARCHAR}");
        }
        
        if (record.getPostname() != null) {
            sql.VALUES("postname", "#{postname,jdbcType=VARCHAR}");
        }
        
        if (record.getPostdesc() != null) {
            sql.VALUES("postdesc", "#{postdesc,jdbcType=VARCHAR}");
        }
        
        if (record.getZantimes() != null) {
            sql.VALUES("zantimes", "#{zantimes,jdbcType=INTEGER}");
        }
        
        if (record.getCreatetime() != null) {
            sql.VALUES("createtime", "#{createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatetime() != null) {
            sql.VALUES("updatetime", "#{updatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getContext() != null) {
            sql.VALUES("context", "#{context,jdbcType=LONGVARBINARY}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    public String selectByExampleWithBLOBs(PostExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("postid");
        } else {
            sql.SELECT("postid");
        }
        sql.SELECT("topicid");
        sql.SELECT("creatormobileno");
        sql.SELECT("postname");
        sql.SELECT("postdesc");
        sql.SELECT("zantimes");
        sql.SELECT("createtime");
        sql.SELECT("updatetime");
        sql.SELECT("context");
        sql.FROM("post");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    public String selectByExample(PostExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("postid");
        } else {
            sql.SELECT("postid");
        }
        sql.SELECT("topicid");
        sql.SELECT("creatormobileno");
        sql.SELECT("postname");
        sql.SELECT("postdesc");
        sql.SELECT("zantimes");
        sql.SELECT("createtime");
        sql.SELECT("updatetime");
        sql.FROM("post");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Post record = (Post) parameter.get("record");
        PostExample example = (PostExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("post");
        
        if (record.getPostid() != null) {
            sql.SET("postid = #{record.postid,jdbcType=VARCHAR}");
        }
        
        if (record.getTopicid() != null) {
            sql.SET("topicid = #{record.topicid,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatormobileno() != null) {
            sql.SET("creatormobileno = #{record.creatormobileno,jdbcType=VARCHAR}");
        }
        
        if (record.getPostname() != null) {
            sql.SET("postname = #{record.postname,jdbcType=VARCHAR}");
        }
        
        if (record.getPostdesc() != null) {
            sql.SET("postdesc = #{record.postdesc,jdbcType=VARCHAR}");
        }
        
        if (record.getZantimes() != null) {
            sql.SET("zantimes = #{record.zantimes,jdbcType=INTEGER}");
        }
        
        if (record.getCreatetime() != null) {
            sql.SET("createtime = #{record.createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatetime() != null) {
            sql.SET("updatetime = #{record.updatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getContext() != null) {
            sql.SET("context = #{record.context,jdbcType=LONGVARBINARY}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("post");
        
        sql.SET("postid = #{record.postid,jdbcType=VARCHAR}");
        sql.SET("topicid = #{record.topicid,jdbcType=VARCHAR}");
        sql.SET("creatormobileno = #{record.creatormobileno,jdbcType=VARCHAR}");
        sql.SET("postname = #{record.postname,jdbcType=VARCHAR}");
        sql.SET("postdesc = #{record.postdesc,jdbcType=VARCHAR}");
        sql.SET("zantimes = #{record.zantimes,jdbcType=INTEGER}");
        sql.SET("createtime = #{record.createtime,jdbcType=TIMESTAMP}");
        sql.SET("updatetime = #{record.updatetime,jdbcType=TIMESTAMP}");
        sql.SET("context = #{record.context,jdbcType=LONGVARBINARY}");
        
        PostExample example = (PostExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("post");
        
        sql.SET("postid = #{record.postid,jdbcType=VARCHAR}");
        sql.SET("topicid = #{record.topicid,jdbcType=VARCHAR}");
        sql.SET("creatormobileno = #{record.creatormobileno,jdbcType=VARCHAR}");
        sql.SET("postname = #{record.postname,jdbcType=VARCHAR}");
        sql.SET("postdesc = #{record.postdesc,jdbcType=VARCHAR}");
        sql.SET("zantimes = #{record.zantimes,jdbcType=INTEGER}");
        sql.SET("createtime = #{record.createtime,jdbcType=TIMESTAMP}");
        sql.SET("updatetime = #{record.updatetime,jdbcType=TIMESTAMP}");
        
        PostExample example = (PostExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Post record) {
        SQL sql = new SQL();
        sql.UPDATE("post");
        
        if (record.getCreatormobileno() != null) {
            sql.SET("creatormobileno = #{creatormobileno,jdbcType=VARCHAR}");
        }
        
        if (record.getPostname() != null) {
            sql.SET("postname = #{postname,jdbcType=VARCHAR}");
        }
        
        if (record.getPostdesc() != null) {
            sql.SET("postdesc = #{postdesc,jdbcType=VARCHAR}");
        }
        
        if (record.getZantimes() != null) {
            sql.SET("zantimes = #{zantimes,jdbcType=INTEGER}");
        }
        
        if (record.getCreatetime() != null) {
            sql.SET("createtime = #{createtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdatetime() != null) {
            sql.SET("updatetime = #{updatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getContext() != null) {
            sql.SET("context = #{context,jdbcType=LONGVARBINARY}");
        }
        
        sql.WHERE("postid = #{postid,jdbcType=VARCHAR}");
        sql.WHERE("topicid = #{topicid,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, PostExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}