package org.inn.baner.persist.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.inn.baner.bean.SheepFlow;
import org.inn.baner.bean.SheepFlowExample;

public interface SheepFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheep_flow
     *
     * @mbggenerated
     */
    @SelectProvider(type=SheepFlowSqlProvider.class, method="countByExample")
    int countByExample(SheepFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheep_flow
     *
     * @mbggenerated
     */
    @DeleteProvider(type=SheepFlowSqlProvider.class, method="deleteByExample")
    int deleteByExample(SheepFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheep_flow
     *
     * @mbggenerated
     */
    @Delete({
        "delete from sheep_flow",
        "where platflow = #{platflow,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String platflow);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheep_flow
     *
     * @mbggenerated
     */
    @Insert({
        "insert into sheep_flow (platflow, activityno, ",
        "providerid, providername, ",
        "consumerid, consumername, ",
        "amount, ccy, stat, ",
        "recordedtime, createtime, ",
        "updatetime, remark)",
        "values (#{platflow,jdbcType=VARCHAR}, #{activityno,jdbcType=VARCHAR}, ",
        "#{providerid,jdbcType=CHAR}, #{providername,jdbcType=CHAR}, ",
        "#{consumerid,jdbcType=CHAR}, #{consumername,jdbcType=CHAR}, ",
        "#{amount,jdbcType=NUMERIC}, #{ccy,jdbcType=CHAR}, #{stat,jdbcType=CHAR}, ",
        "#{recordedtime,jdbcType=TIMESTAMP}, #{createtime,jdbcType=TIMESTAMP}, ",
        "#{updatetime,jdbcType=TIMESTAMP}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(SheepFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheep_flow
     *
     * @mbggenerated
     */
    @InsertProvider(type=SheepFlowSqlProvider.class, method="insertSelective")
    int insertSelective(SheepFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheep_flow
     *
     * @mbggenerated
     */
    @SelectProvider(type=SheepFlowSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="platflow", property="platflow", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="activityno", property="activityno", jdbcType=JdbcType.VARCHAR),
        @Result(column="providerid", property="providerid", jdbcType=JdbcType.CHAR),
        @Result(column="providername", property="providername", jdbcType=JdbcType.CHAR),
        @Result(column="consumerid", property="consumerid", jdbcType=JdbcType.CHAR),
        @Result(column="consumername", property="consumername", jdbcType=JdbcType.CHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.NUMERIC),
        @Result(column="ccy", property="ccy", jdbcType=JdbcType.CHAR),
        @Result(column="stat", property="stat", jdbcType=JdbcType.CHAR),
        @Result(column="recordedtime", property="recordedtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="createtime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updatetime", property="updatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<SheepFlow> selectByExample(SheepFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheep_flow
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "platflow, activityno, providerid, providername, consumerid, consumername, amount, ",
        "ccy, stat, recordedtime, createtime, updatetime, remark",
        "from sheep_flow",
        "where platflow = #{platflow,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="platflow", property="platflow", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="activityno", property="activityno", jdbcType=JdbcType.VARCHAR),
        @Result(column="providerid", property="providerid", jdbcType=JdbcType.CHAR),
        @Result(column="providername", property="providername", jdbcType=JdbcType.CHAR),
        @Result(column="consumerid", property="consumerid", jdbcType=JdbcType.CHAR),
        @Result(column="consumername", property="consumername", jdbcType=JdbcType.CHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.NUMERIC),
        @Result(column="ccy", property="ccy", jdbcType=JdbcType.CHAR),
        @Result(column="stat", property="stat", jdbcType=JdbcType.CHAR),
        @Result(column="recordedtime", property="recordedtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="createtime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updatetime", property="updatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    SheepFlow selectByPrimaryKey(String platflow);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheep_flow
     *
     * @mbggenerated
     */
    @UpdateProvider(type=SheepFlowSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SheepFlow record, @Param("example") SheepFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheep_flow
     *
     * @mbggenerated
     */
    @UpdateProvider(type=SheepFlowSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SheepFlow record, @Param("example") SheepFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheep_flow
     *
     * @mbggenerated
     */
    @UpdateProvider(type=SheepFlowSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SheepFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheep_flow
     *
     * @mbggenerated
     */
    @Update({
        "update sheep_flow",
        "set activityno = #{activityno,jdbcType=VARCHAR},",
          "providerid = #{providerid,jdbcType=CHAR},",
          "providername = #{providername,jdbcType=CHAR},",
          "consumerid = #{consumerid,jdbcType=CHAR},",
          "consumername = #{consumername,jdbcType=CHAR},",
          "amount = #{amount,jdbcType=NUMERIC},",
          "ccy = #{ccy,jdbcType=CHAR},",
          "stat = #{stat,jdbcType=CHAR},",
          "recordedtime = #{recordedtime,jdbcType=TIMESTAMP},",
          "createtime = #{createtime,jdbcType=TIMESTAMP},",
          "updatetime = #{updatetime,jdbcType=TIMESTAMP},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where platflow = #{platflow,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SheepFlow record);
}