package org.inn.baner.persist.mapper;

import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.inn.baner.bean.Topic;
import org.inn.baner.bean.TopicExample;

public interface TopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated
     */
    @SelectProvider(type=TopicSqlProvider.class, method="countByExample")
    long countByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TopicSqlProvider.class, method="deleteByExample")
    int deleteByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated
     */
    @Insert({
        "insert into topic (topicid, topicdesc, ",
        "creatormobileno, topiclogo)",
        "values (#{topicid,jdbcType=INTEGER}, #{topicdesc,jdbcType=VARCHAR}, ",
        "#{creatormobileno,jdbcType=VARCHAR}, #{topiclogo,jdbcType=LONGVARBINARY})"
    })
    int insert(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated
     */
    @InsertProvider(type=TopicSqlProvider.class, method="insertSelective")
    int insertSelective(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated
     */
    @SelectProvider(type=TopicSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="topicid", property="topicid", jdbcType=JdbcType.INTEGER),
        @Result(column="topicdesc", property="topicdesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="creatormobileno", property="creatormobileno", jdbcType=JdbcType.VARCHAR),
        @Result(column="topiclogo", property="topiclogo", jdbcType=JdbcType.LONGVARBINARY)
    })
    List<Topic> selectByExampleWithBLOBs(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated
     */
    @SelectProvider(type=TopicSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="topicid", property="topicid", jdbcType=JdbcType.INTEGER),
        @Result(column="topicdesc", property="topicdesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="creatormobileno", property="creatormobileno", jdbcType=JdbcType.VARCHAR)
    })
    List<Topic> selectByExample(TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TopicSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Topic record, @Param("example") TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TopicSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") Topic record, @Param("example") TopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TopicSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Topic record, @Param("example") TopicExample example);
}