package org.inn.baner.persist.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.inn.baner.bean.Userloc;
import org.inn.baner.bean.UserlocExample;

public interface UserlocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloc
     *
     * @mbg.generated
     */
    @SelectProvider(type=UserlocSqlProvider.class, method="countByExample")
    long countByExample(UserlocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloc
     *
     * @mbg.generated
     */
    @DeleteProvider(type=UserlocSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserlocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloc
     *
     * @mbg.generated
     */
    @Delete({
        "delete from userloc",
        "where mobileno = #{mobileno,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String mobileno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloc
     *
     * @mbg.generated
     */
    @Insert({
        "insert into userloc (mobileno, createtime, ",
        "areacode, locationdesc)",
        "values (#{mobileno,jdbcType=VARCHAR}, #{createtime,jdbcType=TIMESTAMP}, ",
        "#{areacode,jdbcType=VARCHAR}, #{locationdesc,jdbcType=VARCHAR})"
    })
    int insert(Userloc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloc
     *
     * @mbg.generated
     */
    @InsertProvider(type=UserlocSqlProvider.class, method="insertSelective")
    int insertSelective(Userloc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloc
     *
     * @mbg.generated
     */
    @SelectProvider(type=UserlocSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="mobileno", property="mobileno", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="createtime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="areacode", property="areacode", jdbcType=JdbcType.VARCHAR),
        @Result(column="locationdesc", property="locationdesc", jdbcType=JdbcType.VARCHAR)
    })
    List<Userloc> selectByExample(UserlocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloc
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "mobileno, createtime, areacode, locationdesc",
        "from userloc",
        "where mobileno = #{mobileno,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="mobileno", property="mobileno", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="createtime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="areacode", property="areacode", jdbcType=JdbcType.VARCHAR),
        @Result(column="locationdesc", property="locationdesc", jdbcType=JdbcType.VARCHAR)
    })
    Userloc selectByPrimaryKey(String mobileno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloc
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserlocSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Userloc record, @Param("example") UserlocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloc
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserlocSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Userloc record, @Param("example") UserlocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloc
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserlocSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Userloc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloc
     *
     * @mbg.generated
     */
    @Update({
        "update userloc",
        "set createtime = #{createtime,jdbcType=TIMESTAMP},",
          "areacode = #{areacode,jdbcType=VARCHAR},",
          "locationdesc = #{locationdesc,jdbcType=VARCHAR}",
        "where mobileno = #{mobileno,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Userloc record);
}