package org.inn.baner.persist.example;

public class Topic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topicid
     *
     * @mbg.generated
     */
    private Integer topicid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topicdesc
     *
     * @mbg.generated
     */
    private String topicdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.creatormobileno
     *
     * @mbg.generated
     */
    private String creatormobileno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.topiclogo
     *
     * @mbg.generated
     */
    private byte[] topiclogo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topicid
     *
     * @return the value of topic.topicid
     *
     * @mbg.generated
     */
    public Integer getTopicid() {
        return topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topicid
     *
     * @param topicid the value for topic.topicid
     *
     * @mbg.generated
     */
    public void setTopicid(Integer topicid) {
        this.topicid = topicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topicdesc
     *
     * @return the value of topic.topicdesc
     *
     * @mbg.generated
     */
    public String getTopicdesc() {
        return topicdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topicdesc
     *
     * @param topicdesc the value for topic.topicdesc
     *
     * @mbg.generated
     */
    public void setTopicdesc(String topicdesc) {
        this.topicdesc = topicdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.creatormobileno
     *
     * @return the value of topic.creatormobileno
     *
     * @mbg.generated
     */
    public String getCreatormobileno() {
        return creatormobileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.creatormobileno
     *
     * @param creatormobileno the value for topic.creatormobileno
     *
     * @mbg.generated
     */
    public void setCreatormobileno(String creatormobileno) {
        this.creatormobileno = creatormobileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.topiclogo
     *
     * @return the value of topic.topiclogo
     *
     * @mbg.generated
     */
    public byte[] getTopiclogo() {
        return topiclogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.topiclogo
     *
     * @param topiclogo the value for topic.topiclogo
     *
     * @mbg.generated
     */
    public void setTopiclogo(byte[] topiclogo) {
        this.topiclogo = topiclogo;
    }
}