package cn.msec.msc.mysqlgens.admin.mapper;

import cn.msec.msc.mysqlgens.admin.entity.SysAction;
import cn.msec.msc.mysqlgens.admin.entity.SysActionExample;
import cn.msec.msc.mysqlgens.admin.entity.SysActionKey;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SysActionMapper extends StaticTableDaoSupport<SysAction, SysActionExample, SysActionKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ACTION
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @SelectProvider(type=SysActionSqlProvider.class, method="countByExample")
    int countByExample(SysActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ACTION
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @DeleteProvider(type=SysActionSqlProvider.class, method="deleteByExample")
    int deleteByExample(SysActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ACTION
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Delete({
        "delete from T_SYS_ACTION",
        "where ACTION_ID = #{actionId,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(SysActionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ACTION
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Insert({
        "insert into T_SYS_ACTION (ACTION_ID, ACTION_FLAG, ",
        "ACTION_NAME, ACTION_DESC, ",
        "ACTION_MENU, FIELD1)",
        "values (#{actionId,jdbcType=DECIMAL}, #{actionFlag,jdbcType=VARCHAR}, ",
        "#{actionName,jdbcType=VARCHAR}, #{actionDesc,jdbcType=VARCHAR}, ",
        "#{actionMenu,jdbcType=DECIMAL}, #{field1,jdbcType=VARCHAR})"
    })
    int insert(SysAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ACTION
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @InsertProvider(type=SysActionSqlProvider.class, method="insertSelective")
    int insertSelective(SysAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ACTION
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @SelectProvider(type=SysActionSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ACTION_ID", property="actionId", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="ACTION_FLAG", property="actionFlag", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTION_NAME", property="actionName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTION_DESC", property="actionDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTION_MENU", property="actionMenu", jdbcType=JdbcType.DECIMAL),
        @Result(column="FIELD1", property="field1", jdbcType=JdbcType.VARCHAR)
    })
    List<SysAction> selectByExample(SysActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ACTION
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Select({
        "select",
        "ACTION_ID, ACTION_FLAG, ACTION_NAME, ACTION_DESC, ACTION_MENU, FIELD1",
        "from T_SYS_ACTION",
        "where ACTION_ID = #{actionId,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ACTION_ID", property="actionId", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="ACTION_FLAG", property="actionFlag", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTION_NAME", property="actionName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTION_DESC", property="actionDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACTION_MENU", property="actionMenu", jdbcType=JdbcType.DECIMAL),
        @Result(column="FIELD1", property="field1", jdbcType=JdbcType.VARCHAR)
    })
    SysAction selectByPrimaryKey(SysActionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ACTION
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysActionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SysAction record, @Param("example") SysActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ACTION
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysActionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SysAction record, @Param("example") SysActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ACTION
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysActionSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SysAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_ACTION
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Update({
        "update T_SYS_ACTION",
        "set ACTION_FLAG = #{actionFlag,jdbcType=VARCHAR},",
          "ACTION_NAME = #{actionName,jdbcType=VARCHAR},",
          "ACTION_DESC = #{actionDesc,jdbcType=VARCHAR},",
          "ACTION_MENU = #{actionMenu,jdbcType=DECIMAL},",
          "FIELD1 = #{field1,jdbcType=VARCHAR}",
        "where ACTION_ID = #{actionId,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(SysAction record);
}