package cn.msec.msc.mysqlgens.admin.mapper;

import cn.msec.msc.mysqlgens.admin.entity.SysBusiness;
import cn.msec.msc.mysqlgens.admin.entity.SysBusinessExample;
import cn.msec.msc.mysqlgens.admin.entity.SysBusinessKey;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SysBusinessMapper extends StaticTableDaoSupport<SysBusiness, SysBusinessExample, SysBusinessKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @SelectProvider(type=SysBusinessSqlProvider.class, method="countByExample")
    int countByExample(SysBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @DeleteProvider(type=SysBusinessSqlProvider.class, method="deleteByExample")
    int deleteByExample(SysBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Delete({
        "delete from T_SYS_BUSINESS",
        "where BUSINESS_ID = #{businessId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(SysBusinessKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Insert({
        "insert into T_SYS_BUSINESS (BUSINESS_ID, BUSINESS_NAME, ",
        "BUSINESS_DESC, BUSINESS_MANAGER, ",
        "BUSINESS_MOBILE, BUSINESS_SEQ, ",
        "BEGIN_TIME, END_TIME, ",
        "STATUS, BUSINESS_DATA_PERMISSION)",
        "values (#{businessId,jdbcType=VARCHAR}, #{businessName,jdbcType=VARCHAR}, ",
        "#{businessDesc,jdbcType=VARCHAR}, #{businessManager,jdbcType=VARCHAR}, ",
        "#{businessMobile,jdbcType=VARCHAR}, #{businessSeq,jdbcType=DECIMAL}, ",
        "#{beginTime,jdbcType=TIMESTAMP}, #{endTime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=DECIMAL}, #{businessDataPermission,jdbcType=DECIMAL})"
    })
    int insert(SysBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @InsertProvider(type=SysBusinessSqlProvider.class, method="insertSelective")
    int insertSelective(SysBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @SelectProvider(type=SysBusinessSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="BUSINESS_ID", property="businessId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BUSINESS_NAME", property="businessName", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_DESC", property="businessDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_MANAGER", property="businessManager", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_MOBILE", property="businessMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_SEQ", property="businessSeq", jdbcType=JdbcType.DECIMAL),
        @Result(column="BEGIN_TIME", property="beginTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="END_TIME", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.DECIMAL),
        @Result(column="BUSINESS_DATA_PERMISSION", property="businessDataPermission", jdbcType=JdbcType.DECIMAL)
    })
    List<SysBusiness> selectByExample(SysBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Select({
        "select",
        "BUSINESS_ID, BUSINESS_NAME, BUSINESS_DESC, BUSINESS_MANAGER, BUSINESS_MOBILE, ",
        "BUSINESS_SEQ, BEGIN_TIME, END_TIME, STATUS, BUSINESS_DATA_PERMISSION",
        "from T_SYS_BUSINESS",
        "where BUSINESS_ID = #{businessId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="BUSINESS_ID", property="businessId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BUSINESS_NAME", property="businessName", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_DESC", property="businessDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_MANAGER", property="businessManager", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_MOBILE", property="businessMobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUSINESS_SEQ", property="businessSeq", jdbcType=JdbcType.DECIMAL),
        @Result(column="BEGIN_TIME", property="beginTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="END_TIME", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.DECIMAL),
        @Result(column="BUSINESS_DATA_PERMISSION", property="businessDataPermission", jdbcType=JdbcType.DECIMAL)
    })
    SysBusiness selectByPrimaryKey(SysBusinessKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysBusinessSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SysBusiness record, @Param("example") SysBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysBusinessSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SysBusiness record, @Param("example") SysBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysBusinessSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SysBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BUSINESS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Update({
        "update T_SYS_BUSINESS",
        "set BUSINESS_NAME = #{businessName,jdbcType=VARCHAR},",
          "BUSINESS_DESC = #{businessDesc,jdbcType=VARCHAR},",
          "BUSINESS_MANAGER = #{businessManager,jdbcType=VARCHAR},",
          "BUSINESS_MOBILE = #{businessMobile,jdbcType=VARCHAR},",
          "BUSINESS_SEQ = #{businessSeq,jdbcType=DECIMAL},",
          "BEGIN_TIME = #{beginTime,jdbcType=TIMESTAMP},",
          "END_TIME = #{endTime,jdbcType=TIMESTAMP},",
          "STATUS = #{status,jdbcType=DECIMAL},",
          "BUSINESS_DATA_PERMISSION = #{businessDataPermission,jdbcType=DECIMAL}",
        "where BUSINESS_ID = #{businessId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysBusiness record);
}