package cn.msec.msc.mysqlgens.admin.mapper;

import cn.msec.msc.mysqlgens.admin.entity.SysBranch;
import cn.msec.msc.mysqlgens.admin.entity.SysBranchExample;
import cn.msec.msc.mysqlgens.admin.entity.SysBranchKey;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SysBranchMapper extends StaticTableDaoSupport<SysBranch, SysBranchExample, SysBranchKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BRANCH
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @SelectProvider(type=SysBranchSqlProvider.class, method="countByExample")
    int countByExample(SysBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BRANCH
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @DeleteProvider(type=SysBranchSqlProvider.class, method="deleteByExample")
    int deleteByExample(SysBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BRANCH
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Delete({
        "delete from T_SYS_BRANCH",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(SysBranchKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BRANCH
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Insert({
        "insert into T_SYS_BRANCH (ID, BRANCH_ID, ",
        "BRANCH_DESC, BRANCH_NAME, ",
        "BRANCH_MANAGER, MOBILE, ",
        "BEGIN_TIME, END_TIME, ",
        "PARENT_ID, LEAF_FLAG, ",
        "BRANCH_SEQ, LEVEL1)",
        "values (#{id,jdbcType=VARCHAR}, #{branchId,jdbcType=VARCHAR}, ",
        "#{branchDesc,jdbcType=VARCHAR}, #{branchName,jdbcType=VARCHAR}, ",
        "#{branchManager,jdbcType=VARCHAR}, #{mobile,jdbcType=VARCHAR}, ",
        "#{beginTime,jdbcType=TIMESTAMP}, #{endTime,jdbcType=TIMESTAMP}, ",
        "#{parentId,jdbcType=VARCHAR}, #{leafFlag,jdbcType=DECIMAL}, ",
        "#{branchSeq,jdbcType=DECIMAL}, #{level1,jdbcType=DECIMAL})"
    })
    int insert(SysBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BRANCH
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @InsertProvider(type=SysBranchSqlProvider.class, method="insertSelective")
    int insertSelective(SysBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BRANCH
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @SelectProvider(type=SysBranchSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_ID", property="branchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRANCH_DESC", property="branchDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRANCH_NAME", property="branchName", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRANCH_MANAGER", property="branchManager", jdbcType=JdbcType.VARCHAR),
        @Result(column="MOBILE", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="BEGIN_TIME", property="beginTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="END_TIME", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PARENT_ID", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="LEAF_FLAG", property="leafFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="BRANCH_SEQ", property="branchSeq", jdbcType=JdbcType.DECIMAL),
        @Result(column="LEVEL1", property="level1", jdbcType=JdbcType.DECIMAL)
    })
    List<SysBranch> selectByExample(SysBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BRANCH
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Select({
        "select",
        "ID, BRANCH_ID, BRANCH_DESC, BRANCH_NAME, BRANCH_MANAGER, MOBILE, BEGIN_TIME, ",
        "END_TIME, PARENT_ID, LEAF_FLAG, BRANCH_SEQ, LEVEL1",
        "from T_SYS_BRANCH",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BRANCH_ID", property="branchId", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRANCH_DESC", property="branchDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRANCH_NAME", property="branchName", jdbcType=JdbcType.VARCHAR),
        @Result(column="BRANCH_MANAGER", property="branchManager", jdbcType=JdbcType.VARCHAR),
        @Result(column="MOBILE", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="BEGIN_TIME", property="beginTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="END_TIME", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PARENT_ID", property="parentId", jdbcType=JdbcType.VARCHAR),
        @Result(column="LEAF_FLAG", property="leafFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="BRANCH_SEQ", property="branchSeq", jdbcType=JdbcType.DECIMAL),
        @Result(column="LEVEL1", property="level1", jdbcType=JdbcType.DECIMAL)
    })
    SysBranch selectByPrimaryKey(SysBranchKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BRANCH
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysBranchSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SysBranch record, @Param("example") SysBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BRANCH
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysBranchSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SysBranch record, @Param("example") SysBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BRANCH
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysBranchSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SysBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BRANCH
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Update({
        "update T_SYS_BRANCH",
        "set BRANCH_ID = #{branchId,jdbcType=VARCHAR},",
          "BRANCH_DESC = #{branchDesc,jdbcType=VARCHAR},",
          "BRANCH_NAME = #{branchName,jdbcType=VARCHAR},",
          "BRANCH_MANAGER = #{branchManager,jdbcType=VARCHAR},",
          "MOBILE = #{mobile,jdbcType=VARCHAR},",
          "BEGIN_TIME = #{beginTime,jdbcType=TIMESTAMP},",
          "END_TIME = #{endTime,jdbcType=TIMESTAMP},",
          "PARENT_ID = #{parentId,jdbcType=VARCHAR},",
          "LEAF_FLAG = #{leafFlag,jdbcType=DECIMAL},",
          "BRANCH_SEQ = #{branchSeq,jdbcType=DECIMAL},",
          "LEVEL1 = #{level1,jdbcType=DECIMAL}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysBranch record);
}