package cn.msec.msc.mysqlgens.admin.mapper;

import cn.msec.msc.mysqlgens.admin.entity.SysOpLogs;
import cn.msec.msc.mysqlgens.admin.entity.SysOpLogsExample;
import cn.msec.msc.mysqlgens.admin.entity.SysOpLogsKey;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SysOpLogsMapper extends StaticTableDaoSupport<SysOpLogs, SysOpLogsExample, SysOpLogsKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @SelectProvider(type=SysOpLogsSqlProvider.class, method="countByExample")
    int countByExample(SysOpLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @DeleteProvider(type=SysOpLogsSqlProvider.class, method="deleteByExample")
    int deleteByExample(SysOpLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Delete({
        "delete from T_SYS_OP_LOGS",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(SysOpLogsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Insert({
        "insert into T_SYS_OP_LOGS (ID, SKEYS, ",
        "CONTENTS, LEVEL1, ",
        "CRT_TIME)",
        "values (#{id,jdbcType=VARCHAR}, #{skeys,jdbcType=VARCHAR}, ",
        "#{contents,jdbcType=VARCHAR}, #{level1,jdbcType=VARCHAR}, ",
        "#{crtTime,jdbcType=TIMESTAMP})"
    })
    int insert(SysOpLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @InsertProvider(type=SysOpLogsSqlProvider.class, method="insertSelective")
    int insertSelective(SysOpLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @SelectProvider(type=SysOpLogsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SKEYS", property="skeys", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONTENTS", property="contents", jdbcType=JdbcType.VARCHAR),
        @Result(column="LEVEL1", property="level1", jdbcType=JdbcType.VARCHAR),
        @Result(column="CRT_TIME", property="crtTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<SysOpLogs> selectByExample(SysOpLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Select({
        "select",
        "ID, SKEYS, CONTENTS, LEVEL1, CRT_TIME",
        "from T_SYS_OP_LOGS",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="SKEYS", property="skeys", jdbcType=JdbcType.VARCHAR),
        @Result(column="CONTENTS", property="contents", jdbcType=JdbcType.VARCHAR),
        @Result(column="LEVEL1", property="level1", jdbcType=JdbcType.VARCHAR),
        @Result(column="CRT_TIME", property="crtTime", jdbcType=JdbcType.TIMESTAMP)
    })
    SysOpLogs selectByPrimaryKey(SysOpLogsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysOpLogsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SysOpLogs record, @Param("example") SysOpLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysOpLogsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SysOpLogs record, @Param("example") SysOpLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysOpLogsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SysOpLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_OP_LOGS
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Update({
        "update T_SYS_OP_LOGS",
        "set SKEYS = #{skeys,jdbcType=VARCHAR},",
          "CONTENTS = #{contents,jdbcType=VARCHAR},",
          "LEVEL1 = #{level1,jdbcType=VARCHAR},",
          "CRT_TIME = #{crtTime,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysOpLogs record);
}