package cn.msec.msc.mysqlgens.admin.mapper;

import cn.msec.msc.mysqlgens.admin.entity.SysRspCode;
import cn.msec.msc.mysqlgens.admin.entity.SysRspCodeExample;
import cn.msec.msc.mysqlgens.admin.entity.SysRspCodeKey;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SysRspCodeMapper extends StaticTableDaoSupport<SysRspCode, SysRspCodeExample, SysRspCodeKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_RSP_CODE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @SelectProvider(type=SysRspCodeSqlProvider.class, method="countByExample")
    int countByExample(SysRspCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_RSP_CODE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @DeleteProvider(type=SysRspCodeSqlProvider.class, method="deleteByExample")
    int deleteByExample(SysRspCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_RSP_CODE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Delete({
        "delete from T_SYS_RSP_CODE",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(SysRspCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_RSP_CODE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Insert({
        "insert into T_SYS_RSP_CODE (ID, PROD_ID, ",
        "OUT_RSP_CODE, IN_RSP_CODE2, ",
        "RSP_DESC)",
        "values (#{id,jdbcType=VARCHAR}, #{prodId,jdbcType=VARCHAR}, ",
        "#{outRspCode,jdbcType=VARCHAR}, #{inRspCode2,jdbcType=VARCHAR}, ",
        "#{rspDesc,jdbcType=VARCHAR})"
    })
    int insert(SysRspCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_RSP_CODE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @InsertProvider(type=SysRspCodeSqlProvider.class, method="insertSelective")
    int insertSelective(SysRspCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_RSP_CODE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @SelectProvider(type=SysRspCodeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PROD_ID", property="prodId", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUT_RSP_CODE", property="outRspCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="IN_RSP_CODE2", property="inRspCode2", jdbcType=JdbcType.VARCHAR),
        @Result(column="RSP_DESC", property="rspDesc", jdbcType=JdbcType.VARCHAR)
    })
    List<SysRspCode> selectByExample(SysRspCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_RSP_CODE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Select({
        "select",
        "ID, PROD_ID, OUT_RSP_CODE, IN_RSP_CODE2, RSP_DESC",
        "from T_SYS_RSP_CODE",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PROD_ID", property="prodId", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUT_RSP_CODE", property="outRspCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="IN_RSP_CODE2", property="inRspCode2", jdbcType=JdbcType.VARCHAR),
        @Result(column="RSP_DESC", property="rspDesc", jdbcType=JdbcType.VARCHAR)
    })
    SysRspCode selectByPrimaryKey(SysRspCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_RSP_CODE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysRspCodeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SysRspCode record, @Param("example") SysRspCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_RSP_CODE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysRspCodeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SysRspCode record, @Param("example") SysRspCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_RSP_CODE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=SysRspCodeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SysRspCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_RSP_CODE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Update({
        "update T_SYS_RSP_CODE",
        "set PROD_ID = #{prodId,jdbcType=VARCHAR},",
          "OUT_RSP_CODE = #{outRspCode,jdbcType=VARCHAR},",
          "IN_RSP_CODE2 = #{inRspCode2,jdbcType=VARCHAR},",
          "RSP_DESC = #{rspDesc,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysRspCode record);
}