package cn.msec.cbpay.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.msec.cbpay.entity.AppAddress;
import cn.msec.cbpay.entity.AppAddressExample;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;

public interface AppAddressMapper extends StaticTableDaoSupport<AppAddress, AppAddressExample, AppAddress> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_ADDRESS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    @SelectProvider(type=AppAddressSqlProvider.class, method="countByExample")
    int countByExample(AppAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_ADDRESS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    @DeleteProvider(type=AppAddressSqlProvider.class, method="deleteByExample")
    int deleteByExample(AppAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_ADDRESS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    @Delete({
        "delete from APP_ADDRESS",
        "where APPID = #{appid,jdbcType=VARCHAR}",
          "and TYPE = #{type,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("appid") String appid, @Param("type") String type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_ADDRESS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    @Insert({
        "insert into APP_ADDRESS (APPID, TYPE, ",
        "URL, APPSTATUS)",
        "values (#{appid,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR}, ",
        "#{url,jdbcType=VARCHAR}, #{appstatus,jdbcType=VARCHAR})"
    })
    int insert(AppAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_ADDRESS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    @InsertProvider(type=AppAddressSqlProvider.class, method="insertSelective")
    int insertSelective(AppAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_ADDRESS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    @SelectProvider(type=AppAddressSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="APPID", property="appid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="TYPE", property="type", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="URL", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="APPSTATUS", property="appstatus", jdbcType=JdbcType.VARCHAR)
    })
    List<AppAddress> selectByExample(AppAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_ADDRESS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    @Select({
        "select",
        "APPID, TYPE, URL, APPSTATUS",
        "from APP_ADDRESS",
        "where APPID = #{appid,jdbcType=VARCHAR}",
          "and TYPE = #{type,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="APPID", property="appid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="TYPE", property="type", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="URL", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="APPSTATUS", property="appstatus", jdbcType=JdbcType.VARCHAR)
    })
    AppAddress selectByPrimaryKey(@Param("appid") String appid, @Param("type") String type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_ADDRESS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    @UpdateProvider(type=AppAddressSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AppAddress record, @Param("example") AppAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_ADDRESS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    @UpdateProvider(type=AppAddressSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AppAddress record, @Param("example") AppAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_ADDRESS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    @UpdateProvider(type=AppAddressSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AppAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_ADDRESS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    @Update({
        "update APP_ADDRESS",
        "set APPSTATUS = #{appstatus,jdbcType=VARCHAR}",
        "where APPID = #{appid,jdbcType=VARCHAR}",
        " AND TYPE='OUT'"
    })
    int updateByPrimaryKey(AppAddress record);
}