package cn.msec.cbpay.mapper;



import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.msec.cbpay.entity.BBuyExgCtrl;
import cn.msec.cbpay.entity.BBuyExgCtrlExample;
import cn.msec.cbpay.entity.BBuyExgCtrlKey;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;

public interface BBuyExgCtrlMapper extends StaticTableDaoSupport<BBuyExgCtrl, BBuyExgCtrlExample, BBuyExgCtrlKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    @SelectProvider(type=BBuyExgCtrlSqlProvider.class, method="countByExample")
    int countByExample(BBuyExgCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    @DeleteProvider(type=BBuyExgCtrlSqlProvider.class, method="deleteByExample")
    int deleteByExample(BBuyExgCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    @Delete({
        "delete from B_BUY_EXG_CTRL",
        "where BUYBATNO = #{buybatno,jdbcType=VARCHAR}",
          "and BUYDATE = #{buydate,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(BBuyExgCtrlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    @Insert({
        "insert into B_BUY_EXG_CTRL (BUYBATNO, BUYDATE, ",
        "BUYTIME, QUOTECHNL, ",
        "BECIF, TOT_NUM, SALE_CCY, ",
        "BUY_CCY, BUY_SELL_FLAG, TOTAL_AMT, ",
        "SPOT_FLAG, REGISTER_DATE, ",
        "PRICE, CLIENT_EXCHANGE_RATE, ",
        "DISCOUNT_TYPE, DIS_AMT, ",
        "AMT, TRAN_AMT, SELL_ACCT_NO, ",
        "BUY_ACCT_NO, SALE_AMOUNT, ",
        "BUY_AMOUNT, RATE_TIME, ",
        "EXCEED_FLAG, PROCESS_STATUS, ",
        "PROCESS_MSG, TXN_STS, ",
        "CHK_STS)",
        "values (#{buybatno,jdbcType=VARCHAR}, #{buydate,jdbcType=CHAR}, ",
        "#{buytime,jdbcType=CHAR}, #{quotechnl,jdbcType=VARCHAR}, ",
        "#{becif,jdbcType=VARCHAR}, #{totNum,jdbcType=DECIMAL}, #{saleCcy,jdbcType=CHAR}, ",
        "#{buyCcy,jdbcType=CHAR}, #{buySellFlag,jdbcType=CHAR}, #{totalAmt,jdbcType=DECIMAL}, ",
        "#{spotFlag,jdbcType=CHAR}, #{registerDate,jdbcType=CHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{clientExchangeRate,jdbcType=DECIMAL}, ",
        "#{discountType,jdbcType=CHAR}, #{disAmt,jdbcType=DECIMAL}, ",
        "#{amt,jdbcType=DECIMAL}, #{tranAmt,jdbcType=DECIMAL}, #{sellAcctNo,jdbcType=VARCHAR}, ",
        "#{buyAcctNo,jdbcType=VARCHAR}, #{saleAmount,jdbcType=DECIMAL}, ",
        "#{buyAmount,jdbcType=DECIMAL}, #{rateTime,jdbcType=VARCHAR}, ",
        "#{exceedFlag,jdbcType=CHAR}, #{processStatus,jdbcType=VARCHAR}, ",
        "#{processMsg,jdbcType=VARCHAR}, #{txnSts,jdbcType=CHAR}, ",
        "#{chkSts,jdbcType=CHAR})"
    })
    int insert(BBuyExgCtrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    @InsertProvider(type=BBuyExgCtrlSqlProvider.class, method="insertSelective")
    int insertSelective(BBuyExgCtrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    @SelectProvider(type=BBuyExgCtrlSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="BUYBATNO", property="buybatno", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BUYDATE", property="buydate", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="BUYTIME", property="buytime", jdbcType=JdbcType.CHAR),
        @Result(column="QUOTECHNL", property="quotechnl", jdbcType=JdbcType.VARCHAR),
        @Result(column="BECIF", property="becif", jdbcType=JdbcType.VARCHAR),
        @Result(column="TOT_NUM", property="totNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="SALE_CCY", property="saleCcy", jdbcType=JdbcType.CHAR),
        @Result(column="BUY_CCY", property="buyCcy", jdbcType=JdbcType.CHAR),
        @Result(column="BUY_SELL_FLAG", property="buySellFlag", jdbcType=JdbcType.CHAR),
        @Result(column="TOTAL_AMT", property="totalAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPOT_FLAG", property="spotFlag", jdbcType=JdbcType.CHAR),
        @Result(column="REGISTER_DATE", property="registerDate", jdbcType=JdbcType.CHAR),
        @Result(column="PRICE", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="CLIENT_EXCHANGE_RATE", property="clientExchangeRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="DISCOUNT_TYPE", property="discountType", jdbcType=JdbcType.CHAR),
        @Result(column="DIS_AMT", property="disAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="AMT", property="amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="TRAN_AMT", property="tranAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SELL_ACCT_NO", property="sellAcctNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUY_ACCT_NO", property="buyAcctNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="SALE_AMOUNT", property="saleAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="BUY_AMOUNT", property="buyAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="RATE_TIME", property="rateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="EXCEED_FLAG", property="exceedFlag", jdbcType=JdbcType.CHAR),
        @Result(column="PROCESS_STATUS", property="processStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROCESS_MSG", property="processMsg", jdbcType=JdbcType.VARCHAR),
        @Result(column="TXN_STS", property="txnSts", jdbcType=JdbcType.CHAR),
        @Result(column="CHK_STS", property="chkSts", jdbcType=JdbcType.CHAR)
    })
    List<BBuyExgCtrl> selectByExample(BBuyExgCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    @Select({
        "select",
        "BUYBATNO, BUYDATE, BUYTIME, QUOTECHNL, BECIF, TOT_NUM, SALE_CCY, BUY_CCY, BUY_SELL_FLAG, ",
        "TOTAL_AMT, SPOT_FLAG, REGISTER_DATE, PRICE, CLIENT_EXCHANGE_RATE, DISCOUNT_TYPE, ",
        "DIS_AMT, AMT, TRAN_AMT, SELL_ACCT_NO, BUY_ACCT_NO, SALE_AMOUNT, BUY_AMOUNT, ",
        "RATE_TIME, EXCEED_FLAG, PROCESS_STATUS, PROCESS_MSG, TXN_STS, CHK_STS",
        "from B_BUY_EXG_CTRL",
        "where BUYBATNO = #{buybatno,jdbcType=VARCHAR}",
          "and BUYDATE = #{buydate,jdbcType=CHAR}"
    })
    @Results({
        @Result(column="BUYBATNO", property="buybatno", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BUYDATE", property="buydate", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="BUYTIME", property="buytime", jdbcType=JdbcType.CHAR),
        @Result(column="QUOTECHNL", property="quotechnl", jdbcType=JdbcType.VARCHAR),
        @Result(column="BECIF", property="becif", jdbcType=JdbcType.VARCHAR),
        @Result(column="TOT_NUM", property="totNum", jdbcType=JdbcType.DECIMAL),
        @Result(column="SALE_CCY", property="saleCcy", jdbcType=JdbcType.CHAR),
        @Result(column="BUY_CCY", property="buyCcy", jdbcType=JdbcType.CHAR),
        @Result(column="BUY_SELL_FLAG", property="buySellFlag", jdbcType=JdbcType.CHAR),
        @Result(column="TOTAL_AMT", property="totalAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SPOT_FLAG", property="spotFlag", jdbcType=JdbcType.CHAR),
        @Result(column="REGISTER_DATE", property="registerDate", jdbcType=JdbcType.CHAR),
        @Result(column="PRICE", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="CLIENT_EXCHANGE_RATE", property="clientExchangeRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="DISCOUNT_TYPE", property="discountType", jdbcType=JdbcType.CHAR),
        @Result(column="DIS_AMT", property="disAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="AMT", property="amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="TRAN_AMT", property="tranAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="SELL_ACCT_NO", property="sellAcctNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUY_ACCT_NO", property="buyAcctNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="SALE_AMOUNT", property="saleAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="BUY_AMOUNT", property="buyAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="RATE_TIME", property="rateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="EXCEED_FLAG", property="exceedFlag", jdbcType=JdbcType.CHAR),
        @Result(column="PROCESS_STATUS", property="processStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROCESS_MSG", property="processMsg", jdbcType=JdbcType.VARCHAR),
        @Result(column="TXN_STS", property="txnSts", jdbcType=JdbcType.CHAR),
        @Result(column="CHK_STS", property="chkSts", jdbcType=JdbcType.CHAR)
    })
    BBuyExgCtrl selectByPrimaryKey(BBuyExgCtrlKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    @UpdateProvider(type=BBuyExgCtrlSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BBuyExgCtrl record, @Param("example") BBuyExgCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    @UpdateProvider(type=BBuyExgCtrlSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BBuyExgCtrl record, @Param("example") BBuyExgCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    @UpdateProvider(type=BBuyExgCtrlSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BBuyExgCtrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    @Update({
        "update B_BUY_EXG_CTRL",
        "set BUYTIME = #{buytime,jdbcType=CHAR},",
          "QUOTECHNL = #{quotechnl,jdbcType=VARCHAR},",
          "BECIF = #{becif,jdbcType=VARCHAR},",
          "TOT_NUM = #{totNum,jdbcType=DECIMAL},",
          "SALE_CCY = #{saleCcy,jdbcType=CHAR},",
          "BUY_CCY = #{buyCcy,jdbcType=CHAR},",
          "BUY_SELL_FLAG = #{buySellFlag,jdbcType=CHAR},",
          "TOTAL_AMT = #{totalAmt,jdbcType=DECIMAL},",
          "SPOT_FLAG = #{spotFlag,jdbcType=CHAR},",
          "REGISTER_DATE = #{registerDate,jdbcType=CHAR},",
          "PRICE = #{price,jdbcType=DECIMAL},",
          "CLIENT_EXCHANGE_RATE = #{clientExchangeRate,jdbcType=DECIMAL},",
          "DISCOUNT_TYPE = #{discountType,jdbcType=CHAR},",
          "DIS_AMT = #{disAmt,jdbcType=DECIMAL},",
          "AMT = #{amt,jdbcType=DECIMAL},",
          "TRAN_AMT = #{tranAmt,jdbcType=DECIMAL},",
          "SELL_ACCT_NO = #{sellAcctNo,jdbcType=VARCHAR},",
          "BUY_ACCT_NO = #{buyAcctNo,jdbcType=VARCHAR},",
          "SALE_AMOUNT = #{saleAmount,jdbcType=DECIMAL},",
          "BUY_AMOUNT = #{buyAmount,jdbcType=DECIMAL},",
          "RATE_TIME = #{rateTime,jdbcType=VARCHAR},",
          "EXCEED_FLAG = #{exceedFlag,jdbcType=CHAR},",
          "PROCESS_STATUS = #{processStatus,jdbcType=VARCHAR},",
          "PROCESS_MSG = #{processMsg,jdbcType=VARCHAR},",
          "TXN_STS = #{txnSts,jdbcType=CHAR},",
          "CHK_STS = #{chkSts,jdbcType=CHAR}",
        "where BUYBATNO = #{buybatno,jdbcType=VARCHAR}",
          "and BUYDATE = #{buydate,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(BBuyExgCtrl record);
}