package cn.msec.cbpay.mapper;


import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.msec.cbpay.entity.BCheckStatus;
import cn.msec.cbpay.entity.BCheckStatusExample;
import cn.msec.cbpay.entity.BCheckStatusKey;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;

public interface BCheckStatusMapper extends StaticTableDaoSupport<BCheckStatus, BCheckStatusExample, BCheckStatusKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_CHECK_STATUS
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    @SelectProvider(type=BCheckStatusSqlProvider.class, method="countByExample")
    int countByExample(BCheckStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_CHECK_STATUS
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    @DeleteProvider(type=BCheckStatusSqlProvider.class, method="deleteByExample")
    int deleteByExample(BCheckStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_CHECK_STATUS
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    @Delete({
        "delete from B_CHECK_STATUS",
        "where TRANDATE = #{trandate,jdbcType=VARCHAR}",
          "and CHECKTYPE = #{checktype,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(BCheckStatusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_CHECK_STATUS
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    @Insert({
        "insert into B_CHECK_STATUS (TRANDATE, CHECKTYPE, ",
        "ACCOUNTDATE, STATUS, ",
        "TRANTIME, FILENAME, ",
        " JNLNO, ",
        "CHECKNL, ISHANDLED)",
        "values (#{trandate,jdbcType=VARCHAR}, #{checktype,jdbcType=CHAR}, ",
        "#{accountdate,jdbcType=VARCHAR}, #{status,jdbcType=CHAR}, ",
        "#{trantime,jdbcType=VARCHAR}, #{filename,jdbcType=VARCHAR}, ",
        "##{jnlno,jdbcType=VARCHAR}, ",
        "#{checknl,jdbcType=VARCHAR}, #{ishandled,jdbcType=CHAR})"
    })
    int insert(BCheckStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_CHECK_STATUS
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    @InsertProvider(type=BCheckStatusSqlProvider.class, method="insertSelective")
    int insertSelective(BCheckStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_CHECK_STATUS
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    @SelectProvider(type=BCheckStatusSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="TRANDATE", property="trandate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CHECKTYPE", property="checktype", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="ACCOUNTDATE", property="accountdate", jdbcType=JdbcType.VARCHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="TRANTIME", property="trantime", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILENAME", property="filename", jdbcType=JdbcType.VARCHAR),
       // @Result(column="TMSMP", property="tmsmp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="JNLNO", property="jnlno", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHECKNL", property="checknl", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISHANDLED", property="ishandled", jdbcType=JdbcType.CHAR)
    })
    List<BCheckStatus> selectByExample(BCheckStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_CHECK_STATUS
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    @Select({
        "select",
        "TRANDATE, CHECKTYPE, ACCOUNTDATE, STATUS, TRANTIME, FILENAME, JNLNO, ",
        "CHECKNL, ISHANDLED",
        "from B_CHECK_STATUS",
        "where TRANDATE = #{trandate,jdbcType=VARCHAR}",
          "and CHECKTYPE = #{checktype,jdbcType=CHAR}"
    })
    @Results({
        @Result(column="TRANDATE", property="trandate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CHECKTYPE", property="checktype", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="ACCOUNTDATE", property="accountdate", jdbcType=JdbcType.VARCHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="TRANTIME", property="trantime", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILENAME", property="filename", jdbcType=JdbcType.VARCHAR),
      //  @Result(column="TMSMP", property="tmsmp", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="JNLNO", property="jnlno", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHECKNL", property="checknl", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISHANDLED", property="ishandled", jdbcType=JdbcType.CHAR)
    })
    BCheckStatus selectByPrimaryKey(BCheckStatusKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_CHECK_STATUS
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    @UpdateProvider(type=BCheckStatusSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BCheckStatus record, @Param("example") BCheckStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_CHECK_STATUS
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    @UpdateProvider(type=BCheckStatusSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BCheckStatus record, @Param("example") BCheckStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_CHECK_STATUS
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    @UpdateProvider(type=BCheckStatusSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BCheckStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_CHECK_STATUS
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    @Update({
        "update B_CHECK_STATUS",
        "set ACCOUNTDATE = #{accountdate,jdbcType=VARCHAR},",
          "STATUS = #{status,jdbcType=CHAR},",
          "TRANTIME = #{trantime,jdbcType=VARCHAR},",
          "FILENAME = #{filename,jdbcType=VARCHAR},",
        //  "TMSMP = #{tmsmp,jdbcType=TIMESTAMP},",
          "JNLNO = #{jnlno,jdbcType=VARCHAR},",
          "CHECKNL = #{checknl,jdbcType=VARCHAR},",
          "ISHANDLED = #{ishandled,jdbcType=CHAR}",
        "where TRANDATE = #{trandate,jdbcType=VARCHAR}",
          "and CHECKTYPE = #{checktype,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(BCheckStatus record);
}