package cn.msec.cbpay.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.msec.cbpay.entity.BForeignCurrencyRate;
import cn.msec.cbpay.entity.BForeignCurrencyRateExample;
import cn.msec.cbpay.entity.BForeignCurrencyRateKey;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;

public interface BForeignCurrencyRateMapper extends StaticTableDaoSupport<BForeignCurrencyRate, BForeignCurrencyRateExample, BForeignCurrencyRateKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:58 CST 2016
     */
    @SelectProvider(type=BForeignCurrencyRateSqlProvider.class, method="countByExample")
    int countByExample(BForeignCurrencyRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:58 CST 2016
     */
    @DeleteProvider(type=BForeignCurrencyRateSqlProvider.class, method="deleteByExample")
    int deleteByExample(BForeignCurrencyRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:58 CST 2016
     */
    @Delete({
        "delete from B_FOREIGN_CURRENCY_RATE",
        "where FROM_ID = #{fromId,jdbcType=VARCHAR}",
          "and RECV_DATE = #{recvDate,jdbcType=VARCHAR}",
          "and RECV_TIME = #{recvTime,jdbcType=VARCHAR}",
          "and CURRENCY_CODE = #{currencyCode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(BForeignCurrencyRateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:58 CST 2016
     */
    @Insert({
        "insert into B_FOREIGN_CURRENCY_RATE (FROM_ID, RECV_DATE, ",
        "RECV_TIME, CURRENCY_CODE, ",
        "TRANSTIME, TRANSDATE, ",
        "CASHBUYPRICE, EXBUYPRICE, ",
        "CASHSELLPRICE, EXSELLPRICE, ",
        "EXQUOTEDATE, EXQUOTETIME, ",
        "E3RDPAYNO, PRICE, ",
        "DIRECTION_FLAG, TRAN_AMT, ",
        "CLIENT_EXCHANGE_RATE, DISCOUNT_TYPE, ",
        "DIS_AMT, AMT)",
        "values (#{fromId,jdbcType=VARCHAR}, #{recvDate,jdbcType=VARCHAR}, ",
        "#{recvTime,jdbcType=VARCHAR}, #{currencyCode,jdbcType=VARCHAR}, ",
        "#{transtime,jdbcType=VARCHAR}, #{transdate,jdbcType=VARCHAR}, ",
        "#{cashbuyprice,jdbcType=DECIMAL}, #{exbuyprice,jdbcType=DECIMAL}, ",
        "#{cashsellprice,jdbcType=DECIMAL}, #{exsellprice,jdbcType=DECIMAL}, ",
        "#{exquotedate,jdbcType=VARCHAR}, #{exquotetime,jdbcType=VARCHAR}, ",
        "#{e3rdpayno,jdbcType=VARCHAR}, #{price,jdbcType=DECIMAL}, ",
        "#{directionFlag,jdbcType=CHAR}, #{tranAmt,jdbcType=DECIMAL}, ",
        "#{clientExchangeRate,jdbcType=DECIMAL}, #{discountType,jdbcType=CHAR}, ",
        "#{disAmt,jdbcType=DECIMAL}, #{amt,jdbcType=DECIMAL})"
    })
    int insert(BForeignCurrencyRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:58 CST 2016
     */
    @InsertProvider(type=BForeignCurrencyRateSqlProvider.class, method="insertSelective")
    int insertSelective(BForeignCurrencyRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:58 CST 2016
     */
    @SelectProvider(type=BForeignCurrencyRateSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="FROM_ID", property="fromId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="RECV_DATE", property="recvDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="RECV_TIME", property="recvTime", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CURRENCY_CODE", property="currencyCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="TRANSTIME", property="transtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSDATE", property="transdate", jdbcType=JdbcType.VARCHAR),
        @Result(column="CASHBUYPRICE", property="cashbuyprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="EXBUYPRICE", property="exbuyprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASHSELLPRICE", property="cashsellprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="EXSELLPRICE", property="exsellprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="EXQUOTEDATE", property="exquotedate", jdbcType=JdbcType.VARCHAR),
        @Result(column="EXQUOTETIME", property="exquotetime", jdbcType=JdbcType.VARCHAR),
        @Result(column="E3RDPAYNO", property="e3rdpayno", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRICE", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="DIRECTION_FLAG", property="directionFlag", jdbcType=JdbcType.CHAR),
        @Result(column="TRAN_AMT", property="tranAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CLIENT_EXCHANGE_RATE", property="clientExchangeRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="DISCOUNT_TYPE", property="discountType", jdbcType=JdbcType.CHAR),
        @Result(column="DIS_AMT", property="disAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="AMT", property="amt", jdbcType=JdbcType.DECIMAL)
    })
    List<BForeignCurrencyRate> selectByExample(BForeignCurrencyRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:58 CST 2016
     */
    @Select({
        "select",
        "FROM_ID, RECV_DATE, RECV_TIME, CURRENCY_CODE, TRANSTIME, TRANSDATE, CASHBUYPRICE, ",
        "EXBUYPRICE, CASHSELLPRICE, EXSELLPRICE, EXQUOTEDATE, EXQUOTETIME, E3RDPAYNO, ",
        "PRICE, DIRECTION_FLAG, TRAN_AMT, CLIENT_EXCHANGE_RATE, DISCOUNT_TYPE, DIS_AMT, ",
        "AMT",
        "from B_FOREIGN_CURRENCY_RATE",
        "where FROM_ID = #{fromId,jdbcType=VARCHAR}",
          "and RECV_DATE = #{recvDate,jdbcType=VARCHAR}",
          "and RECV_TIME = #{recvTime,jdbcType=VARCHAR}",
          "and CURRENCY_CODE = #{currencyCode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="FROM_ID", property="fromId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="RECV_DATE", property="recvDate", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="RECV_TIME", property="recvTime", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="CURRENCY_CODE", property="currencyCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="TRANSTIME", property="transtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANSDATE", property="transdate", jdbcType=JdbcType.VARCHAR),
        @Result(column="CASHBUYPRICE", property="cashbuyprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="EXBUYPRICE", property="exbuyprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="CASHSELLPRICE", property="cashsellprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="EXSELLPRICE", property="exsellprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="EXQUOTEDATE", property="exquotedate", jdbcType=JdbcType.VARCHAR),
        @Result(column="EXQUOTETIME", property="exquotetime", jdbcType=JdbcType.VARCHAR),
        @Result(column="E3RDPAYNO", property="e3rdpayno", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRICE", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="DIRECTION_FLAG", property="directionFlag", jdbcType=JdbcType.CHAR),
        @Result(column="TRAN_AMT", property="tranAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="CLIENT_EXCHANGE_RATE", property="clientExchangeRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="DISCOUNT_TYPE", property="discountType", jdbcType=JdbcType.CHAR),
        @Result(column="DIS_AMT", property="disAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="AMT", property="amt", jdbcType=JdbcType.DECIMAL)
    })
    BForeignCurrencyRate selectByPrimaryKey(BForeignCurrencyRateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:58 CST 2016
     */
    @UpdateProvider(type=BForeignCurrencyRateSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BForeignCurrencyRate record, @Param("example") BForeignCurrencyRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:58 CST 2016
     */
    @UpdateProvider(type=BForeignCurrencyRateSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BForeignCurrencyRate record, @Param("example") BForeignCurrencyRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:58 CST 2016
     */
    @UpdateProvider(type=BForeignCurrencyRateSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BForeignCurrencyRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:58 CST 2016
     */
    @Update({
        "update B_FOREIGN_CURRENCY_RATE",
        "set TRANSTIME = #{transtime,jdbcType=VARCHAR},",
          "TRANSDATE = #{transdate,jdbcType=VARCHAR},",
          "CASHBUYPRICE = #{cashbuyprice,jdbcType=DECIMAL},",
          "EXBUYPRICE = #{exbuyprice,jdbcType=DECIMAL},",
          "CASHSELLPRICE = #{cashsellprice,jdbcType=DECIMAL},",
          "EXSELLPRICE = #{exsellprice,jdbcType=DECIMAL},",
          "EXQUOTEDATE = #{exquotedate,jdbcType=VARCHAR},",
          "EXQUOTETIME = #{exquotetime,jdbcType=VARCHAR},",
          "E3RDPAYNO = #{e3rdpayno,jdbcType=VARCHAR},",
          "PRICE = #{price,jdbcType=DECIMAL},",
          "DIRECTION_FLAG = #{directionFlag,jdbcType=CHAR},",
          "TRAN_AMT = #{tranAmt,jdbcType=DECIMAL},",
          "CLIENT_EXCHANGE_RATE = #{clientExchangeRate,jdbcType=DECIMAL},",
          "DISCOUNT_TYPE = #{discountType,jdbcType=CHAR},",
          "DIS_AMT = #{disAmt,jdbcType=DECIMAL},",
          "AMT = #{amt,jdbcType=DECIMAL}",
        "where FROM_ID = #{fromId,jdbcType=VARCHAR}",
          "and RECV_DATE = #{recvDate,jdbcType=VARCHAR}",
          "and RECV_TIME = #{recvTime,jdbcType=VARCHAR}",
          "and CURRENCY_CODE = #{currencyCode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BForeignCurrencyRate record);
}