package cn.msec.cbpay.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.msec.cbpay.entity.BMerchantOrder;
import cn.msec.cbpay.entity.BMerchantOrderExample;
import cn.msec.cbpay.entity.BMerchantOrderKey;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;

public interface BMerchantOrderMapper extends StaticTableDaoSupport<BMerchantOrder, BMerchantOrderExample, BMerchantOrderKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @SelectProvider(type=BMerchantOrderSqlProvider.class, method="countByExample")
    int countByExample(BMerchantOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @DeleteProvider(type=BMerchantOrderSqlProvider.class, method="deleteByExample")
    int deleteByExample(BMerchantOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @Delete({
        "delete from B_MERCHANT_ORDER",
        "where MERCHANTID = #{merchantid,jdbcType=VARCHAR}",
          "and ORDERID = #{orderid,jdbcType=VARCHAR}",
          "and ORDERDATE = #{orderdate,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(BMerchantOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @Insert({
        "insert into B_MERCHANT_ORDER (MERCHANTID, ORDERID, ",
        "ORDERDATE, PAYJNLNO, ",
        "PAYTIME, ORDERTIME, CLIENTIP, ",
        "PURCHASERID, VALIDUNIT, ",
        "VALIDNUM, ORDERDESC, ",
        "ORDERAMOUNT, CURRENCY, ",
        "MERCHANTPOUNDAGE, PURCHASEAMOUNT, ",
        "CHANNEL, ACCEPTANCERATE, ",
        "ACCEPTANCEMOUNT, ACCEPTANCYCURRENCY, ",
        "ACCEPTANCYPOUNDAGE, ORDERSTATUS, ",
        "PAGERETURNURL, OFFLINENOTIFYURL, ",
        "PAYORDERID, BUYBATNO, ",
        "BUYBATSTATUS, BUYBATRATE, ",
        "UPORDOWNMOUNT, PAYBATNO, ",
        "PAYBATSTATUS, MOUNTCHANGENO, ",
        "MOUNTCHANGESTATUS, SETTLEBATNO, ",
        "SETTLEBATSTATUS, USERID, ",
        "TRADE_TYPE, BUYBATDATE, ",
        "PAYCARD, PAYDATE, TRADE_CODE, ",
        "IS_REF, PAYBATDATE, PRODUCTID, ",
        "PRODUCTNAME, PRODUCTDESC, ",
        "SHOWURL, ISRESPONSE, ",
        "RCVTIME, RCVDATE, ",
        "TMSMP, INVOICENO)",
        "values (#{merchantid,jdbcType=VARCHAR}, #{orderid,jdbcType=VARCHAR}, ",
        "#{orderdate,jdbcType=CHAR}, #{payjnlno,jdbcType=VARCHAR}, ",
        "#{paytime,jdbcType=CHAR}, #{ordertime,jdbcType=CHAR}, #{clientip,jdbcType=VARCHAR}, ",
        "#{purchaserid,jdbcType=VARCHAR}, #{validunit,jdbcType=VARCHAR}, ",
        "#{validnum,jdbcType=VARCHAR}, #{orderdesc,jdbcType=VARCHAR}, ",
        "#{orderamount,jdbcType=DECIMAL}, #{currency,jdbcType=VARCHAR}, ",
        "#{merchantpoundage,jdbcType=DECIMAL}, #{purchaseamount,jdbcType=DECIMAL}, ",
        "#{channel,jdbcType=VARCHAR}, #{acceptancerate,jdbcType=DECIMAL}, ",
        "#{acceptancemount,jdbcType=DECIMAL}, #{acceptancycurrency,jdbcType=VARCHAR}, ",
        "#{acceptancypoundage,jdbcType=DECIMAL}, #{orderstatus,jdbcType=VARCHAR}, ",
        "#{pagereturnurl,jdbcType=VARCHAR}, #{offlinenotifyurl,jdbcType=VARCHAR}, ",
        "#{payorderid,jdbcType=VARCHAR}, #{buybatno,jdbcType=VARCHAR}, ",
        "#{buybatstatus,jdbcType=CHAR}, #{buybatrate,jdbcType=DECIMAL}, ",
        "#{upordownmount,jdbcType=DECIMAL}, #{paybatno,jdbcType=VARCHAR}, ",
        "#{paybatstatus,jdbcType=CHAR}, #{mountchangeno,jdbcType=VARCHAR}, ",
        "#{mountchangestatus,jdbcType=CHAR}, #{settlebatno,jdbcType=VARCHAR}, ",
        "#{settlebatstatus,jdbcType=CHAR}, #{userid,jdbcType=VARCHAR}, ",
        "#{tradeType,jdbcType=VARCHAR}, #{buybatdate,jdbcType=CHAR}, ",
        "#{paycard,jdbcType=VARCHAR}, #{paydate,jdbcType=CHAR}, #{tradeCode,jdbcType=VARCHAR}, ",
        "#{isRef,jdbcType=CHAR}, #{paybatdate,jdbcType=CHAR}, #{productid,jdbcType=VARCHAR}, ",
        "#{productname,jdbcType=VARCHAR}, #{productdesc,jdbcType=VARCHAR}, ",
        "#{showurl,jdbcType=VARCHAR}, #{isresponse,jdbcType=CHAR}, ",
        "#{rcvtime,jdbcType=VARCHAR}, #{rcvdate,jdbcType=VARCHAR}, ",
        "#{tmsmp,jdbcType=VARCHAR}, #{invoiceno,jdbcType=VARCHAR})"
    })
    int insert(BMerchantOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @InsertProvider(type=BMerchantOrderSqlProvider.class, method="insertSelective")
    int insertSelective(BMerchantOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @SelectProvider(type=BMerchantOrderSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="MERCHANTID", property="merchantid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORDERID", property="orderid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORDERDATE", property="orderdate", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="PAYJNLNO", property="payjnlno", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAYTIME", property="paytime", jdbcType=JdbcType.CHAR),
        @Result(column="ORDERTIME", property="ordertime", jdbcType=JdbcType.CHAR),
        @Result(column="CLIENTIP", property="clientip", jdbcType=JdbcType.VARCHAR),
        @Result(column="PURCHASERID", property="purchaserid", jdbcType=JdbcType.VARCHAR),
        @Result(column="VALIDUNIT", property="validunit", jdbcType=JdbcType.VARCHAR),
        @Result(column="VALIDNUM", property="validnum", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORDERDESC", property="orderdesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORDERAMOUNT", property="orderamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURRENCY", property="currency", jdbcType=JdbcType.VARCHAR),
        @Result(column="MERCHANTPOUNDAGE", property="merchantpoundage", jdbcType=JdbcType.DECIMAL),
        @Result(column="PURCHASEAMOUNT", property="purchaseamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHANNEL", property="channel", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACCEPTANCERATE", property="acceptancerate", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACCEPTANCEMOUNT", property="acceptancemount", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACCEPTANCYCURRENCY", property="acceptancycurrency", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACCEPTANCYPOUNDAGE", property="acceptancypoundage", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORDERSTATUS", property="orderstatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAGERETURNURL", property="pagereturnurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="OFFLINENOTIFYURL", property="offlinenotifyurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAYORDERID", property="payorderid", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUYBATNO", property="buybatno", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUYBATSTATUS", property="buybatstatus", jdbcType=JdbcType.CHAR),
        @Result(column="BUYBATRATE", property="buybatrate", jdbcType=JdbcType.DECIMAL),
        @Result(column="UPORDOWNMOUNT", property="upordownmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAYBATNO", property="paybatno", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAYBATSTATUS", property="paybatstatus", jdbcType=JdbcType.CHAR),
        @Result(column="MOUNTCHANGENO", property="mountchangeno", jdbcType=JdbcType.VARCHAR),
        @Result(column="MOUNTCHANGESTATUS", property="mountchangestatus", jdbcType=JdbcType.CHAR),
        @Result(column="SETTLEBATNO", property="settlebatno", jdbcType=JdbcType.VARCHAR),
        @Result(column="SETTLEBATSTATUS", property="settlebatstatus", jdbcType=JdbcType.CHAR),
        @Result(column="USERID", property="userid", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRADE_TYPE", property="tradeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUYBATDATE", property="buybatdate", jdbcType=JdbcType.CHAR),
        @Result(column="PAYCARD", property="paycard", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAYDATE", property="paydate", jdbcType=JdbcType.CHAR),
        @Result(column="TRADE_CODE", property="tradeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="IS_REF", property="isRef", jdbcType=JdbcType.CHAR),
        @Result(column="PAYBATDATE", property="paybatdate", jdbcType=JdbcType.CHAR),
        @Result(column="PRODUCTID", property="productid", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRODUCTNAME", property="productname", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRODUCTDESC", property="productdesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="SHOWURL", property="showurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISRESPONSE", property="isresponse", jdbcType=JdbcType.CHAR),
        @Result(column="RCVTIME", property="rcvtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="RCVDATE", property="rcvdate", jdbcType=JdbcType.VARCHAR),
        @Result(column="TMSMP", property="tmsmp", jdbcType=JdbcType.VARCHAR),
        @Result(column="INVOICENO", property="invoiceno", jdbcType=JdbcType.VARCHAR)
    })
    List<BMerchantOrder> selectByExample(BMerchantOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @Select({
        "select",
        "MERCHANTID, ORDERID, ORDERDATE, PAYJNLNO, PAYTIME, ORDERTIME, CLIENTIP, PURCHASERID, ",
        "VALIDUNIT, VALIDNUM, ORDERDESC, ORDERAMOUNT, CURRENCY, MERCHANTPOUNDAGE, PURCHASEAMOUNT, ",
        "CHANNEL, ACCEPTANCERATE, ACCEPTANCEMOUNT, ACCEPTANCYCURRENCY, ACCEPTANCYPOUNDAGE, ",
        "ORDERSTATUS, PAGERETURNURL, OFFLINENOTIFYURL, PAYORDERID, BUYBATNO, BUYBATSTATUS, ",
        "BUYBATRATE, UPORDOWNMOUNT, PAYBATNO, PAYBATSTATUS, MOUNTCHANGENO, MOUNTCHANGESTATUS, ",
        "SETTLEBATNO, SETTLEBATSTATUS, USERID, TRADE_TYPE, BUYBATDATE, PAYCARD, PAYDATE, ",
        "TRADE_CODE, IS_REF, PAYBATDATE, PRODUCTID, PRODUCTNAME, PRODUCTDESC, SHOWURL, ",
        "ISRESPONSE, RCVTIME, RCVDATE, TMSMP, INVOICENO",
        "from B_MERCHANT_ORDER",
        "where MERCHANTID = #{merchantid,jdbcType=VARCHAR}",
          "and ORDERID = #{orderid,jdbcType=VARCHAR}",
          "and ORDERDATE = #{orderdate,jdbcType=CHAR}"
    })
    @Results({
        @Result(column="MERCHANTID", property="merchantid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORDERID", property="orderid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="ORDERDATE", property="orderdate", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="PAYJNLNO", property="payjnlno", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAYTIME", property="paytime", jdbcType=JdbcType.CHAR),
        @Result(column="ORDERTIME", property="ordertime", jdbcType=JdbcType.CHAR),
        @Result(column="CLIENTIP", property="clientip", jdbcType=JdbcType.VARCHAR),
        @Result(column="PURCHASERID", property="purchaserid", jdbcType=JdbcType.VARCHAR),
        @Result(column="VALIDUNIT", property="validunit", jdbcType=JdbcType.VARCHAR),
        @Result(column="VALIDNUM", property="validnum", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORDERDESC", property="orderdesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="ORDERAMOUNT", property="orderamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURRENCY", property="currency", jdbcType=JdbcType.VARCHAR),
        @Result(column="MERCHANTPOUNDAGE", property="merchantpoundage", jdbcType=JdbcType.DECIMAL),
        @Result(column="PURCHASEAMOUNT", property="purchaseamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="CHANNEL", property="channel", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACCEPTANCERATE", property="acceptancerate", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACCEPTANCEMOUNT", property="acceptancemount", jdbcType=JdbcType.DECIMAL),
        @Result(column="ACCEPTANCYCURRENCY", property="acceptancycurrency", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACCEPTANCYPOUNDAGE", property="acceptancypoundage", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORDERSTATUS", property="orderstatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAGERETURNURL", property="pagereturnurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="OFFLINENOTIFYURL", property="offlinenotifyurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAYORDERID", property="payorderid", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUYBATNO", property="buybatno", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUYBATSTATUS", property="buybatstatus", jdbcType=JdbcType.CHAR),
        @Result(column="BUYBATRATE", property="buybatrate", jdbcType=JdbcType.DECIMAL),
        @Result(column="UPORDOWNMOUNT", property="upordownmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAYBATNO", property="paybatno", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAYBATSTATUS", property="paybatstatus", jdbcType=JdbcType.CHAR),
        @Result(column="MOUNTCHANGENO", property="mountchangeno", jdbcType=JdbcType.VARCHAR),
        @Result(column="MOUNTCHANGESTATUS", property="mountchangestatus", jdbcType=JdbcType.CHAR),
        @Result(column="SETTLEBATNO", property="settlebatno", jdbcType=JdbcType.VARCHAR),
        @Result(column="SETTLEBATSTATUS", property="settlebatstatus", jdbcType=JdbcType.CHAR),
        @Result(column="USERID", property="userid", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRADE_TYPE", property="tradeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="BUYBATDATE", property="buybatdate", jdbcType=JdbcType.CHAR),
        @Result(column="PAYCARD", property="paycard", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAYDATE", property="paydate", jdbcType=JdbcType.CHAR),
        @Result(column="TRADE_CODE", property="tradeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="IS_REF", property="isRef", jdbcType=JdbcType.CHAR),
        @Result(column="PAYBATDATE", property="paybatdate", jdbcType=JdbcType.CHAR),
        @Result(column="PRODUCTID", property="productid", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRODUCTNAME", property="productname", jdbcType=JdbcType.VARCHAR),
        @Result(column="PRODUCTDESC", property="productdesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="SHOWURL", property="showurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISRESPONSE", property="isresponse", jdbcType=JdbcType.CHAR),
        @Result(column="RCVTIME", property="rcvtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="RCVDATE", property="rcvdate", jdbcType=JdbcType.VARCHAR),
        @Result(column="TMSMP", property="tmsmp", jdbcType=JdbcType.VARCHAR),
        @Result(column="INVOICENO", property="invoiceno", jdbcType=JdbcType.VARCHAR)
    })
    BMerchantOrder selectByPrimaryKey(BMerchantOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @UpdateProvider(type=BMerchantOrderSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BMerchantOrder record, @Param("example") BMerchantOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @UpdateProvider(type=BMerchantOrderSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BMerchantOrder record, @Param("example") BMerchantOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @UpdateProvider(type=BMerchantOrderSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BMerchantOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @Update({
        "update B_MERCHANT_ORDER",
        "set PAYJNLNO = #{payjnlno,jdbcType=VARCHAR},",
          "PAYTIME = #{paytime,jdbcType=CHAR},",
          "ORDERTIME = #{ordertime,jdbcType=CHAR},",
          "CLIENTIP = #{clientip,jdbcType=VARCHAR},",
          "PURCHASERID = #{purchaserid,jdbcType=VARCHAR},",
          "VALIDUNIT = #{validunit,jdbcType=VARCHAR},",
          "VALIDNUM = #{validnum,jdbcType=VARCHAR},",
          "ORDERDESC = #{orderdesc,jdbcType=VARCHAR},",
          "ORDERAMOUNT = #{orderamount,jdbcType=DECIMAL},",
          "CURRENCY = #{currency,jdbcType=VARCHAR},",
          "MERCHANTPOUNDAGE = #{merchantpoundage,jdbcType=DECIMAL},",
          "PURCHASEAMOUNT = #{purchaseamount,jdbcType=DECIMAL},",
          "CHANNEL = #{channel,jdbcType=VARCHAR},",
          "ACCEPTANCERATE = #{acceptancerate,jdbcType=DECIMAL},",
          "ACCEPTANCEMOUNT = #{acceptancemount,jdbcType=DECIMAL},",
          "ACCEPTANCYCURRENCY = #{acceptancycurrency,jdbcType=VARCHAR},",
          "ACCEPTANCYPOUNDAGE = #{acceptancypoundage,jdbcType=DECIMAL},",
          "ORDERSTATUS = #{orderstatus,jdbcType=VARCHAR},",
          "PAGERETURNURL = #{pagereturnurl,jdbcType=VARCHAR},",
          "OFFLINENOTIFYURL = #{offlinenotifyurl,jdbcType=VARCHAR},",
          "PAYORDERID = #{payorderid,jdbcType=VARCHAR},",
          "BUYBATNO = #{buybatno,jdbcType=VARCHAR},",
          "BUYBATSTATUS = #{buybatstatus,jdbcType=CHAR},",
          "BUYBATRATE = #{buybatrate,jdbcType=DECIMAL},",
          "UPORDOWNMOUNT = #{upordownmount,jdbcType=DECIMAL},",
          "PAYBATNO = #{paybatno,jdbcType=VARCHAR},",
          "PAYBATSTATUS = #{paybatstatus,jdbcType=CHAR},",
          "MOUNTCHANGENO = #{mountchangeno,jdbcType=VARCHAR},",
          "MOUNTCHANGESTATUS = #{mountchangestatus,jdbcType=CHAR},",
          "SETTLEBATNO = #{settlebatno,jdbcType=VARCHAR},",
          "SETTLEBATSTATUS = #{settlebatstatus,jdbcType=CHAR},",
          "USERID = #{userid,jdbcType=VARCHAR},",
          "TRADE_TYPE = #{tradeType,jdbcType=VARCHAR},",
          "BUYBATDATE = #{buybatdate,jdbcType=CHAR},",
          "PAYCARD = #{paycard,jdbcType=VARCHAR},",
          "PAYDATE = #{paydate,jdbcType=CHAR},",
          "TRADE_CODE = #{tradeCode,jdbcType=VARCHAR},",
          "IS_REF = #{isRef,jdbcType=CHAR},",
          "PAYBATDATE = #{paybatdate,jdbcType=CHAR},",
          "PRODUCTID = #{productid,jdbcType=VARCHAR},",
          "PRODUCTNAME = #{productname,jdbcType=VARCHAR},",
          "PRODUCTDESC = #{productdesc,jdbcType=VARCHAR},",
          "SHOWURL = #{showurl,jdbcType=VARCHAR},",
          "ISRESPONSE = #{isresponse,jdbcType=CHAR},",
          "RCVTIME = #{rcvtime,jdbcType=VARCHAR},",
          "RCVDATE = #{rcvdate,jdbcType=VARCHAR},",
          "TMSMP = #{tmsmp,jdbcType=VARCHAR},",
          "INVOICENO = #{invoiceno,jdbcType=VARCHAR}",
        "where MERCHANTID = #{merchantid,jdbcType=VARCHAR}",
          "and ORDERID = #{orderid,jdbcType=VARCHAR}",
          "and ORDERDATE = #{orderdate,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(BMerchantOrder record);
}