package cn.msec.cbpay.mapper;

import java.util.List;

import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.msec.cbpay.entity.BMerchantPermission;
import cn.msec.cbpay.entity.BMerchantPermissionExample;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;

public interface BMerchantPermissionMapper extends StaticTableDaoSupport<BMerchantPermission, BMerchantPermissionExample, BMerchantPermission> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_PERMISSION
     *
     * @mbggenerated Tue May 03 11:14:41 CST 2016
     */
    @SelectProvider(type=BMerchantPermissionSqlProvider.class, method="countByExample")
    int countByExample(BMerchantPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_PERMISSION
     *
     * @mbggenerated Tue May 03 11:14:41 CST 2016
     */
    @DeleteProvider(type=BMerchantPermissionSqlProvider.class, method="deleteByExample")
    int deleteByExample(BMerchantPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_PERMISSION
     *
     * @mbggenerated Tue May 03 11:14:41 CST 2016
     */
    @Insert({
        "insert into B_MERCHANT_PERMISSION (MERCHANTID, TRANCODE, ",
        "VALID)",
        "values (#{merchantid,jdbcType=VARCHAR}, #{trancode,jdbcType=VARCHAR}, ",
        "#{valid,jdbcType=CHAR})"
    })
    int insert(BMerchantPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_PERMISSION
     *
     * @mbggenerated Tue May 03 11:14:41 CST 2016
     */
    @InsertProvider(type=BMerchantPermissionSqlProvider.class, method="insertSelective")
    int insertSelective(BMerchantPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_PERMISSION
     *
     * @mbggenerated Tue May 03 11:14:41 CST 2016
     */
    @SelectProvider(type=BMerchantPermissionSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="MERCHANTID", property="merchantid", jdbcType=JdbcType.VARCHAR),
        @Result(column="TRANCODE", property="trancode", jdbcType=JdbcType.VARCHAR),
        @Result(column="VALID", property="valid", jdbcType=JdbcType.CHAR)
    })
    List<BMerchantPermission> selectByExample(BMerchantPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_PERMISSION
     *
     * @mbggenerated Tue May 03 11:14:41 CST 2016
     */
    @UpdateProvider(type=BMerchantPermissionSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BMerchantPermission record, @Param("example") BMerchantPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_PERMISSION
     *
     * @mbggenerated Tue May 03 11:14:41 CST 2016
     */
    @UpdateProvider(type=BMerchantPermissionSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BMerchantPermission record, @Param("example") BMerchantPermissionExample example);
}