package cn.msec.cbpay.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.msec.cbpay.entity.BUMBCheckingLog;
import cn.msec.cbpay.entity.BUMBCheckingLogExample;
import cn.msec.cbpay.entity.BUMBCheckingLogKey;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;

public interface BUMBCheckingLogMapper extends StaticTableDaoSupport<BUMBCheckingLog, BUMBCheckingLogExample, BUMBCheckingLogKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    @SelectProvider(type=BUMBCheckingLogSqlProvider.class, method="countByExample")
    int countByExample(BUMBCheckingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    @DeleteProvider(type=BUMBCheckingLogSqlProvider.class, method="deleteByExample")
    int deleteByExample(BUMBCheckingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    @Delete({
        "delete from B_UMB_CHECKING_LOG",
        "where JNLNO = #{jnlno,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(BUMBCheckingLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    @Insert({
        "insert into B_UMB_CHECKING_LOG (JNLNO, TRANDATE, ",
        "ACCOUNTDATE, CHECKTYPE, ",
        "STATUS, DONETIME, FILENAME)",
        "values (#{jnlno,jdbcType=VARCHAR}, #{trandate,jdbcType=VARCHAR}, ",
        "#{accountdate,jdbcType=VARCHAR}, #{checktype,jdbcType=CHAR}, ",
        "#{status,jdbcType=CHAR}, #{donetime,jdbcType=VARCHAR}, #{filename,jdbcType=VARCHAR})"
    })
    int insert(BUMBCheckingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    @InsertProvider(type=BUMBCheckingLogSqlProvider.class, method="insertSelective")
    int insertSelective(BUMBCheckingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    @SelectProvider(type=BUMBCheckingLogSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="JNLNO", property="jnlno", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="TRANDATE", property="trandate", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACCOUNTDATE", property="accountdate", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHECKTYPE", property="checktype", jdbcType=JdbcType.CHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="DONETIME", property="donetime", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILENAME", property="filename", jdbcType=JdbcType.VARCHAR)
    })
    List<BUMBCheckingLog> selectByExample(BUMBCheckingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    @Select({
        "select",
        "JNLNO, TRANDATE, ACCOUNTDATE, CHECKTYPE, STATUS, DONETIME, FILENAME",
        "from B_UMB_CHECKING_LOG",
        "where JNLNO = #{jnlno,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="JNLNO", property="jnlno", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="TRANDATE", property="trandate", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACCOUNTDATE", property="accountdate", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHECKTYPE", property="checktype", jdbcType=JdbcType.CHAR),
        @Result(column="STATUS", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="DONETIME", property="donetime", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILENAME", property="filename", jdbcType=JdbcType.VARCHAR)
    })
    BUMBCheckingLog selectByPrimaryKey(BUMBCheckingLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    @UpdateProvider(type=BUMBCheckingLogSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BUMBCheckingLog record, @Param("example") BUMBCheckingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    @UpdateProvider(type=BUMBCheckingLogSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BUMBCheckingLog record, @Param("example") BUMBCheckingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    @UpdateProvider(type=BUMBCheckingLogSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BUMBCheckingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    @Update({
        "update B_UMB_CHECKING_LOG",
        "set TRANDATE = #{trandate,jdbcType=VARCHAR},",
          "ACCOUNTDATE = #{accountdate,jdbcType=VARCHAR},",
          "CHECKTYPE = #{checktype,jdbcType=CHAR},",
          "STATUS = #{status,jdbcType=CHAR},",
          "DONETIME = #{donetime,jdbcType=VARCHAR},",
          "FILENAME = #{filename,jdbcType=VARCHAR}",
        "where JNLNO = #{jnlno,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BUMBCheckingLog record);
}