package cn.msec.cbpay.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;

import cn.msec.cbpay.entity.BUMBCheckingLog;
import cn.msec.cbpay.entity.BUMBCheckingLogExample;
import cn.msec.cbpay.entity.BUMBCheckingLogExample.Criteria;
import cn.msec.cbpay.entity.BUMBCheckingLogExample.Criterion;

public class BUMBCheckingLogSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    public String countByExample(BUMBCheckingLogExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("B_UMB_CHECKING_LOG");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    public String deleteByExample(BUMBCheckingLogExample example) {
        BEGIN();
        DELETE_FROM("B_UMB_CHECKING_LOG");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    public String insertSelective(BUMBCheckingLog record) {
        BEGIN();
        INSERT_INTO("B_UMB_CHECKING_LOG");
        
        if (record.getJnlno() != null) {
            VALUES("JNLNO", "#{jnlno,jdbcType=VARCHAR}");
        }
        
        if (record.getTrandate() != null) {
            VALUES("TRANDATE", "#{trandate,jdbcType=VARCHAR}");
        }
        
        if (record.getAccountdate() != null) {
            VALUES("ACCOUNTDATE", "#{accountdate,jdbcType=VARCHAR}");
        }
        
        if (record.getChecktype() != null) {
            VALUES("CHECKTYPE", "#{checktype,jdbcType=CHAR}");
        }
        
        if (record.getStatus() != null) {
            VALUES("STATUS", "#{status,jdbcType=CHAR}");
        }
        
        if (record.getDonetime() != null) {
            VALUES("DONETIME", "#{donetime,jdbcType=VARCHAR}");
        }
        
        if (record.getFilename() != null) {
            VALUES("FILENAME", "#{filename,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    public String selectByExample(BUMBCheckingLogExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("JNLNO");
        } else {
            SELECT("JNLNO");
        }
        SELECT("TRANDATE");
        SELECT("ACCOUNTDATE");
        SELECT("CHECKTYPE");
        SELECT("STATUS");
        SELECT("DONETIME");
        SELECT("FILENAME");
        FROM("B_UMB_CHECKING_LOG");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example != null){
            return SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
        }
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        BUMBCheckingLog record = (BUMBCheckingLog) parameter.get("record");
        BUMBCheckingLogExample example = (BUMBCheckingLogExample) parameter.get("example");
        
        BEGIN();
        UPDATE("B_UMB_CHECKING_LOG");
        
        if (record.getJnlno() != null) {
            SET("JNLNO = #{record.jnlno,jdbcType=VARCHAR}");
        }
        
        if (record.getTrandate() != null) {
            SET("TRANDATE = #{record.trandate,jdbcType=VARCHAR}");
        }
        
        if (record.getAccountdate() != null) {
            SET("ACCOUNTDATE = #{record.accountdate,jdbcType=VARCHAR}");
        }
        
        if (record.getChecktype() != null) {
            SET("CHECKTYPE = #{record.checktype,jdbcType=CHAR}");
        }
        
        if (record.getStatus() != null) {
            SET("STATUS = #{record.status,jdbcType=CHAR}");
        }
        
        if (record.getDonetime() != null) {
            SET("DONETIME = #{record.donetime,jdbcType=VARCHAR}");
        }
        
        if (record.getFilename() != null) {
            SET("FILENAME = #{record.filename,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("B_UMB_CHECKING_LOG");
        
        SET("JNLNO = #{record.jnlno,jdbcType=VARCHAR}");
        SET("TRANDATE = #{record.trandate,jdbcType=VARCHAR}");
        SET("ACCOUNTDATE = #{record.accountdate,jdbcType=VARCHAR}");
        SET("CHECKTYPE = #{record.checktype,jdbcType=CHAR}");
        SET("STATUS = #{record.status,jdbcType=CHAR}");
        SET("DONETIME = #{record.donetime,jdbcType=VARCHAR}");
        SET("FILENAME = #{record.filename,jdbcType=VARCHAR}");
        
        BUMBCheckingLogExample example = (BUMBCheckingLogExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    public String updateByPrimaryKeySelective(BUMBCheckingLog record) {
        BEGIN();
        UPDATE("B_UMB_CHECKING_LOG");
        
        if (record.getTrandate() != null) {
            SET("TRANDATE = #{trandate,jdbcType=VARCHAR}");
        }
        
        if (record.getAccountdate() != null) {
            SET("ACCOUNTDATE = #{accountdate,jdbcType=VARCHAR}");
        }
        
        if (record.getChecktype() != null) {
            SET("CHECKTYPE = #{checktype,jdbcType=CHAR}");
        }
        
        if (record.getStatus() != null) {
            SET("STATUS = #{status,jdbcType=CHAR}");
        }
        
        if (record.getDonetime() != null) {
            SET("DONETIME = #{donetime,jdbcType=VARCHAR}");
        }
        
        if (record.getFilename() != null) {
            SET("FILENAME = #{filename,jdbcType=VARCHAR}");
        }
        
        WHERE("JNLNO = #{jnlno,jdbcType=VARCHAR}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_UMB_CHECKING_LOG
     *
     * @mbggenerated Tue Mar 29 14:37:12 CST 2016
     */
    protected void applyWhere(BUMBCheckingLogExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}