package cn.msec.cbpay.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import java.util.List;
import java.util.Map;

import cn.msec.cbpay.entity.BUserCard;
import cn.msec.cbpay.entity.BUserCardExample;
import cn.msec.cbpay.entity.BUserCardExample.Criteria;
import cn.msec.cbpay.entity.BUserCardExample.Criterion;

public class BUserCardSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_CARD
     *
     * @mbggenerated Thu Mar 24 14:15:40 CST 2016
     */
    public String countByExample(BUserCardExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("B_USER_CARD");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_CARD
     *
     * @mbggenerated Thu Mar 24 14:15:40 CST 2016
     */
    public String deleteByExample(BUserCardExample example) {
        BEGIN();
        DELETE_FROM("B_USER_CARD");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_CARD
     *
     * @mbggenerated Thu Mar 24 14:15:40 CST 2016
     */
    public String insertSelective(BUserCard record) {
        BEGIN();
        INSERT_INTO("B_USER_CARD");
        
        if (record.getMerchantid() != null) {
            VALUES("MERCHANTID", "#{merchantid,jdbcType=VARCHAR}");
        }
        
        if (record.getPurchaserid() != null) {
            VALUES("PURCHASERID", "#{purchaserid,jdbcType=VARCHAR}");
        }
        
        if (record.getCardid() != null) {
            VALUES("CARDID", "#{cardid,jdbcType=VARCHAR}");
        }
        
        if (record.getValid() != null) {
            VALUES("VALID", "#{valid,jdbcType=CHAR}");
        }
        
        if (record.getCreatetime() != null) {
            VALUES("CREATETIME", "#{createtime,jdbcType=VARCHAR}");
        }
        
        if (record.getBankname() != null) {
            VALUES("BANKNAME", "#{bankname,jdbcType=VARCHAR}");
        }
        
        if (record.getOpenprovince() != null) {
            VALUES("OPENPROVINCE", "#{openprovince,jdbcType=VARCHAR}");
        }
        
        if (record.getOpencity() != null) {
            VALUES("OPENCITY", "#{opencity,jdbcType=VARCHAR}");
        }
        
        if (record.getOpenname() != null) {
            VALUES("OPENNAME", "#{openname,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_CARD
     *
     * @mbggenerated Thu Mar 24 14:15:40 CST 2016
     */
    public String selectByExample(BUserCardExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("MERCHANTID");
        } else {
            SELECT("MERCHANTID");
        }
        SELECT("PURCHASERID");
        SELECT("CARDID");
        SELECT("VALID");
        SELECT("CREATETIME");
        SELECT("BANKNAME");
        SELECT("OPENPROVINCE");
        SELECT("OPENCITY");
        SELECT("OPENNAME");
        FROM("B_USER_CARD");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        if(example != null){
            return SQL().concat(" limit "+example.getOffset()+","+example.getLimit());
        }
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_CARD
     *
     * @mbggenerated Thu Mar 24 14:15:40 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        BUserCard record = (BUserCard) parameter.get("record");
        BUserCardExample example = (BUserCardExample) parameter.get("example");
        
        BEGIN();
        UPDATE("B_USER_CARD");
        
        if (record.getMerchantid() != null) {
            SET("MERCHANTID = #{record.merchantid,jdbcType=VARCHAR}");
        }
        
        if (record.getPurchaserid() != null) {
            SET("PURCHASERID = #{record.purchaserid,jdbcType=VARCHAR}");
        }
        
        if (record.getCardid() != null) {
            SET("CARDID = #{record.cardid,jdbcType=VARCHAR}");
        }
        
        if (record.getValid() != null) {
            SET("VALID = #{record.valid,jdbcType=CHAR}");
        }
        
        if (record.getCreatetime() != null) {
            SET("CREATETIME = #{record.createtime,jdbcType=VARCHAR}");
        }
        
        if (record.getBankname() != null) {
            SET("BANKNAME = #{record.bankname,jdbcType=VARCHAR}");
        }
        
        if (record.getOpenprovince() != null) {
            SET("OPENPROVINCE = #{record.openprovince,jdbcType=VARCHAR}");
        }
        
        if (record.getOpencity() != null) {
            SET("OPENCITY = #{record.opencity,jdbcType=VARCHAR}");
        }
        
        if (record.getOpenname() != null) {
            SET("OPENNAME = #{record.openname,jdbcType=VARCHAR}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_CARD
     *
     * @mbggenerated Thu Mar 24 14:15:40 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("B_USER_CARD");
        
        SET("MERCHANTID = #{record.merchantid,jdbcType=VARCHAR}");
        SET("PURCHASERID = #{record.purchaserid,jdbcType=VARCHAR}");
        SET("CARDID = #{record.cardid,jdbcType=VARCHAR}");
        SET("VALID = #{record.valid,jdbcType=CHAR}");
        SET("CREATETIME = #{record.createtime,jdbcType=VARCHAR}");
        SET("BANKNAME = #{record.bankname,jdbcType=VARCHAR}");
        SET("OPENPROVINCE = #{record.openprovince,jdbcType=VARCHAR}");
        SET("OPENCITY = #{record.opencity,jdbcType=VARCHAR}");
        SET("OPENNAME = #{record.openname,jdbcType=VARCHAR}");
        
        BUserCardExample example = (BUserCardExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_CARD
     *
     * @mbggenerated Thu Mar 24 14:15:40 CST 2016
     */
    protected void applyWhere(BUserCardExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}