package cn.msec.cbpay.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.msec.cbpay.entity.BUserInfo;
import cn.msec.cbpay.entity.BUserInfoExample;
import cn.msec.cbpay.entity.BUserInfoKey;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;

public interface BUserInfoMapper extends StaticTableDaoSupport<BUserInfo, BUserInfoExample, BUserInfoKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_INFO
     *
     * @mbggenerated Wed Mar 23 17:39:39 CST 2016
     */
    @SelectProvider(type=BUserInfoSqlProvider.class, method="countByExample")
    int countByExample(BUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_INFO
     *
     * @mbggenerated Wed Mar 23 17:39:39 CST 2016
     */
    @DeleteProvider(type=BUserInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(BUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_INFO
     *
     * @mbggenerated Wed Mar 23 17:39:39 CST 2016
     */
    @Delete({
        "delete from B_USER_INFO",
        "where PURCHASERID = #{purchaserid,jdbcType=VARCHAR}",
          "and MERCHANTID = #{merchantid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(BUserInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_INFO
     *
     * @mbggenerated Wed Mar 23 17:39:39 CST 2016
     */
    @Insert({
        "insert into B_USER_INFO (PURCHASERID, MERCHANTID, ",
        "NICKNAME, USRSTS, ",
        "REALNMFLG, REALNAME, ",
        "IDTYP, IDNO, REGDATE, ",
        "REGTIME, REGCHNL, ",
        "EMAIL, TMSMP, TELNUM)",
        "values (#{purchaserid,jdbcType=VARCHAR}, #{merchantid,jdbcType=VARCHAR}, ",
        "#{nickname,jdbcType=VARCHAR}, #{usrsts,jdbcType=VARCHAR}, ",
        "#{realnmflg,jdbcType=VARCHAR}, #{realname,jdbcType=VARCHAR}, ",
        "#{idtyp,jdbcType=VARCHAR}, #{idno,jdbcType=VARCHAR}, #{regdate,jdbcType=VARCHAR}, ",
        "#{regtime,jdbcType=VARCHAR}, #{regchnl,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR}, #{tmsmp,jdbcType=VARCHAR}, #{telnum,jdbcType=VARCHAR})"
    })
    int insert(BUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_INFO
     *
     * @mbggenerated Wed Mar 23 17:39:39 CST 2016
     */
    @InsertProvider(type=BUserInfoSqlProvider.class, method="insertSelective")
    int insertSelective(BUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_INFO
     *
     * @mbggenerated Wed Mar 23 17:39:39 CST 2016
     */
    @SelectProvider(type=BUserInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="PURCHASERID", property="purchaserid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MERCHANTID", property="merchantid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="NICKNAME", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="USRSTS", property="usrsts", jdbcType=JdbcType.VARCHAR),
        @Result(column="REALNMFLG", property="realnmflg", jdbcType=JdbcType.VARCHAR),
        @Result(column="REALNAME", property="realname", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDTYP", property="idtyp", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDNO", property="idno", jdbcType=JdbcType.VARCHAR),
        @Result(column="REGDATE", property="regdate", jdbcType=JdbcType.VARCHAR),
        @Result(column="REGTIME", property="regtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="REGCHNL", property="regchnl", jdbcType=JdbcType.VARCHAR),
        @Result(column="EMAIL", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="TMSMP", property="tmsmp", jdbcType=JdbcType.VARCHAR),
        @Result(column="TELNUM", property="telnum", jdbcType=JdbcType.VARCHAR)
    })
    List<BUserInfo> selectByExample(BUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_INFO
     *
     * @mbggenerated Wed Mar 23 17:39:39 CST 2016
     */
    @Select({
        "select",
        "PURCHASERID, MERCHANTID, NICKNAME, USRSTS, REALNMFLG, REALNAME, IDTYP, IDNO, ",
        "REGDATE, REGTIME, REGCHNL, EMAIL, TMSMP, TELNUM",
        "from B_USER_INFO",
        "where PURCHASERID = #{purchaserid,jdbcType=VARCHAR}",
          "and MERCHANTID = #{merchantid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="PURCHASERID", property="purchaserid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MERCHANTID", property="merchantid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="NICKNAME", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="USRSTS", property="usrsts", jdbcType=JdbcType.VARCHAR),
        @Result(column="REALNMFLG", property="realnmflg", jdbcType=JdbcType.VARCHAR),
        @Result(column="REALNAME", property="realname", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDTYP", property="idtyp", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDNO", property="idno", jdbcType=JdbcType.VARCHAR),
        @Result(column="REGDATE", property="regdate", jdbcType=JdbcType.VARCHAR),
        @Result(column="REGTIME", property="regtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="REGCHNL", property="regchnl", jdbcType=JdbcType.VARCHAR),
        @Result(column="EMAIL", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="TMSMP", property="tmsmp", jdbcType=JdbcType.VARCHAR),
        @Result(column="TELNUM", property="telnum", jdbcType=JdbcType.VARCHAR)
    })
    BUserInfo selectByPrimaryKey(BUserInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_INFO
     *
     * @mbggenerated Wed Mar 23 17:39:39 CST 2016
     */
    @UpdateProvider(type=BUserInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BUserInfo record, @Param("example") BUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_INFO
     *
     * @mbggenerated Wed Mar 23 17:39:39 CST 2016
     */
    @UpdateProvider(type=BUserInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BUserInfo record, @Param("example") BUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_INFO
     *
     * @mbggenerated Wed Mar 23 17:39:39 CST 2016
     */
    @UpdateProvider(type=BUserInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_INFO
     *
     * @mbggenerated Wed Mar 23 17:39:39 CST 2016
     */
    @Update({
        "update B_USER_INFO",
        "set NICKNAME = #{nickname,jdbcType=VARCHAR},",
          "USRSTS = #{usrsts,jdbcType=VARCHAR},",
          "REALNMFLG = #{realnmflg,jdbcType=VARCHAR},",
          "REALNAME = #{realname,jdbcType=VARCHAR},",
          "IDTYP = #{idtyp,jdbcType=VARCHAR},",
          "IDNO = #{idno,jdbcType=VARCHAR},",
          "REGDATE = #{regdate,jdbcType=VARCHAR},",
          "REGTIME = #{regtime,jdbcType=VARCHAR},",
          "REGCHNL = #{regchnl,jdbcType=VARCHAR},",
          "EMAIL = #{email,jdbcType=VARCHAR},",
          "TMSMP = #{tmsmp,jdbcType=VARCHAR},",
          "TELNUM = #{telnum,jdbcType=VARCHAR}",
        "where PURCHASERID = #{purchaserid,jdbcType=VARCHAR}",
          "and MERCHANTID = #{merchantid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(BUserInfo record);
}