package cn.msec.cbpay.mapper;

import java.util.List;

import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.msec.cbpay.entity.BUserCard;
import cn.msec.cbpay.entity.BUserCardExample;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;

public interface BUserCardMapper extends StaticTableDaoSupport<BUserCard, BUserCardExample, BUserCard> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_CARD
     *
     * @mbggenerated Thu Mar 24 14:15:40 CST 2016
     */
    @SelectProvider(type=BUserCardSqlProvider.class, method="countByExample")
    int countByExample(BUserCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_CARD
     *
     * @mbggenerated Thu Mar 24 14:15:40 CST 2016
     */
    @DeleteProvider(type=BUserCardSqlProvider.class, method="deleteByExample")
    int deleteByExample(BUserCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_CARD
     *
     * @mbggenerated Thu Mar 24 14:15:40 CST 2016
     */
    @Insert({
        "insert into B_USER_CARD (MERCHANTID, PURCHASERID, ",
        "CARDID, VALID, CREATETIME, ",
        "BANKNAME, OPENPROVINCE, ",
        "OPENCITY, OPENNAME)",
        "values (#{merchantid,jdbcType=VARCHAR}, #{purchaserid,jdbcType=VARCHAR}, ",
        "#{cardid,jdbcType=VARCHAR}, #{valid,jdbcType=CHAR}, #{createtime,jdbcType=VARCHAR}, ",
        "#{bankname,jdbcType=VARCHAR}, #{openprovince,jdbcType=VARCHAR}, ",
        "#{opencity,jdbcType=VARCHAR}, #{openname,jdbcType=VARCHAR})"
    })
    int insert(BUserCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_CARD
     *
     * @mbggenerated Thu Mar 24 14:15:40 CST 2016
     */
    @InsertProvider(type=BUserCardSqlProvider.class, method="insertSelective")
    int insertSelective(BUserCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_CARD
     *
     * @mbggenerated Thu Mar 24 14:15:40 CST 2016
     */
    @SelectProvider(type=BUserCardSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="MERCHANTID", property="merchantid", jdbcType=JdbcType.VARCHAR),
        @Result(column="PURCHASERID", property="purchaserid", jdbcType=JdbcType.VARCHAR),
        @Result(column="CARDID", property="cardid", jdbcType=JdbcType.VARCHAR),
        @Result(column="VALID", property="valid", jdbcType=JdbcType.CHAR),
        @Result(column="CREATETIME", property="createtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="BANKNAME", property="bankname", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPENPROVINCE", property="openprovince", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPENCITY", property="opencity", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPENNAME", property="openname", jdbcType=JdbcType.VARCHAR)
    })
    List<BUserCard> selectByExample(BUserCardExample example);
    
    
    @Select({
        "select",
        "*",
        "from B_USER_CARD",
        "where PURCHASERID = #{purchaserid,jdbcType=VARCHAR}",
          "and MERCHANTID = #{merchantid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="MERCHANTID", property="merchantid", jdbcType=JdbcType.VARCHAR),
        @Result(column="PURCHASERID", property="purchaserid", jdbcType=JdbcType.VARCHAR),
        @Result(column="CARDID", property="cardid", jdbcType=JdbcType.VARCHAR),
        @Result(column="VALID", property="valid", jdbcType=JdbcType.CHAR),
        @Result(column="CREATETIME", property="createtime", jdbcType=JdbcType.VARCHAR),
        @Result(column="BANKNAME", property="bankname", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPENPROVINCE", property="openprovince", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPENCITY", property="opencity", jdbcType=JdbcType.VARCHAR),
        @Result(column="OPENNAME", property="openname", jdbcType=JdbcType.VARCHAR)
    })
    List<BUserCard> selectByMerandPur(BUserCard usercard);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_CARD
     *
     * @mbggenerated Thu Mar 24 14:15:40 CST 2016
     */
    @UpdateProvider(type=BUserCardSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BUserCard record, @Param("example") BUserCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_USER_CARD
     *
     * @mbggenerated Thu Mar 24 14:15:40 CST 2016
     */
    @UpdateProvider(type=BUserCardSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BUserCard record, @Param("example") BUserCardExample example);
}