package cn.msec.cbpay.mapper;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;

import cn.msec.cbpay.entity.RouteType;
import cn.msec.cbpay.entity.RouteTypeKey;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;

public interface RouteTypeMapper extends StaticTableDaoSupport<RouteType,RouteType , RouteTypeKey> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUT_TYPE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Delete({
        "delete from ROUT_TYPE",
        "where MERCHANTID = #{merchantid,jdbcType=VARCHAR}",
        "and ROUTETYPE = #{routetype,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(RouteTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUT_TYPE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Insert({
        "insert into ROUT_TYPE (MERCHANTID, ROUTETYPE, ",
        "ROUTEFIELD, VALID)",
        "values (#{merchantid,jdbcType=VARCHAR}, #{routetype,jdbcType=VARCHAR}, ",
        "#{routefield,jdbcType=VARCHAR}, #{valid,jdbcType=VARCHAR})"
    })
    int insert(RouteType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUT_TYPE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @InsertProvider(type=RouteTypeSqlProvider.class, method="insertSelective")
    int insertSelective(RouteType record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUT_TYPE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @UpdateProvider(type=RouteTypeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RouteType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROUT_TYPE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Update({
        "update ROUT_TYPE",
        "set MERCHANTID = #{merchantid,jdbcType=VARCHAR},",
          "ROUTETYPE = #{routetype,jdbcType=VARCHAR},",
          "ROUTEFIELD = #{routefield,jdbcType=VARCHAR},",
          "VALID = #{valid,jdbcType=VARCHAR}",
        "where MERCHANTID = #{merchantid,jdbcType=VARCHAR}",
        "and ROUTETYPE = #{routetype,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(RouteType record);
}