package cn.msec.cbpay.mapper;

import java.util.List;

import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import cn.msec.cbpay.entity.SystemDict;
import cn.msec.cbpay.entity.SystemDictExample;
import cn.msec.ojpa.msc.mysql.StaticTableDaoSupport;

public interface SystemDictMapper extends StaticTableDaoSupport<SystemDict, SystemDictExample, SystemDict> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_DICT
     *
     * @mbggenerated Fri May 20 10:32:40 CST 2016
     */
    @SelectProvider(type=SystemDictSqlProvider.class, method="countByExample")
    int countByExample(SystemDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_DICT
     *
     * @mbggenerated Fri May 20 10:32:40 CST 2016
     */
    @DeleteProvider(type=SystemDictSqlProvider.class, method="deleteByExample")
    int deleteByExample(SystemDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_DICT
     *
     * @mbggenerated Fri May 20 10:32:40 CST 2016
     */
    @Insert({
        "insert into SYSTEM_DICT (KEY, NAME, ",
        "desc, TYPE)",
        "values (#{key,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{desc,jdbcType=VARCHAR}, #{type,jdbcType=VARCHAR})"
    })
    int insert(SystemDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_DICT
     *
     * @mbggenerated Fri May 20 10:32:40 CST 2016
     */
    @InsertProvider(type=SystemDictSqlProvider.class, method="insertSelective")
    int insertSelective(SystemDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_DICT
     *
     * @mbggenerated Fri May 20 10:32:40 CST 2016
     */
    @SelectProvider(type=SystemDictSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="KEY", property="key", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="desc", property="desc", jdbcType=JdbcType.VARCHAR),
        @Result(column="TYPE", property="type", jdbcType=JdbcType.VARCHAR)
    })
    List<SystemDict> selectByExample(SystemDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_DICT
     *
     * @mbggenerated Fri May 20 10:32:40 CST 2016
     */
    @UpdateProvider(type=SystemDictSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") SystemDict record, @Param("example") SystemDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM_DICT
     *
     * @mbggenerated Fri May 20 10:32:40 CST 2016
     */
    @UpdateProvider(type=SystemDictSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") SystemDict record, @Param("example") SystemDictExample example);
}