package cn.msec.cbpay.entity;

import cn.msec.ojpa.api.annotations.Tab;
import cn.msec.ojpa.msc.mysql.CustomDateSerializer;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="APP_ADDRESS")
@AllArgsConstructor
@NoArgsConstructor
public class AppAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_ADDRESS.APPID
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_ADDRESS.TYPE
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_ADDRESS.URL
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_ADDRESS.APPSTATUS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    private String appstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_ADDRESS.APPID
     *
     * @return the value of APP_ADDRESS.APPID
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_ADDRESS.APPID
     *
     * @param appid the value for APP_ADDRESS.APPID
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_ADDRESS.TYPE
     *
     * @return the value of APP_ADDRESS.TYPE
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_ADDRESS.TYPE
     *
     * @param type the value for APP_ADDRESS.TYPE
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_ADDRESS.URL
     *
     * @return the value of APP_ADDRESS.URL
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_ADDRESS.URL
     *
     * @param url the value for APP_ADDRESS.URL
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_ADDRESS.APPSTATUS
     *
     * @return the value of APP_ADDRESS.APPSTATUS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    public String getAppstatus() {
        return appstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_ADDRESS.APPSTATUS
     *
     * @param appstatus the value for APP_ADDRESS.APPSTATUS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    public void setAppstatus(String appstatus) {
        this.appstatus = appstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_ADDRESS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AppAddress other = (AppAddress) that;
        return (this.getAppid() == null ? other.getAppid() == null : this.getAppid().equals(other.getAppid()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getAppstatus() == null ? other.getAppstatus() == null : this.getAppstatus().equals(other.getAppstatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_ADDRESS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAppid() == null) ? 0 : getAppid().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getAppstatus() == null) ? 0 : getAppstatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_ADDRESS
     *
     * @mbggenerated Wed Apr 13 10:44:14 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", appid=").append(appid);
        sb.append(", type=").append(type);
        sb.append(", url=").append(url);
        sb.append(", appstatus=").append(appstatus);
        sb.append("]");
        return sb.toString();
    }
}