package cn.msec.cbpay.entity;



import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data
public class BBuyExgCtrlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    protected List<Criteria> oredCriteria;

    protected int offset;

    protected int limit;

    protected String sumCol;

    protected String groupSelClause;

    protected String groupByClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    public BBuyExgCtrlExample() {
        oredCriteria = new ArrayList<Criteria>();
        offset = 0;
        limit = Integer.MAX_VALUE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        this.offset= 0;
        this.limit= Integer.MAX_VALUE;
        this.sumCol=null;
        this.groupSelClause=null;
        this.groupByClause=null;
    }

    public void setOffset(int offset) {
         this.offset = offset;
    }

    public int getOffset() {
          return offset;
    }

    public void setLimit(int limit) {
         this.limit = limit;
    }

    public int getLimit() {
          return limit;
    }

    public void setSumCol(String sumCol) {
         this.sumCol = sumCol;
    }

    public String getSumCol() {
          return sumCol;
    }

    public void setGroupSelClause(String groupSelClause) {
         this.groupSelClause = groupSelClause;
    }

    public String getGroupSelClause() {
          return groupSelClause;
    }

    public void setGroupByClause(String groupByClause) {
         this.groupByClause = groupByClause;
    }

    public String getGroupByClause() {
          return groupByClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    @Data
    public abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        public GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBuybatnoIsNull() {
            addCriterion("BUYBATNO is null");
            return (Criteria) this;
        }

        public Criteria andBuybatnoIsNotNull() {
            addCriterion("BUYBATNO is not null");
            return (Criteria) this;
        }

        public Criteria andBuybatnoEqualTo(String value) {
            addCriterion("BUYBATNO =", value, "buybatno");
            return (Criteria) this;
        }

        public Criteria andBuybatnoNotEqualTo(String value) {
            addCriterion("BUYBATNO <>", value, "buybatno");
            return (Criteria) this;
        }

        public Criteria andBuybatnoGreaterThan(String value) {
            addCriterion("BUYBATNO >", value, "buybatno");
            return (Criteria) this;
        }

        public Criteria andBuybatnoGreaterThanOrEqualTo(String value) {
            addCriterion("BUYBATNO >=", value, "buybatno");
            return (Criteria) this;
        }

        public Criteria andBuybatnoLessThan(String value) {
            addCriterion("BUYBATNO <", value, "buybatno");
            return (Criteria) this;
        }

        public Criteria andBuybatnoLessThanOrEqualTo(String value) {
            addCriterion("BUYBATNO <=", value, "buybatno");
            return (Criteria) this;
        }

        public Criteria andBuybatnoLike(String value) {
            addCriterion("BUYBATNO like", value, "buybatno");
            return (Criteria) this;
        }

        public Criteria andBuybatnoNotLike(String value) {
            addCriterion("BUYBATNO not like", value, "buybatno");
            return (Criteria) this;
        }

        public Criteria andBuybatnoIn(List<String> values) {
            addCriterion("BUYBATNO in", values, "buybatno");
            return (Criteria) this;
        }

        public Criteria andBuybatnoNotIn(List<String> values) {
            addCriterion("BUYBATNO not in", values, "buybatno");
            return (Criteria) this;
        }

        public Criteria andBuybatnoBetween(String value1, String value2) {
            addCriterion("BUYBATNO between", value1, value2, "buybatno");
            return (Criteria) this;
        }

        public Criteria andBuybatnoNotBetween(String value1, String value2) {
            addCriterion("BUYBATNO not between", value1, value2, "buybatno");
            return (Criteria) this;
        }

        public Criteria andBuydateIsNull() {
            addCriterion("BUYDATE is null");
            return (Criteria) this;
        }

        public Criteria andBuydateIsNotNull() {
            addCriterion("BUYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andBuydateEqualTo(String value) {
            addCriterion("BUYDATE =", value, "buydate");
            return (Criteria) this;
        }

        public Criteria andBuydateNotEqualTo(String value) {
            addCriterion("BUYDATE <>", value, "buydate");
            return (Criteria) this;
        }

        public Criteria andBuydateGreaterThan(String value) {
            addCriterion("BUYDATE >", value, "buydate");
            return (Criteria) this;
        }

        public Criteria andBuydateGreaterThanOrEqualTo(String value) {
            addCriterion("BUYDATE >=", value, "buydate");
            return (Criteria) this;
        }

        public Criteria andBuydateLessThan(String value) {
            addCriterion("BUYDATE <", value, "buydate");
            return (Criteria) this;
        }

        public Criteria andBuydateLessThanOrEqualTo(String value) {
            addCriterion("BUYDATE <=", value, "buydate");
            return (Criteria) this;
        }

        public Criteria andBuydateLike(String value) {
            addCriterion("BUYDATE like", value, "buydate");
            return (Criteria) this;
        }

        public Criteria andBuydateNotLike(String value) {
            addCriterion("BUYDATE not like", value, "buydate");
            return (Criteria) this;
        }

        public Criteria andBuydateIn(List<String> values) {
            addCriterion("BUYDATE in", values, "buydate");
            return (Criteria) this;
        }

        public Criteria andBuydateNotIn(List<String> values) {
            addCriterion("BUYDATE not in", values, "buydate");
            return (Criteria) this;
        }

        public Criteria andBuydateBetween(String value1, String value2) {
            addCriterion("BUYDATE between", value1, value2, "buydate");
            return (Criteria) this;
        }

        public Criteria andBuydateNotBetween(String value1, String value2) {
            addCriterion("BUYDATE not between", value1, value2, "buydate");
            return (Criteria) this;
        }

        public Criteria andBuytimeIsNull() {
            addCriterion("BUYTIME is null");
            return (Criteria) this;
        }

        public Criteria andBuytimeIsNotNull() {
            addCriterion("BUYTIME is not null");
            return (Criteria) this;
        }

        public Criteria andBuytimeEqualTo(String value) {
            addCriterion("BUYTIME =", value, "buytime");
            return (Criteria) this;
        }

        public Criteria andBuytimeNotEqualTo(String value) {
            addCriterion("BUYTIME <>", value, "buytime");
            return (Criteria) this;
        }

        public Criteria andBuytimeGreaterThan(String value) {
            addCriterion("BUYTIME >", value, "buytime");
            return (Criteria) this;
        }

        public Criteria andBuytimeGreaterThanOrEqualTo(String value) {
            addCriterion("BUYTIME >=", value, "buytime");
            return (Criteria) this;
        }

        public Criteria andBuytimeLessThan(String value) {
            addCriterion("BUYTIME <", value, "buytime");
            return (Criteria) this;
        }

        public Criteria andBuytimeLessThanOrEqualTo(String value) {
            addCriterion("BUYTIME <=", value, "buytime");
            return (Criteria) this;
        }

        public Criteria andBuytimeLike(String value) {
            addCriterion("BUYTIME like", value, "buytime");
            return (Criteria) this;
        }

        public Criteria andBuytimeNotLike(String value) {
            addCriterion("BUYTIME not like", value, "buytime");
            return (Criteria) this;
        }

        public Criteria andBuytimeIn(List<String> values) {
            addCriterion("BUYTIME in", values, "buytime");
            return (Criteria) this;
        }

        public Criteria andBuytimeNotIn(List<String> values) {
            addCriterion("BUYTIME not in", values, "buytime");
            return (Criteria) this;
        }

        public Criteria andBuytimeBetween(String value1, String value2) {
            addCriterion("BUYTIME between", value1, value2, "buytime");
            return (Criteria) this;
        }

        public Criteria andBuytimeNotBetween(String value1, String value2) {
            addCriterion("BUYTIME not between", value1, value2, "buytime");
            return (Criteria) this;
        }

        public Criteria andQuotechnlIsNull() {
            addCriterion("QUOTECHNL is null");
            return (Criteria) this;
        }

        public Criteria andQuotechnlIsNotNull() {
            addCriterion("QUOTECHNL is not null");
            return (Criteria) this;
        }

        public Criteria andQuotechnlEqualTo(String value) {
            addCriterion("QUOTECHNL =", value, "quotechnl");
            return (Criteria) this;
        }

        public Criteria andQuotechnlNotEqualTo(String value) {
            addCriterion("QUOTECHNL <>", value, "quotechnl");
            return (Criteria) this;
        }

        public Criteria andQuotechnlGreaterThan(String value) {
            addCriterion("QUOTECHNL >", value, "quotechnl");
            return (Criteria) this;
        }

        public Criteria andQuotechnlGreaterThanOrEqualTo(String value) {
            addCriterion("QUOTECHNL >=", value, "quotechnl");
            return (Criteria) this;
        }

        public Criteria andQuotechnlLessThan(String value) {
            addCriterion("QUOTECHNL <", value, "quotechnl");
            return (Criteria) this;
        }

        public Criteria andQuotechnlLessThanOrEqualTo(String value) {
            addCriterion("QUOTECHNL <=", value, "quotechnl");
            return (Criteria) this;
        }

        public Criteria andQuotechnlLike(String value) {
            addCriterion("QUOTECHNL like", value, "quotechnl");
            return (Criteria) this;
        }

        public Criteria andQuotechnlNotLike(String value) {
            addCriterion("QUOTECHNL not like", value, "quotechnl");
            return (Criteria) this;
        }

        public Criteria andQuotechnlIn(List<String> values) {
            addCriterion("QUOTECHNL in", values, "quotechnl");
            return (Criteria) this;
        }

        public Criteria andQuotechnlNotIn(List<String> values) {
            addCriterion("QUOTECHNL not in", values, "quotechnl");
            return (Criteria) this;
        }

        public Criteria andQuotechnlBetween(String value1, String value2) {
            addCriterion("QUOTECHNL between", value1, value2, "quotechnl");
            return (Criteria) this;
        }

        public Criteria andQuotechnlNotBetween(String value1, String value2) {
            addCriterion("QUOTECHNL not between", value1, value2, "quotechnl");
            return (Criteria) this;
        }

        public Criteria andBecifIsNull() {
            addCriterion("BECIF is null");
            return (Criteria) this;
        }

        public Criteria andBecifIsNotNull() {
            addCriterion("BECIF is not null");
            return (Criteria) this;
        }

        public Criteria andBecifEqualTo(String value) {
            addCriterion("BECIF =", value, "becif");
            return (Criteria) this;
        }

        public Criteria andBecifNotEqualTo(String value) {
            addCriterion("BECIF <>", value, "becif");
            return (Criteria) this;
        }

        public Criteria andBecifGreaterThan(String value) {
            addCriterion("BECIF >", value, "becif");
            return (Criteria) this;
        }

        public Criteria andBecifGreaterThanOrEqualTo(String value) {
            addCriterion("BECIF >=", value, "becif");
            return (Criteria) this;
        }

        public Criteria andBecifLessThan(String value) {
            addCriterion("BECIF <", value, "becif");
            return (Criteria) this;
        }

        public Criteria andBecifLessThanOrEqualTo(String value) {
            addCriterion("BECIF <=", value, "becif");
            return (Criteria) this;
        }

        public Criteria andBecifLike(String value) {
            addCriterion("BECIF like", value, "becif");
            return (Criteria) this;
        }

        public Criteria andBecifNotLike(String value) {
            addCriterion("BECIF not like", value, "becif");
            return (Criteria) this;
        }

        public Criteria andBecifIn(List<String> values) {
            addCriterion("BECIF in", values, "becif");
            return (Criteria) this;
        }

        public Criteria andBecifNotIn(List<String> values) {
            addCriterion("BECIF not in", values, "becif");
            return (Criteria) this;
        }

        public Criteria andBecifBetween(String value1, String value2) {
            addCriterion("BECIF between", value1, value2, "becif");
            return (Criteria) this;
        }

        public Criteria andBecifNotBetween(String value1, String value2) {
            addCriterion("BECIF not between", value1, value2, "becif");
            return (Criteria) this;
        }

        public Criteria andTotNumIsNull() {
            addCriterion("TOT_NUM is null");
            return (Criteria) this;
        }

        public Criteria andTotNumIsNotNull() {
            addCriterion("TOT_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andTotNumEqualTo(Short value) {
            addCriterion("TOT_NUM =", value, "totNum");
            return (Criteria) this;
        }

        public Criteria andTotNumNotEqualTo(Short value) {
            addCriterion("TOT_NUM <>", value, "totNum");
            return (Criteria) this;
        }

        public Criteria andTotNumGreaterThan(Short value) {
            addCriterion("TOT_NUM >", value, "totNum");
            return (Criteria) this;
        }

        public Criteria andTotNumGreaterThanOrEqualTo(Short value) {
            addCriterion("TOT_NUM >=", value, "totNum");
            return (Criteria) this;
        }

        public Criteria andTotNumLessThan(Short value) {
            addCriterion("TOT_NUM <", value, "totNum");
            return (Criteria) this;
        }

        public Criteria andTotNumLessThanOrEqualTo(Short value) {
            addCriterion("TOT_NUM <=", value, "totNum");
            return (Criteria) this;
        }

        public Criteria andTotNumIn(List<Short> values) {
            addCriterion("TOT_NUM in", values, "totNum");
            return (Criteria) this;
        }

        public Criteria andTotNumNotIn(List<Short> values) {
            addCriterion("TOT_NUM not in", values, "totNum");
            return (Criteria) this;
        }

        public Criteria andTotNumBetween(Short value1, Short value2) {
            addCriterion("TOT_NUM between", value1, value2, "totNum");
            return (Criteria) this;
        }

        public Criteria andTotNumNotBetween(Short value1, Short value2) {
            addCriterion("TOT_NUM not between", value1, value2, "totNum");
            return (Criteria) this;
        }

        public Criteria andSaleCcyIsNull() {
            addCriterion("SALE_CCY is null");
            return (Criteria) this;
        }

        public Criteria andSaleCcyIsNotNull() {
            addCriterion("SALE_CCY is not null");
            return (Criteria) this;
        }

        public Criteria andSaleCcyEqualTo(String value) {
            addCriterion("SALE_CCY =", value, "saleCcy");
            return (Criteria) this;
        }

        public Criteria andSaleCcyNotEqualTo(String value) {
            addCriterion("SALE_CCY <>", value, "saleCcy");
            return (Criteria) this;
        }

        public Criteria andSaleCcyGreaterThan(String value) {
            addCriterion("SALE_CCY >", value, "saleCcy");
            return (Criteria) this;
        }

        public Criteria andSaleCcyGreaterThanOrEqualTo(String value) {
            addCriterion("SALE_CCY >=", value, "saleCcy");
            return (Criteria) this;
        }

        public Criteria andSaleCcyLessThan(String value) {
            addCriterion("SALE_CCY <", value, "saleCcy");
            return (Criteria) this;
        }

        public Criteria andSaleCcyLessThanOrEqualTo(String value) {
            addCriterion("SALE_CCY <=", value, "saleCcy");
            return (Criteria) this;
        }

        public Criteria andSaleCcyLike(String value) {
            addCriterion("SALE_CCY like", value, "saleCcy");
            return (Criteria) this;
        }

        public Criteria andSaleCcyNotLike(String value) {
            addCriterion("SALE_CCY not like", value, "saleCcy");
            return (Criteria) this;
        }

        public Criteria andSaleCcyIn(List<String> values) {
            addCriterion("SALE_CCY in", values, "saleCcy");
            return (Criteria) this;
        }

        public Criteria andSaleCcyNotIn(List<String> values) {
            addCriterion("SALE_CCY not in", values, "saleCcy");
            return (Criteria) this;
        }

        public Criteria andSaleCcyBetween(String value1, String value2) {
            addCriterion("SALE_CCY between", value1, value2, "saleCcy");
            return (Criteria) this;
        }

        public Criteria andSaleCcyNotBetween(String value1, String value2) {
            addCriterion("SALE_CCY not between", value1, value2, "saleCcy");
            return (Criteria) this;
        }

        public Criteria andBuyCcyIsNull() {
            addCriterion("BUY_CCY is null");
            return (Criteria) this;
        }

        public Criteria andBuyCcyIsNotNull() {
            addCriterion("BUY_CCY is not null");
            return (Criteria) this;
        }

        public Criteria andBuyCcyEqualTo(String value) {
            addCriterion("BUY_CCY =", value, "buyCcy");
            return (Criteria) this;
        }

        public Criteria andBuyCcyNotEqualTo(String value) {
            addCriterion("BUY_CCY <>", value, "buyCcy");
            return (Criteria) this;
        }

        public Criteria andBuyCcyGreaterThan(String value) {
            addCriterion("BUY_CCY >", value, "buyCcy");
            return (Criteria) this;
        }

        public Criteria andBuyCcyGreaterThanOrEqualTo(String value) {
            addCriterion("BUY_CCY >=", value, "buyCcy");
            return (Criteria) this;
        }

        public Criteria andBuyCcyLessThan(String value) {
            addCriterion("BUY_CCY <", value, "buyCcy");
            return (Criteria) this;
        }

        public Criteria andBuyCcyLessThanOrEqualTo(String value) {
            addCriterion("BUY_CCY <=", value, "buyCcy");
            return (Criteria) this;
        }

        public Criteria andBuyCcyLike(String value) {
            addCriterion("BUY_CCY like", value, "buyCcy");
            return (Criteria) this;
        }

        public Criteria andBuyCcyNotLike(String value) {
            addCriterion("BUY_CCY not like", value, "buyCcy");
            return (Criteria) this;
        }

        public Criteria andBuyCcyIn(List<String> values) {
            addCriterion("BUY_CCY in", values, "buyCcy");
            return (Criteria) this;
        }

        public Criteria andBuyCcyNotIn(List<String> values) {
            addCriterion("BUY_CCY not in", values, "buyCcy");
            return (Criteria) this;
        }

        public Criteria andBuyCcyBetween(String value1, String value2) {
            addCriterion("BUY_CCY between", value1, value2, "buyCcy");
            return (Criteria) this;
        }

        public Criteria andBuyCcyNotBetween(String value1, String value2) {
            addCriterion("BUY_CCY not between", value1, value2, "buyCcy");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagIsNull() {
            addCriterion("BUY_SELL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagIsNotNull() {
            addCriterion("BUY_SELL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagEqualTo(String value) {
            addCriterion("BUY_SELL_FLAG =", value, "buySellFlag");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagNotEqualTo(String value) {
            addCriterion("BUY_SELL_FLAG <>", value, "buySellFlag");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagGreaterThan(String value) {
            addCriterion("BUY_SELL_FLAG >", value, "buySellFlag");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagGreaterThanOrEqualTo(String value) {
            addCriterion("BUY_SELL_FLAG >=", value, "buySellFlag");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagLessThan(String value) {
            addCriterion("BUY_SELL_FLAG <", value, "buySellFlag");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagLessThanOrEqualTo(String value) {
            addCriterion("BUY_SELL_FLAG <=", value, "buySellFlag");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagLike(String value) {
            addCriterion("BUY_SELL_FLAG like", value, "buySellFlag");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagNotLike(String value) {
            addCriterion("BUY_SELL_FLAG not like", value, "buySellFlag");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagIn(List<String> values) {
            addCriterion("BUY_SELL_FLAG in", values, "buySellFlag");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagNotIn(List<String> values) {
            addCriterion("BUY_SELL_FLAG not in", values, "buySellFlag");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagBetween(String value1, String value2) {
            addCriterion("BUY_SELL_FLAG between", value1, value2, "buySellFlag");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagNotBetween(String value1, String value2) {
            addCriterion("BUY_SELL_FLAG not between", value1, value2, "buySellFlag");
            return (Criteria) this;
        }

        public Criteria andTotalAmtIsNull() {
            addCriterion("TOTAL_AMT is null");
            return (Criteria) this;
        }

        public Criteria andTotalAmtIsNotNull() {
            addCriterion("TOTAL_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAmtEqualTo(BigDecimal value) {
            addCriterion("TOTAL_AMT =", value, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtNotEqualTo(BigDecimal value) {
            addCriterion("TOTAL_AMT <>", value, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtGreaterThan(BigDecimal value) {
            addCriterion("TOTAL_AMT >", value, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTAL_AMT >=", value, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtLessThan(BigDecimal value) {
            addCriterion("TOTAL_AMT <", value, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TOTAL_AMT <=", value, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtIn(List<BigDecimal> values) {
            addCriterion("TOTAL_AMT in", values, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtNotIn(List<BigDecimal> values) {
            addCriterion("TOTAL_AMT not in", values, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTAL_AMT between", value1, value2, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TOTAL_AMT not between", value1, value2, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andSpotFlagIsNull() {
            addCriterion("SPOT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andSpotFlagIsNotNull() {
            addCriterion("SPOT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSpotFlagEqualTo(String value) {
            addCriterion("SPOT_FLAG =", value, "spotFlag");
            return (Criteria) this;
        }

        public Criteria andSpotFlagNotEqualTo(String value) {
            addCriterion("SPOT_FLAG <>", value, "spotFlag");
            return (Criteria) this;
        }

        public Criteria andSpotFlagGreaterThan(String value) {
            addCriterion("SPOT_FLAG >", value, "spotFlag");
            return (Criteria) this;
        }

        public Criteria andSpotFlagGreaterThanOrEqualTo(String value) {
            addCriterion("SPOT_FLAG >=", value, "spotFlag");
            return (Criteria) this;
        }

        public Criteria andSpotFlagLessThan(String value) {
            addCriterion("SPOT_FLAG <", value, "spotFlag");
            return (Criteria) this;
        }

        public Criteria andSpotFlagLessThanOrEqualTo(String value) {
            addCriterion("SPOT_FLAG <=", value, "spotFlag");
            return (Criteria) this;
        }

        public Criteria andSpotFlagLike(String value) {
            addCriterion("SPOT_FLAG like", value, "spotFlag");
            return (Criteria) this;
        }

        public Criteria andSpotFlagNotLike(String value) {
            addCriterion("SPOT_FLAG not like", value, "spotFlag");
            return (Criteria) this;
        }

        public Criteria andSpotFlagIn(List<String> values) {
            addCriterion("SPOT_FLAG in", values, "spotFlag");
            return (Criteria) this;
        }

        public Criteria andSpotFlagNotIn(List<String> values) {
            addCriterion("SPOT_FLAG not in", values, "spotFlag");
            return (Criteria) this;
        }

        public Criteria andSpotFlagBetween(String value1, String value2) {
            addCriterion("SPOT_FLAG between", value1, value2, "spotFlag");
            return (Criteria) this;
        }

        public Criteria andSpotFlagNotBetween(String value1, String value2) {
            addCriterion("SPOT_FLAG not between", value1, value2, "spotFlag");
            return (Criteria) this;
        }

        public Criteria andRegisterDateIsNull() {
            addCriterion("REGISTER_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRegisterDateIsNotNull() {
            addCriterion("REGISTER_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterDateEqualTo(String value) {
            addCriterion("REGISTER_DATE =", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateNotEqualTo(String value) {
            addCriterion("REGISTER_DATE <>", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateGreaterThan(String value) {
            addCriterion("REGISTER_DATE >", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateGreaterThanOrEqualTo(String value) {
            addCriterion("REGISTER_DATE >=", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateLessThan(String value) {
            addCriterion("REGISTER_DATE <", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateLessThanOrEqualTo(String value) {
            addCriterion("REGISTER_DATE <=", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateLike(String value) {
            addCriterion("REGISTER_DATE like", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateNotLike(String value) {
            addCriterion("REGISTER_DATE not like", value, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateIn(List<String> values) {
            addCriterion("REGISTER_DATE in", values, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateNotIn(List<String> values) {
            addCriterion("REGISTER_DATE not in", values, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateBetween(String value1, String value2) {
            addCriterion("REGISTER_DATE between", value1, value2, "registerDate");
            return (Criteria) this;
        }

        public Criteria andRegisterDateNotBetween(String value1, String value2) {
            addCriterion("REGISTER_DATE not between", value1, value2, "registerDate");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("PRICE is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("PRICE =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("PRICE <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("PRICE >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PRICE >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("PRICE <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PRICE <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("PRICE in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("PRICE not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRICE between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRICE not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andClientExchangeRateIsNull() {
            addCriterion("CLIENT_EXCHANGE_RATE is null");
            return (Criteria) this;
        }

        public Criteria andClientExchangeRateIsNotNull() {
            addCriterion("CLIENT_EXCHANGE_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andClientExchangeRateEqualTo(BigDecimal value) {
            addCriterion("CLIENT_EXCHANGE_RATE =", value, "clientExchangeRate");
            return (Criteria) this;
        }

        public Criteria andClientExchangeRateNotEqualTo(BigDecimal value) {
            addCriterion("CLIENT_EXCHANGE_RATE <>", value, "clientExchangeRate");
            return (Criteria) this;
        }

        public Criteria andClientExchangeRateGreaterThan(BigDecimal value) {
            addCriterion("CLIENT_EXCHANGE_RATE >", value, "clientExchangeRate");
            return (Criteria) this;
        }

        public Criteria andClientExchangeRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CLIENT_EXCHANGE_RATE >=", value, "clientExchangeRate");
            return (Criteria) this;
        }

        public Criteria andClientExchangeRateLessThan(BigDecimal value) {
            addCriterion("CLIENT_EXCHANGE_RATE <", value, "clientExchangeRate");
            return (Criteria) this;
        }

        public Criteria andClientExchangeRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CLIENT_EXCHANGE_RATE <=", value, "clientExchangeRate");
            return (Criteria) this;
        }

        public Criteria andClientExchangeRateIn(List<BigDecimal> values) {
            addCriterion("CLIENT_EXCHANGE_RATE in", values, "clientExchangeRate");
            return (Criteria) this;
        }

        public Criteria andClientExchangeRateNotIn(List<BigDecimal> values) {
            addCriterion("CLIENT_EXCHANGE_RATE not in", values, "clientExchangeRate");
            return (Criteria) this;
        }

        public Criteria andClientExchangeRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CLIENT_EXCHANGE_RATE between", value1, value2, "clientExchangeRate");
            return (Criteria) this;
        }

        public Criteria andClientExchangeRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CLIENT_EXCHANGE_RATE not between", value1, value2, "clientExchangeRate");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeIsNull() {
            addCriterion("DISCOUNT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeIsNotNull() {
            addCriterion("DISCOUNT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeEqualTo(String value) {
            addCriterion("DISCOUNT_TYPE =", value, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeNotEqualTo(String value) {
            addCriterion("DISCOUNT_TYPE <>", value, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeGreaterThan(String value) {
            addCriterion("DISCOUNT_TYPE >", value, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DISCOUNT_TYPE >=", value, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeLessThan(String value) {
            addCriterion("DISCOUNT_TYPE <", value, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeLessThanOrEqualTo(String value) {
            addCriterion("DISCOUNT_TYPE <=", value, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeLike(String value) {
            addCriterion("DISCOUNT_TYPE like", value, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeNotLike(String value) {
            addCriterion("DISCOUNT_TYPE not like", value, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeIn(List<String> values) {
            addCriterion("DISCOUNT_TYPE in", values, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeNotIn(List<String> values) {
            addCriterion("DISCOUNT_TYPE not in", values, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeBetween(String value1, String value2) {
            addCriterion("DISCOUNT_TYPE between", value1, value2, "discountType");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeNotBetween(String value1, String value2) {
            addCriterion("DISCOUNT_TYPE not between", value1, value2, "discountType");
            return (Criteria) this;
        }

        public Criteria andDisAmtIsNull() {
            addCriterion("DIS_AMT is null");
            return (Criteria) this;
        }

        public Criteria andDisAmtIsNotNull() {
            addCriterion("DIS_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andDisAmtEqualTo(BigDecimal value) {
            addCriterion("DIS_AMT =", value, "disAmt");
            return (Criteria) this;
        }

        public Criteria andDisAmtNotEqualTo(BigDecimal value) {
            addCriterion("DIS_AMT <>", value, "disAmt");
            return (Criteria) this;
        }

        public Criteria andDisAmtGreaterThan(BigDecimal value) {
            addCriterion("DIS_AMT >", value, "disAmt");
            return (Criteria) this;
        }

        public Criteria andDisAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DIS_AMT >=", value, "disAmt");
            return (Criteria) this;
        }

        public Criteria andDisAmtLessThan(BigDecimal value) {
            addCriterion("DIS_AMT <", value, "disAmt");
            return (Criteria) this;
        }

        public Criteria andDisAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DIS_AMT <=", value, "disAmt");
            return (Criteria) this;
        }

        public Criteria andDisAmtIn(List<BigDecimal> values) {
            addCriterion("DIS_AMT in", values, "disAmt");
            return (Criteria) this;
        }

        public Criteria andDisAmtNotIn(List<BigDecimal> values) {
            addCriterion("DIS_AMT not in", values, "disAmt");
            return (Criteria) this;
        }

        public Criteria andDisAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DIS_AMT between", value1, value2, "disAmt");
            return (Criteria) this;
        }

        public Criteria andDisAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DIS_AMT not between", value1, value2, "disAmt");
            return (Criteria) this;
        }

        public Criteria andAmtIsNull() {
            addCriterion("AMT is null");
            return (Criteria) this;
        }

        public Criteria andAmtIsNotNull() {
            addCriterion("AMT is not null");
            return (Criteria) this;
        }

        public Criteria andAmtEqualTo(BigDecimal value) {
            addCriterion("AMT =", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotEqualTo(BigDecimal value) {
            addCriterion("AMT <>", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThan(BigDecimal value) {
            addCriterion("AMT >", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AMT >=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThan(BigDecimal value) {
            addCriterion("AMT <", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AMT <=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtIn(List<BigDecimal> values) {
            addCriterion("AMT in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotIn(List<BigDecimal> values) {
            addCriterion("AMT not in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMT between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AMT not between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andTranAmtIsNull() {
            addCriterion("TRAN_AMT is null");
            return (Criteria) this;
        }

        public Criteria andTranAmtIsNotNull() {
            addCriterion("TRAN_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andTranAmtEqualTo(BigDecimal value) {
            addCriterion("TRAN_AMT =", value, "tranAmt");
            return (Criteria) this;
        }

        public Criteria andTranAmtNotEqualTo(BigDecimal value) {
            addCriterion("TRAN_AMT <>", value, "tranAmt");
            return (Criteria) this;
        }

        public Criteria andTranAmtGreaterThan(BigDecimal value) {
            addCriterion("TRAN_AMT >", value, "tranAmt");
            return (Criteria) this;
        }

        public Criteria andTranAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TRAN_AMT >=", value, "tranAmt");
            return (Criteria) this;
        }

        public Criteria andTranAmtLessThan(BigDecimal value) {
            addCriterion("TRAN_AMT <", value, "tranAmt");
            return (Criteria) this;
        }

        public Criteria andTranAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TRAN_AMT <=", value, "tranAmt");
            return (Criteria) this;
        }

        public Criteria andTranAmtIn(List<BigDecimal> values) {
            addCriterion("TRAN_AMT in", values, "tranAmt");
            return (Criteria) this;
        }

        public Criteria andTranAmtNotIn(List<BigDecimal> values) {
            addCriterion("TRAN_AMT not in", values, "tranAmt");
            return (Criteria) this;
        }

        public Criteria andTranAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRAN_AMT between", value1, value2, "tranAmt");
            return (Criteria) this;
        }

        public Criteria andTranAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TRAN_AMT not between", value1, value2, "tranAmt");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoIsNull() {
            addCriterion("SELL_ACCT_NO is null");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoIsNotNull() {
            addCriterion("SELL_ACCT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoEqualTo(String value) {
            addCriterion("SELL_ACCT_NO =", value, "sellAcctNo");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoNotEqualTo(String value) {
            addCriterion("SELL_ACCT_NO <>", value, "sellAcctNo");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoGreaterThan(String value) {
            addCriterion("SELL_ACCT_NO >", value, "sellAcctNo");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoGreaterThanOrEqualTo(String value) {
            addCriterion("SELL_ACCT_NO >=", value, "sellAcctNo");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoLessThan(String value) {
            addCriterion("SELL_ACCT_NO <", value, "sellAcctNo");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoLessThanOrEqualTo(String value) {
            addCriterion("SELL_ACCT_NO <=", value, "sellAcctNo");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoLike(String value) {
            addCriterion("SELL_ACCT_NO like", value, "sellAcctNo");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoNotLike(String value) {
            addCriterion("SELL_ACCT_NO not like", value, "sellAcctNo");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoIn(List<String> values) {
            addCriterion("SELL_ACCT_NO in", values, "sellAcctNo");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoNotIn(List<String> values) {
            addCriterion("SELL_ACCT_NO not in", values, "sellAcctNo");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoBetween(String value1, String value2) {
            addCriterion("SELL_ACCT_NO between", value1, value2, "sellAcctNo");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoNotBetween(String value1, String value2) {
            addCriterion("SELL_ACCT_NO not between", value1, value2, "sellAcctNo");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoIsNull() {
            addCriterion("BUY_ACCT_NO is null");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoIsNotNull() {
            addCriterion("BUY_ACCT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoEqualTo(String value) {
            addCriterion("BUY_ACCT_NO =", value, "buyAcctNo");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoNotEqualTo(String value) {
            addCriterion("BUY_ACCT_NO <>", value, "buyAcctNo");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoGreaterThan(String value) {
            addCriterion("BUY_ACCT_NO >", value, "buyAcctNo");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoGreaterThanOrEqualTo(String value) {
            addCriterion("BUY_ACCT_NO >=", value, "buyAcctNo");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoLessThan(String value) {
            addCriterion("BUY_ACCT_NO <", value, "buyAcctNo");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoLessThanOrEqualTo(String value) {
            addCriterion("BUY_ACCT_NO <=", value, "buyAcctNo");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoLike(String value) {
            addCriterion("BUY_ACCT_NO like", value, "buyAcctNo");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoNotLike(String value) {
            addCriterion("BUY_ACCT_NO not like", value, "buyAcctNo");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoIn(List<String> values) {
            addCriterion("BUY_ACCT_NO in", values, "buyAcctNo");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoNotIn(List<String> values) {
            addCriterion("BUY_ACCT_NO not in", values, "buyAcctNo");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoBetween(String value1, String value2) {
            addCriterion("BUY_ACCT_NO between", value1, value2, "buyAcctNo");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoNotBetween(String value1, String value2) {
            addCriterion("BUY_ACCT_NO not between", value1, value2, "buyAcctNo");
            return (Criteria) this;
        }

        public Criteria andSaleAmountIsNull() {
            addCriterion("SALE_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andSaleAmountIsNotNull() {
            addCriterion("SALE_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andSaleAmountEqualTo(BigDecimal value) {
            addCriterion("SALE_AMOUNT =", value, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountNotEqualTo(BigDecimal value) {
            addCriterion("SALE_AMOUNT <>", value, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountGreaterThan(BigDecimal value) {
            addCriterion("SALE_AMOUNT >", value, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SALE_AMOUNT >=", value, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountLessThan(BigDecimal value) {
            addCriterion("SALE_AMOUNT <", value, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SALE_AMOUNT <=", value, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountIn(List<BigDecimal> values) {
            addCriterion("SALE_AMOUNT in", values, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountNotIn(List<BigDecimal> values) {
            addCriterion("SALE_AMOUNT not in", values, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SALE_AMOUNT between", value1, value2, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SALE_AMOUNT not between", value1, value2, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andBuyAmountIsNull() {
            addCriterion("BUY_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andBuyAmountIsNotNull() {
            addCriterion("BUY_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andBuyAmountEqualTo(BigDecimal value) {
            addCriterion("BUY_AMOUNT =", value, "buyAmount");
            return (Criteria) this;
        }

        public Criteria andBuyAmountNotEqualTo(BigDecimal value) {
            addCriterion("BUY_AMOUNT <>", value, "buyAmount");
            return (Criteria) this;
        }

        public Criteria andBuyAmountGreaterThan(BigDecimal value) {
            addCriterion("BUY_AMOUNT >", value, "buyAmount");
            return (Criteria) this;
        }

        public Criteria andBuyAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BUY_AMOUNT >=", value, "buyAmount");
            return (Criteria) this;
        }

        public Criteria andBuyAmountLessThan(BigDecimal value) {
            addCriterion("BUY_AMOUNT <", value, "buyAmount");
            return (Criteria) this;
        }

        public Criteria andBuyAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BUY_AMOUNT <=", value, "buyAmount");
            return (Criteria) this;
        }

        public Criteria andBuyAmountIn(List<BigDecimal> values) {
            addCriterion("BUY_AMOUNT in", values, "buyAmount");
            return (Criteria) this;
        }

        public Criteria andBuyAmountNotIn(List<BigDecimal> values) {
            addCriterion("BUY_AMOUNT not in", values, "buyAmount");
            return (Criteria) this;
        }

        public Criteria andBuyAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BUY_AMOUNT between", value1, value2, "buyAmount");
            return (Criteria) this;
        }

        public Criteria andBuyAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BUY_AMOUNT not between", value1, value2, "buyAmount");
            return (Criteria) this;
        }

        public Criteria andRateTimeIsNull() {
            addCriterion("RATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRateTimeIsNotNull() {
            addCriterion("RATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRateTimeEqualTo(String value) {
            addCriterion("RATE_TIME =", value, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeNotEqualTo(String value) {
            addCriterion("RATE_TIME <>", value, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeGreaterThan(String value) {
            addCriterion("RATE_TIME >", value, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("RATE_TIME >=", value, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeLessThan(String value) {
            addCriterion("RATE_TIME <", value, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeLessThanOrEqualTo(String value) {
            addCriterion("RATE_TIME <=", value, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeLike(String value) {
            addCriterion("RATE_TIME like", value, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeNotLike(String value) {
            addCriterion("RATE_TIME not like", value, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeIn(List<String> values) {
            addCriterion("RATE_TIME in", values, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeNotIn(List<String> values) {
            addCriterion("RATE_TIME not in", values, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeBetween(String value1, String value2) {
            addCriterion("RATE_TIME between", value1, value2, "rateTime");
            return (Criteria) this;
        }

        public Criteria andRateTimeNotBetween(String value1, String value2) {
            addCriterion("RATE_TIME not between", value1, value2, "rateTime");
            return (Criteria) this;
        }

        public Criteria andExceedFlagIsNull() {
            addCriterion("EXCEED_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andExceedFlagIsNotNull() {
            addCriterion("EXCEED_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andExceedFlagEqualTo(String value) {
            addCriterion("EXCEED_FLAG =", value, "exceedFlag");
            return (Criteria) this;
        }

        public Criteria andExceedFlagNotEqualTo(String value) {
            addCriterion("EXCEED_FLAG <>", value, "exceedFlag");
            return (Criteria) this;
        }

        public Criteria andExceedFlagGreaterThan(String value) {
            addCriterion("EXCEED_FLAG >", value, "exceedFlag");
            return (Criteria) this;
        }

        public Criteria andExceedFlagGreaterThanOrEqualTo(String value) {
            addCriterion("EXCEED_FLAG >=", value, "exceedFlag");
            return (Criteria) this;
        }

        public Criteria andExceedFlagLessThan(String value) {
            addCriterion("EXCEED_FLAG <", value, "exceedFlag");
            return (Criteria) this;
        }

        public Criteria andExceedFlagLessThanOrEqualTo(String value) {
            addCriterion("EXCEED_FLAG <=", value, "exceedFlag");
            return (Criteria) this;
        }

        public Criteria andExceedFlagLike(String value) {
            addCriterion("EXCEED_FLAG like", value, "exceedFlag");
            return (Criteria) this;
        }

        public Criteria andExceedFlagNotLike(String value) {
            addCriterion("EXCEED_FLAG not like", value, "exceedFlag");
            return (Criteria) this;
        }

        public Criteria andExceedFlagIn(List<String> values) {
            addCriterion("EXCEED_FLAG in", values, "exceedFlag");
            return (Criteria) this;
        }

        public Criteria andExceedFlagNotIn(List<String> values) {
            addCriterion("EXCEED_FLAG not in", values, "exceedFlag");
            return (Criteria) this;
        }

        public Criteria andExceedFlagBetween(String value1, String value2) {
            addCriterion("EXCEED_FLAG between", value1, value2, "exceedFlag");
            return (Criteria) this;
        }

        public Criteria andExceedFlagNotBetween(String value1, String value2) {
            addCriterion("EXCEED_FLAG not between", value1, value2, "exceedFlag");
            return (Criteria) this;
        }

        public Criteria andProcessStatusIsNull() {
            addCriterion("PROCESS_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andProcessStatusIsNotNull() {
            addCriterion("PROCESS_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andProcessStatusEqualTo(String value) {
            addCriterion("PROCESS_STATUS =", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusNotEqualTo(String value) {
            addCriterion("PROCESS_STATUS <>", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusGreaterThan(String value) {
            addCriterion("PROCESS_STATUS >", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusGreaterThanOrEqualTo(String value) {
            addCriterion("PROCESS_STATUS >=", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusLessThan(String value) {
            addCriterion("PROCESS_STATUS <", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusLessThanOrEqualTo(String value) {
            addCriterion("PROCESS_STATUS <=", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusLike(String value) {
            addCriterion("PROCESS_STATUS like", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusNotLike(String value) {
            addCriterion("PROCESS_STATUS not like", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusIn(List<String> values) {
            addCriterion("PROCESS_STATUS in", values, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusNotIn(List<String> values) {
            addCriterion("PROCESS_STATUS not in", values, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusBetween(String value1, String value2) {
            addCriterion("PROCESS_STATUS between", value1, value2, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusNotBetween(String value1, String value2) {
            addCriterion("PROCESS_STATUS not between", value1, value2, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessMsgIsNull() {
            addCriterion("PROCESS_MSG is null");
            return (Criteria) this;
        }

        public Criteria andProcessMsgIsNotNull() {
            addCriterion("PROCESS_MSG is not null");
            return (Criteria) this;
        }

        public Criteria andProcessMsgEqualTo(String value) {
            addCriterion("PROCESS_MSG =", value, "processMsg");
            return (Criteria) this;
        }

        public Criteria andProcessMsgNotEqualTo(String value) {
            addCriterion("PROCESS_MSG <>", value, "processMsg");
            return (Criteria) this;
        }

        public Criteria andProcessMsgGreaterThan(String value) {
            addCriterion("PROCESS_MSG >", value, "processMsg");
            return (Criteria) this;
        }

        public Criteria andProcessMsgGreaterThanOrEqualTo(String value) {
            addCriterion("PROCESS_MSG >=", value, "processMsg");
            return (Criteria) this;
        }

        public Criteria andProcessMsgLessThan(String value) {
            addCriterion("PROCESS_MSG <", value, "processMsg");
            return (Criteria) this;
        }

        public Criteria andProcessMsgLessThanOrEqualTo(String value) {
            addCriterion("PROCESS_MSG <=", value, "processMsg");
            return (Criteria) this;
        }

        public Criteria andProcessMsgLike(String value) {
            addCriterion("PROCESS_MSG like", value, "processMsg");
            return (Criteria) this;
        }

        public Criteria andProcessMsgNotLike(String value) {
            addCriterion("PROCESS_MSG not like", value, "processMsg");
            return (Criteria) this;
        }

        public Criteria andProcessMsgIn(List<String> values) {
            addCriterion("PROCESS_MSG in", values, "processMsg");
            return (Criteria) this;
        }

        public Criteria andProcessMsgNotIn(List<String> values) {
            addCriterion("PROCESS_MSG not in", values, "processMsg");
            return (Criteria) this;
        }

        public Criteria andProcessMsgBetween(String value1, String value2) {
            addCriterion("PROCESS_MSG between", value1, value2, "processMsg");
            return (Criteria) this;
        }

        public Criteria andProcessMsgNotBetween(String value1, String value2) {
            addCriterion("PROCESS_MSG not between", value1, value2, "processMsg");
            return (Criteria) this;
        }

        public Criteria andTxnStsIsNull() {
            addCriterion("TXN_STS is null");
            return (Criteria) this;
        }

        public Criteria andTxnStsIsNotNull() {
            addCriterion("TXN_STS is not null");
            return (Criteria) this;
        }

        public Criteria andTxnStsEqualTo(String value) {
            addCriterion("TXN_STS =", value, "txnSts");
            return (Criteria) this;
        }

        public Criteria andTxnStsNotEqualTo(String value) {
            addCriterion("TXN_STS <>", value, "txnSts");
            return (Criteria) this;
        }

        public Criteria andTxnStsGreaterThan(String value) {
            addCriterion("TXN_STS >", value, "txnSts");
            return (Criteria) this;
        }

        public Criteria andTxnStsGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_STS >=", value, "txnSts");
            return (Criteria) this;
        }

        public Criteria andTxnStsLessThan(String value) {
            addCriterion("TXN_STS <", value, "txnSts");
            return (Criteria) this;
        }

        public Criteria andTxnStsLessThanOrEqualTo(String value) {
            addCriterion("TXN_STS <=", value, "txnSts");
            return (Criteria) this;
        }

        public Criteria andTxnStsLike(String value) {
            addCriterion("TXN_STS like", value, "txnSts");
            return (Criteria) this;
        }

        public Criteria andTxnStsNotLike(String value) {
            addCriterion("TXN_STS not like", value, "txnSts");
            return (Criteria) this;
        }

        public Criteria andTxnStsIn(List<String> values) {
            addCriterion("TXN_STS in", values, "txnSts");
            return (Criteria) this;
        }

        public Criteria andTxnStsNotIn(List<String> values) {
            addCriterion("TXN_STS not in", values, "txnSts");
            return (Criteria) this;
        }

        public Criteria andTxnStsBetween(String value1, String value2) {
            addCriterion("TXN_STS between", value1, value2, "txnSts");
            return (Criteria) this;
        }

        public Criteria andTxnStsNotBetween(String value1, String value2) {
            addCriterion("TXN_STS not between", value1, value2, "txnSts");
            return (Criteria) this;
        }

        public Criteria andChkStsIsNull() {
            addCriterion("CHK_STS is null");
            return (Criteria) this;
        }

        public Criteria andChkStsIsNotNull() {
            addCriterion("CHK_STS is not null");
            return (Criteria) this;
        }

        public Criteria andChkStsEqualTo(String value) {
            addCriterion("CHK_STS =", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsNotEqualTo(String value) {
            addCriterion("CHK_STS <>", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsGreaterThan(String value) {
            addCriterion("CHK_STS >", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsGreaterThanOrEqualTo(String value) {
            addCriterion("CHK_STS >=", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsLessThan(String value) {
            addCriterion("CHK_STS <", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsLessThanOrEqualTo(String value) {
            addCriterion("CHK_STS <=", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsLike(String value) {
            addCriterion("CHK_STS like", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsNotLike(String value) {
            addCriterion("CHK_STS not like", value, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsIn(List<String> values) {
            addCriterion("CHK_STS in", values, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsNotIn(List<String> values) {
            addCriterion("CHK_STS not in", values, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsBetween(String value1, String value2) {
            addCriterion("CHK_STS between", value1, value2, "chkSts");
            return (Criteria) this;
        }

        public Criteria andChkStsNotBetween(String value1, String value2) {
            addCriterion("CHK_STS not between", value1, value2, "chkSts");
            return (Criteria) this;
        }

        public Criteria andBuybatnoLikeInsensitive(String value) {
            addCriterion("upper(BUYBATNO) like", value.toUpperCase(), "buybatno");
            return (Criteria) this;
        }

        public Criteria andBuydateLikeInsensitive(String value) {
            addCriterion("upper(BUYDATE) like", value.toUpperCase(), "buydate");
            return (Criteria) this;
        }

        public Criteria andBuytimeLikeInsensitive(String value) {
            addCriterion("upper(BUYTIME) like", value.toUpperCase(), "buytime");
            return (Criteria) this;
        }

        public Criteria andQuotechnlLikeInsensitive(String value) {
            addCriterion("upper(QUOTECHNL) like", value.toUpperCase(), "quotechnl");
            return (Criteria) this;
        }

        public Criteria andBecifLikeInsensitive(String value) {
            addCriterion("upper(BECIF) like", value.toUpperCase(), "becif");
            return (Criteria) this;
        }

        public Criteria andSaleCcyLikeInsensitive(String value) {
            addCriterion("upper(SALE_CCY) like", value.toUpperCase(), "saleCcy");
            return (Criteria) this;
        }

        public Criteria andBuyCcyLikeInsensitive(String value) {
            addCriterion("upper(BUY_CCY) like", value.toUpperCase(), "buyCcy");
            return (Criteria) this;
        }

        public Criteria andBuySellFlagLikeInsensitive(String value) {
            addCriterion("upper(BUY_SELL_FLAG) like", value.toUpperCase(), "buySellFlag");
            return (Criteria) this;
        }

        public Criteria andSpotFlagLikeInsensitive(String value) {
            addCriterion("upper(SPOT_FLAG) like", value.toUpperCase(), "spotFlag");
            return (Criteria) this;
        }

        public Criteria andRegisterDateLikeInsensitive(String value) {
            addCriterion("upper(REGISTER_DATE) like", value.toUpperCase(), "registerDate");
            return (Criteria) this;
        }

        public Criteria andDiscountTypeLikeInsensitive(String value) {
            addCriterion("upper(DISCOUNT_TYPE) like", value.toUpperCase(), "discountType");
            return (Criteria) this;
        }

        public Criteria andSellAcctNoLikeInsensitive(String value) {
            addCriterion("upper(SELL_ACCT_NO) like", value.toUpperCase(), "sellAcctNo");
            return (Criteria) this;
        }

        public Criteria andBuyAcctNoLikeInsensitive(String value) {
            addCriterion("upper(BUY_ACCT_NO) like", value.toUpperCase(), "buyAcctNo");
            return (Criteria) this;
        }

        public Criteria andRateTimeLikeInsensitive(String value) {
            addCriterion("upper(RATE_TIME) like", value.toUpperCase(), "rateTime");
            return (Criteria) this;
        }

        public Criteria andExceedFlagLikeInsensitive(String value) {
            addCriterion("upper(EXCEED_FLAG) like", value.toUpperCase(), "exceedFlag");
            return (Criteria) this;
        }

        public Criteria andProcessStatusLikeInsensitive(String value) {
            addCriterion("upper(PROCESS_STATUS) like", value.toUpperCase(), "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessMsgLikeInsensitive(String value) {
            addCriterion("upper(PROCESS_MSG) like", value.toUpperCase(), "processMsg");
            return (Criteria) this;
        }

        public Criteria andTxnStsLikeInsensitive(String value) {
            addCriterion("upper(TXN_STS) like", value.toUpperCase(), "txnSts");
            return (Criteria) this;
        }

        public Criteria andChkStsLikeInsensitive(String value) {
            addCriterion("upper(CHK_STS) like", value.toUpperCase(), "chkSts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated do_not_delete_during_merge Wed May 04 15:01:39 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        public Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table B_BUY_EXG_CTRL
     *
     * @mbggenerated Wed May 04 15:01:39 CST 2016
     */
    @Data
    @NoArgsConstructor
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        public Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        public Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        public Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        public Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}