package cn.msec.cbpay.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
public class BCheckStatusKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_CHECK_STATUS.TRANDATE
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    private String trandate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_CHECK_STATUS.CHECKTYPE
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    private String checktype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_CHECK_STATUS.TRANDATE
     *
     * @return the value of B_CHECK_STATUS.TRANDATE
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    public String getTrandate() {
        return trandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_CHECK_STATUS.TRANDATE
     *
     * @param trandate the value for B_CHECK_STATUS.TRANDATE
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    public void setTrandate(String trandate) {
        this.trandate = trandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_CHECK_STATUS.CHECKTYPE
     *
     * @return the value of B_CHECK_STATUS.CHECKTYPE
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    public String getChecktype() {
        return checktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_CHECK_STATUS.CHECKTYPE
     *
     * @param checktype the value for B_CHECK_STATUS.CHECKTYPE
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    public void setChecktype(String checktype) {
        this.checktype = checktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_CHECK_STATUS
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BCheckStatusKey other = (BCheckStatusKey) that;
        return (this.getTrandate() == null ? other.getTrandate() == null : this.getTrandate().equals(other.getTrandate()))
            && (this.getChecktype() == null ? other.getChecktype() == null : this.getChecktype().equals(other.getChecktype()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_CHECK_STATUS
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTrandate() == null) ? 0 : getTrandate().hashCode());
        result = prime * result + ((getChecktype() == null) ? 0 : getChecktype().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_CHECK_STATUS
     *
     * @mbggenerated Mon Jun 13 09:11:20 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", trandate=").append(trandate);
        sb.append(", checktype=").append(checktype);
        sb.append("]");
        return sb.toString();
    }
}