package cn.msec.cbpay.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
public class BFocusListKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOCUS_LIST.IDTYPE
     *
     * @mbggenerated Tue Mar 22 19:36:50 CST 2016
     */
    private String idtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOCUS_LIST.IDNO
     *
     * @mbggenerated Tue Mar 22 19:36:50 CST 2016
     */
    private String idno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOCUS_LIST.IDTYPE
     *
     * @return the value of B_FOCUS_LIST.IDTYPE
     *
     * @mbggenerated Tue Mar 22 19:36:50 CST 2016
     */
    public String getIdtype() {
        return idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOCUS_LIST.IDTYPE
     *
     * @param idtype the value for B_FOCUS_LIST.IDTYPE
     *
     * @mbggenerated Tue Mar 22 19:36:50 CST 2016
     */
    public void setIdtype(String idtype) {
        this.idtype = idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOCUS_LIST.IDNO
     *
     * @return the value of B_FOCUS_LIST.IDNO
     *
     * @mbggenerated Tue Mar 22 19:36:50 CST 2016
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOCUS_LIST.IDNO
     *
     * @param idno the value for B_FOCUS_LIST.IDNO
     *
     * @mbggenerated Tue Mar 22 19:36:50 CST 2016
     */
    public void setIdno(String idno) {
        this.idno = idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOCUS_LIST
     *
     * @mbggenerated Tue Mar 22 19:36:50 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BFocusListKey other = (BFocusListKey) that;
        return (this.getIdtype() == null ? other.getIdtype() == null : this.getIdtype().equals(other.getIdtype()))
            && (this.getIdno() == null ? other.getIdno() == null : this.getIdno().equals(other.getIdno()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOCUS_LIST
     *
     * @mbggenerated Tue Mar 22 19:36:50 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdtype() == null) ? 0 : getIdtype().hashCode());
        result = prime * result + ((getIdno() == null) ? 0 : getIdno().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOCUS_LIST
     *
     * @mbggenerated Tue Mar 22 19:36:50 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idtype=").append(idtype);
        sb.append(", idno=").append(idno);
        sb.append("]");
        return sb.toString();
    }
}