package cn.msec.cbpay.entity;

import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import cn.msec.ojpa.api.annotations.Tab;

@Tab(name="B_FOREIGN_CURRENCY_RATE")
@AllArgsConstructor
@NoArgsConstructor
public class BForeignCurrencyRate extends BForeignCurrencyRateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.TRANSTIME
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private String transtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.TRANSDATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private String transdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.CASHBUYPRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private BigDecimal cashbuyprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.EXBUYPRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private BigDecimal exbuyprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.CASHSELLPRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private BigDecimal cashsellprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.EXSELLPRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private BigDecimal exsellprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.EXQUOTEDATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private String exquotedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.EXQUOTETIME
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private String exquotetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.E3RDPAYNO
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private String e3rdpayno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.PRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.DIRECTION_FLAG
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private String directionFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.TRAN_AMT
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private BigDecimal tranAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.CLIENT_EXCHANGE_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private BigDecimal clientExchangeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.DISCOUNT_TYPE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private String discountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.DIS_AMT
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private BigDecimal disAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.AMT
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private BigDecimal amt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.TRANSTIME
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.TRANSTIME
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public String getTranstime() {
        return transtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.TRANSTIME
     *
     * @param transtime the value for B_FOREIGN_CURRENCY_RATE.TRANSTIME
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setTranstime(String transtime) {
        this.transtime = transtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.TRANSDATE
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.TRANSDATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public String getTransdate() {
        return transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.TRANSDATE
     *
     * @param transdate the value for B_FOREIGN_CURRENCY_RATE.TRANSDATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setTransdate(String transdate) {
        this.transdate = transdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.CASHBUYPRICE
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.CASHBUYPRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public BigDecimal getCashbuyprice() {
        return cashbuyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.CASHBUYPRICE
     *
     * @param cashbuyprice the value for B_FOREIGN_CURRENCY_RATE.CASHBUYPRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setCashbuyprice(BigDecimal cashbuyprice) {
        this.cashbuyprice = cashbuyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.EXBUYPRICE
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.EXBUYPRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public BigDecimal getExbuyprice() {
        return exbuyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.EXBUYPRICE
     *
     * @param exbuyprice the value for B_FOREIGN_CURRENCY_RATE.EXBUYPRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setExbuyprice(BigDecimal exbuyprice) {
        this.exbuyprice = exbuyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.CASHSELLPRICE
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.CASHSELLPRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public BigDecimal getCashsellprice() {
        return cashsellprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.CASHSELLPRICE
     *
     * @param cashsellprice the value for B_FOREIGN_CURRENCY_RATE.CASHSELLPRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setCashsellprice(BigDecimal cashsellprice) {
        this.cashsellprice = cashsellprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.EXSELLPRICE
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.EXSELLPRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public BigDecimal getExsellprice() {
        return exsellprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.EXSELLPRICE
     *
     * @param exsellprice the value for B_FOREIGN_CURRENCY_RATE.EXSELLPRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setExsellprice(BigDecimal exsellprice) {
        this.exsellprice = exsellprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.EXQUOTEDATE
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.EXQUOTEDATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public String getExquotedate() {
        return exquotedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.EXQUOTEDATE
     *
     * @param exquotedate the value for B_FOREIGN_CURRENCY_RATE.EXQUOTEDATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setExquotedate(String exquotedate) {
        this.exquotedate = exquotedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.EXQUOTETIME
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.EXQUOTETIME
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public String getExquotetime() {
        return exquotetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.EXQUOTETIME
     *
     * @param exquotetime the value for B_FOREIGN_CURRENCY_RATE.EXQUOTETIME
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setExquotetime(String exquotetime) {
        this.exquotetime = exquotetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.E3RDPAYNO
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.E3RDPAYNO
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public String getE3rdpayno() {
        return e3rdpayno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.E3RDPAYNO
     *
     * @param e3rdpayno the value for B_FOREIGN_CURRENCY_RATE.E3RDPAYNO
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setE3rdpayno(String e3rdpayno) {
        this.e3rdpayno = e3rdpayno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.PRICE
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.PRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.PRICE
     *
     * @param price the value for B_FOREIGN_CURRENCY_RATE.PRICE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.DIRECTION_FLAG
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.DIRECTION_FLAG
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public String getDirectionFlag() {
        return directionFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.DIRECTION_FLAG
     *
     * @param directionFlag the value for B_FOREIGN_CURRENCY_RATE.DIRECTION_FLAG
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setDirectionFlag(String directionFlag) {
        this.directionFlag = directionFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.TRAN_AMT
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.TRAN_AMT
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public BigDecimal getTranAmt() {
        return tranAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.TRAN_AMT
     *
     * @param tranAmt the value for B_FOREIGN_CURRENCY_RATE.TRAN_AMT
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setTranAmt(BigDecimal tranAmt) {
        this.tranAmt = tranAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.CLIENT_EXCHANGE_RATE
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.CLIENT_EXCHANGE_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public BigDecimal getClientExchangeRate() {
        return clientExchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.CLIENT_EXCHANGE_RATE
     *
     * @param clientExchangeRate the value for B_FOREIGN_CURRENCY_RATE.CLIENT_EXCHANGE_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setClientExchangeRate(BigDecimal clientExchangeRate) {
        this.clientExchangeRate = clientExchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.DISCOUNT_TYPE
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.DISCOUNT_TYPE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public String getDiscountType() {
        return discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.DISCOUNT_TYPE
     *
     * @param discountType the value for B_FOREIGN_CURRENCY_RATE.DISCOUNT_TYPE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setDiscountType(String discountType) {
        this.discountType = discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.DIS_AMT
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.DIS_AMT
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public BigDecimal getDisAmt() {
        return disAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.DIS_AMT
     *
     * @param disAmt the value for B_FOREIGN_CURRENCY_RATE.DIS_AMT
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setDisAmt(BigDecimal disAmt) {
        this.disAmt = disAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.AMT
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.AMT
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public BigDecimal getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.AMT
     *
     * @param amt the value for B_FOREIGN_CURRENCY_RATE.AMT
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:58 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BForeignCurrencyRate other = (BForeignCurrencyRate) that;
        return (this.getFromId() == null ? other.getFromId() == null : this.getFromId().equals(other.getFromId()))
            && (this.getRecvDate() == null ? other.getRecvDate() == null : this.getRecvDate().equals(other.getRecvDate()))
            && (this.getRecvTime() == null ? other.getRecvTime() == null : this.getRecvTime().equals(other.getRecvTime()))
            && (this.getCurrencyCode() == null ? other.getCurrencyCode() == null : this.getCurrencyCode().equals(other.getCurrencyCode()))
            && (this.getTranstime() == null ? other.getTranstime() == null : this.getTranstime().equals(other.getTranstime()))
            && (this.getTransdate() == null ? other.getTransdate() == null : this.getTransdate().equals(other.getTransdate()))
            && (this.getCashbuyprice() == null ? other.getCashbuyprice() == null : this.getCashbuyprice().equals(other.getCashbuyprice()))
            && (this.getExbuyprice() == null ? other.getExbuyprice() == null : this.getExbuyprice().equals(other.getExbuyprice()))
            && (this.getCashsellprice() == null ? other.getCashsellprice() == null : this.getCashsellprice().equals(other.getCashsellprice()))
            && (this.getExsellprice() == null ? other.getExsellprice() == null : this.getExsellprice().equals(other.getExsellprice()))
            && (this.getExquotedate() == null ? other.getExquotedate() == null : this.getExquotedate().equals(other.getExquotedate()))
            && (this.getExquotetime() == null ? other.getExquotetime() == null : this.getExquotetime().equals(other.getExquotetime()))
            && (this.getE3rdpayno() == null ? other.getE3rdpayno() == null : this.getE3rdpayno().equals(other.getE3rdpayno()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getDirectionFlag() == null ? other.getDirectionFlag() == null : this.getDirectionFlag().equals(other.getDirectionFlag()))
            && (this.getTranAmt() == null ? other.getTranAmt() == null : this.getTranAmt().equals(other.getTranAmt()))
            && (this.getClientExchangeRate() == null ? other.getClientExchangeRate() == null : this.getClientExchangeRate().equals(other.getClientExchangeRate()))
            && (this.getDiscountType() == null ? other.getDiscountType() == null : this.getDiscountType().equals(other.getDiscountType()))
            && (this.getDisAmt() == null ? other.getDisAmt() == null : this.getDisAmt().equals(other.getDisAmt()))
            && (this.getAmt() == null ? other.getAmt() == null : this.getAmt().equals(other.getAmt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:58 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFromId() == null) ? 0 : getFromId().hashCode());
        result = prime * result + ((getRecvDate() == null) ? 0 : getRecvDate().hashCode());
        result = prime * result + ((getRecvTime() == null) ? 0 : getRecvTime().hashCode());
        result = prime * result + ((getCurrencyCode() == null) ? 0 : getCurrencyCode().hashCode());
        result = prime * result + ((getTranstime() == null) ? 0 : getTranstime().hashCode());
        result = prime * result + ((getTransdate() == null) ? 0 : getTransdate().hashCode());
        result = prime * result + ((getCashbuyprice() == null) ? 0 : getCashbuyprice().hashCode());
        result = prime * result + ((getExbuyprice() == null) ? 0 : getExbuyprice().hashCode());
        result = prime * result + ((getCashsellprice() == null) ? 0 : getCashsellprice().hashCode());
        result = prime * result + ((getExsellprice() == null) ? 0 : getExsellprice().hashCode());
        result = prime * result + ((getExquotedate() == null) ? 0 : getExquotedate().hashCode());
        result = prime * result + ((getExquotetime() == null) ? 0 : getExquotetime().hashCode());
        result = prime * result + ((getE3rdpayno() == null) ? 0 : getE3rdpayno().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getDirectionFlag() == null) ? 0 : getDirectionFlag().hashCode());
        result = prime * result + ((getTranAmt() == null) ? 0 : getTranAmt().hashCode());
        result = prime * result + ((getClientExchangeRate() == null) ? 0 : getClientExchangeRate().hashCode());
        result = prime * result + ((getDiscountType() == null) ? 0 : getDiscountType().hashCode());
        result = prime * result + ((getDisAmt() == null) ? 0 : getDisAmt().hashCode());
        result = prime * result + ((getAmt() == null) ? 0 : getAmt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:58 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", transtime=").append(transtime);
        sb.append(", transdate=").append(transdate);
        sb.append(", cashbuyprice=").append(cashbuyprice);
        sb.append(", exbuyprice=").append(exbuyprice);
        sb.append(", cashsellprice=").append(cashsellprice);
        sb.append(", exsellprice=").append(exsellprice);
        sb.append(", exquotedate=").append(exquotedate);
        sb.append(", exquotetime=").append(exquotetime);
        sb.append(", e3rdpayno=").append(e3rdpayno);
        sb.append(", price=").append(price);
        sb.append(", directionFlag=").append(directionFlag);
        sb.append(", tranAmt=").append(tranAmt);
        sb.append(", clientExchangeRate=").append(clientExchangeRate);
        sb.append(", discountType=").append(discountType);
        sb.append(", disAmt=").append(disAmt);
        sb.append(", amt=").append(amt);
        sb.append("]");
        return sb.toString();
    }
}