package cn.msec.cbpay.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
public class BForeignCurrencyRateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.FROM_ID
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private String fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.RECV_DATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private String recvDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.RECV_TIME
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private String recvTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_FOREIGN_CURRENCY_RATE.CURRENCY_CODE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    private String currencyCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.FROM_ID
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.FROM_ID
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public String getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.FROM_ID
     *
     * @param fromId the value for B_FOREIGN_CURRENCY_RATE.FROM_ID
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setFromId(String fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.RECV_DATE
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.RECV_DATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public String getRecvDate() {
        return recvDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.RECV_DATE
     *
     * @param recvDate the value for B_FOREIGN_CURRENCY_RATE.RECV_DATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setRecvDate(String recvDate) {
        this.recvDate = recvDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.RECV_TIME
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.RECV_TIME
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public String getRecvTime() {
        return recvTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.RECV_TIME
     *
     * @param recvTime the value for B_FOREIGN_CURRENCY_RATE.RECV_TIME
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setRecvTime(String recvTime) {
        this.recvTime = recvTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_FOREIGN_CURRENCY_RATE.CURRENCY_CODE
     *
     * @return the value of B_FOREIGN_CURRENCY_RATE.CURRENCY_CODE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_FOREIGN_CURRENCY_RATE.CURRENCY_CODE
     *
     * @param currencyCode the value for B_FOREIGN_CURRENCY_RATE.CURRENCY_CODE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BForeignCurrencyRateKey other = (BForeignCurrencyRateKey) that;
        return (this.getFromId() == null ? other.getFromId() == null : this.getFromId().equals(other.getFromId()))
            && (this.getRecvDate() == null ? other.getRecvDate() == null : this.getRecvDate().equals(other.getRecvDate()))
            && (this.getRecvTime() == null ? other.getRecvTime() == null : this.getRecvTime().equals(other.getRecvTime()))
            && (this.getCurrencyCode() == null ? other.getCurrencyCode() == null : this.getCurrencyCode().equals(other.getCurrencyCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFromId() == null) ? 0 : getFromId().hashCode());
        result = prime * result + ((getRecvDate() == null) ? 0 : getRecvDate().hashCode());
        result = prime * result + ((getRecvTime() == null) ? 0 : getRecvTime().hashCode());
        result = prime * result + ((getCurrencyCode() == null) ? 0 : getCurrencyCode().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_FOREIGN_CURRENCY_RATE
     *
     * @mbggenerated Tue Mar 22 09:19:57 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fromId=").append(fromId);
        sb.append(", recvDate=").append(recvDate);
        sb.append(", recvTime=").append(recvTime);
        sb.append(", currencyCode=").append(currencyCode);
        sb.append("]");
        return sb.toString();
    }
}