package cn.msec.cbpay.entity;

import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import cn.msec.ojpa.api.annotations.Tab;

@Tab(name="B_MERCHANT_INFO")
@AllArgsConstructor
@NoArgsConstructor
public class BMerchantInfo extends BMerchantInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.MERCHANTNAME
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String merchantname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.MERCHANTDESC
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String merchantdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.ISENCRYPT
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String isencrypt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.ENCRYPT_ALGORITHM
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String encryptAlgorithm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.ISSIGNATURE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String issignature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.SIGNATURE_ALGORITHM
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String signatureAlgorithm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.PUBLIC_KEY_FILE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String publicKeyFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.KEY_FILE_TYPE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String keyFileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.ENCRYPT_TYPE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String encryptType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.SIGNATURE_TYPE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String signatureType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.KEY_STORE_FILE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String keyStoreFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.KEY_STORE_ALIAS
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String keyStoreAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.KEY_STORE_PASSWORD
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String keyStorePassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.COUNTRY_CODE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.CURRENCY_TYPE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String currencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.MERPLATACCTALIAS
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String merplatacctalias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.PROTOCOLNO
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String protocolno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.VALID
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.POUNDAGEFLAG
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String poundageflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.POUNDAGERATE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private BigDecimal poundagerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.CONTRACT_NO
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String contractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.MERCHANT_PRINCIPAL
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String merchantPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_INFO.PRINCIPAL_TEL
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    private String principalTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.MERCHANTNAME
     *
     * @return the value of B_MERCHANT_INFO.MERCHANTNAME
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getMerchantname() {
        return merchantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.MERCHANTNAME
     *
     * @param merchantname the value for B_MERCHANT_INFO.MERCHANTNAME
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setMerchantname(String merchantname) {
        this.merchantname = merchantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.MERCHANTDESC
     *
     * @return the value of B_MERCHANT_INFO.MERCHANTDESC
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getMerchantdesc() {
        return merchantdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.MERCHANTDESC
     *
     * @param merchantdesc the value for B_MERCHANT_INFO.MERCHANTDESC
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setMerchantdesc(String merchantdesc) {
        this.merchantdesc = merchantdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.ISENCRYPT
     *
     * @return the value of B_MERCHANT_INFO.ISENCRYPT
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getIsencrypt() {
        return isencrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.ISENCRYPT
     *
     * @param isencrypt the value for B_MERCHANT_INFO.ISENCRYPT
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setIsencrypt(String isencrypt) {
        this.isencrypt = isencrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.ENCRYPT_ALGORITHM
     *
     * @return the value of B_MERCHANT_INFO.ENCRYPT_ALGORITHM
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getEncryptAlgorithm() {
        return encryptAlgorithm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.ENCRYPT_ALGORITHM
     *
     * @param encryptAlgorithm the value for B_MERCHANT_INFO.ENCRYPT_ALGORITHM
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setEncryptAlgorithm(String encryptAlgorithm) {
        this.encryptAlgorithm = encryptAlgorithm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.ISSIGNATURE
     *
     * @return the value of B_MERCHANT_INFO.ISSIGNATURE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getIssignature() {
        return issignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.ISSIGNATURE
     *
     * @param issignature the value for B_MERCHANT_INFO.ISSIGNATURE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setIssignature(String issignature) {
        this.issignature = issignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.SIGNATURE_ALGORITHM
     *
     * @return the value of B_MERCHANT_INFO.SIGNATURE_ALGORITHM
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getSignatureAlgorithm() {
        return signatureAlgorithm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.SIGNATURE_ALGORITHM
     *
     * @param signatureAlgorithm the value for B_MERCHANT_INFO.SIGNATURE_ALGORITHM
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setSignatureAlgorithm(String signatureAlgorithm) {
        this.signatureAlgorithm = signatureAlgorithm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.PUBLIC_KEY_FILE
     *
     * @return the value of B_MERCHANT_INFO.PUBLIC_KEY_FILE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getPublicKeyFile() {
        return publicKeyFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.PUBLIC_KEY_FILE
     *
     * @param publicKeyFile the value for B_MERCHANT_INFO.PUBLIC_KEY_FILE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setPublicKeyFile(String publicKeyFile) {
        this.publicKeyFile = publicKeyFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.KEY_FILE_TYPE
     *
     * @return the value of B_MERCHANT_INFO.KEY_FILE_TYPE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getKeyFileType() {
        return keyFileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.KEY_FILE_TYPE
     *
     * @param keyFileType the value for B_MERCHANT_INFO.KEY_FILE_TYPE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setKeyFileType(String keyFileType) {
        this.keyFileType = keyFileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.ENCRYPT_TYPE
     *
     * @return the value of B_MERCHANT_INFO.ENCRYPT_TYPE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getEncryptType() {
        return encryptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.ENCRYPT_TYPE
     *
     * @param encryptType the value for B_MERCHANT_INFO.ENCRYPT_TYPE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setEncryptType(String encryptType) {
        this.encryptType = encryptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.SIGNATURE_TYPE
     *
     * @return the value of B_MERCHANT_INFO.SIGNATURE_TYPE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getSignatureType() {
        return signatureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.SIGNATURE_TYPE
     *
     * @param signatureType the value for B_MERCHANT_INFO.SIGNATURE_TYPE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setSignatureType(String signatureType) {
        this.signatureType = signatureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.KEY_STORE_FILE
     *
     * @return the value of B_MERCHANT_INFO.KEY_STORE_FILE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getKeyStoreFile() {
        return keyStoreFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.KEY_STORE_FILE
     *
     * @param keyStoreFile the value for B_MERCHANT_INFO.KEY_STORE_FILE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setKeyStoreFile(String keyStoreFile) {
        this.keyStoreFile = keyStoreFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.KEY_STORE_ALIAS
     *
     * @return the value of B_MERCHANT_INFO.KEY_STORE_ALIAS
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getKeyStoreAlias() {
        return keyStoreAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.KEY_STORE_ALIAS
     *
     * @param keyStoreAlias the value for B_MERCHANT_INFO.KEY_STORE_ALIAS
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setKeyStoreAlias(String keyStoreAlias) {
        this.keyStoreAlias = keyStoreAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.KEY_STORE_PASSWORD
     *
     * @return the value of B_MERCHANT_INFO.KEY_STORE_PASSWORD
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getKeyStorePassword() {
        return keyStorePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.KEY_STORE_PASSWORD
     *
     * @param keyStorePassword the value for B_MERCHANT_INFO.KEY_STORE_PASSWORD
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setKeyStorePassword(String keyStorePassword) {
        this.keyStorePassword = keyStorePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.COUNTRY_CODE
     *
     * @return the value of B_MERCHANT_INFO.COUNTRY_CODE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.COUNTRY_CODE
     *
     * @param countryCode the value for B_MERCHANT_INFO.COUNTRY_CODE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.CURRENCY_TYPE
     *
     * @return the value of B_MERCHANT_INFO.CURRENCY_TYPE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.CURRENCY_TYPE
     *
     * @param currencyType the value for B_MERCHANT_INFO.CURRENCY_TYPE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.MERPLATACCTALIAS
     *
     * @return the value of B_MERCHANT_INFO.MERPLATACCTALIAS
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getMerplatacctalias() {
        return merplatacctalias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.MERPLATACCTALIAS
     *
     * @param merplatacctalias the value for B_MERCHANT_INFO.MERPLATACCTALIAS
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setMerplatacctalias(String merplatacctalias) {
        this.merplatacctalias = merplatacctalias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.PROTOCOLNO
     *
     * @return the value of B_MERCHANT_INFO.PROTOCOLNO
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getProtocolno() {
        return protocolno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.PROTOCOLNO
     *
     * @param protocolno the value for B_MERCHANT_INFO.PROTOCOLNO
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setProtocolno(String protocolno) {
        this.protocolno = protocolno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.VALID
     *
     * @return the value of B_MERCHANT_INFO.VALID
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.VALID
     *
     * @param valid the value for B_MERCHANT_INFO.VALID
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setValid(String valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.POUNDAGEFLAG
     *
     * @return the value of B_MERCHANT_INFO.POUNDAGEFLAG
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getPoundageflag() {
        return poundageflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.POUNDAGEFLAG
     *
     * @param poundageflag the value for B_MERCHANT_INFO.POUNDAGEFLAG
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setPoundageflag(String poundageflag) {
        this.poundageflag = poundageflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.POUNDAGERATE
     *
     * @return the value of B_MERCHANT_INFO.POUNDAGERATE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public BigDecimal getPoundagerate() {
        return poundagerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.POUNDAGERATE
     *
     * @param poundagerate the value for B_MERCHANT_INFO.POUNDAGERATE
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setPoundagerate(BigDecimal poundagerate) {
        this.poundagerate = poundagerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.CONTRACT_NO
     *
     * @return the value of B_MERCHANT_INFO.CONTRACT_NO
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.CONTRACT_NO
     *
     * @param contractNo the value for B_MERCHANT_INFO.CONTRACT_NO
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.MERCHANT_PRINCIPAL
     *
     * @return the value of B_MERCHANT_INFO.MERCHANT_PRINCIPAL
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getMerchantPrincipal() {
        return merchantPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.MERCHANT_PRINCIPAL
     *
     * @param merchantPrincipal the value for B_MERCHANT_INFO.MERCHANT_PRINCIPAL
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setMerchantPrincipal(String merchantPrincipal) {
        this.merchantPrincipal = merchantPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_INFO.PRINCIPAL_TEL
     *
     * @return the value of B_MERCHANT_INFO.PRINCIPAL_TEL
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public String getPrincipalTel() {
        return principalTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_INFO.PRINCIPAL_TEL
     *
     * @param principalTel the value for B_MERCHANT_INFO.PRINCIPAL_TEL
     *
     * @mbggenerated Mon Mar 28 15:17:48 CST 2016
     */
    public void setPrincipalTel(String principalTel) {
        this.principalTel = principalTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_INFO
     *
     * @mbggenerated Mon Mar 28 15:17:49 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BMerchantInfo other = (BMerchantInfo) that;
        return (this.getMerchantid() == null ? other.getMerchantid() == null : this.getMerchantid().equals(other.getMerchantid()))
            && (this.getMerchantname() == null ? other.getMerchantname() == null : this.getMerchantname().equals(other.getMerchantname()))
            && (this.getMerchantdesc() == null ? other.getMerchantdesc() == null : this.getMerchantdesc().equals(other.getMerchantdesc()))
            && (this.getIsencrypt() == null ? other.getIsencrypt() == null : this.getIsencrypt().equals(other.getIsencrypt()))
            && (this.getEncryptAlgorithm() == null ? other.getEncryptAlgorithm() == null : this.getEncryptAlgorithm().equals(other.getEncryptAlgorithm()))
            && (this.getIssignature() == null ? other.getIssignature() == null : this.getIssignature().equals(other.getIssignature()))
            && (this.getSignatureAlgorithm() == null ? other.getSignatureAlgorithm() == null : this.getSignatureAlgorithm().equals(other.getSignatureAlgorithm()))
            && (this.getPublicKeyFile() == null ? other.getPublicKeyFile() == null : this.getPublicKeyFile().equals(other.getPublicKeyFile()))
            && (this.getKeyFileType() == null ? other.getKeyFileType() == null : this.getKeyFileType().equals(other.getKeyFileType()))
            && (this.getEncryptType() == null ? other.getEncryptType() == null : this.getEncryptType().equals(other.getEncryptType()))
            && (this.getSignatureType() == null ? other.getSignatureType() == null : this.getSignatureType().equals(other.getSignatureType()))
            && (this.getKeyStoreFile() == null ? other.getKeyStoreFile() == null : this.getKeyStoreFile().equals(other.getKeyStoreFile()))
            && (this.getKeyStoreAlias() == null ? other.getKeyStoreAlias() == null : this.getKeyStoreAlias().equals(other.getKeyStoreAlias()))
            && (this.getKeyStorePassword() == null ? other.getKeyStorePassword() == null : this.getKeyStorePassword().equals(other.getKeyStorePassword()))
            && (this.getCountryCode() == null ? other.getCountryCode() == null : this.getCountryCode().equals(other.getCountryCode()))
            && (this.getCurrencyType() == null ? other.getCurrencyType() == null : this.getCurrencyType().equals(other.getCurrencyType()))
            && (this.getMerplatacctalias() == null ? other.getMerplatacctalias() == null : this.getMerplatacctalias().equals(other.getMerplatacctalias()))
            && (this.getProtocolno() == null ? other.getProtocolno() == null : this.getProtocolno().equals(other.getProtocolno()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()))
            && (this.getPoundageflag() == null ? other.getPoundageflag() == null : this.getPoundageflag().equals(other.getPoundageflag()))
            && (this.getPoundagerate() == null ? other.getPoundagerate() == null : this.getPoundagerate().equals(other.getPoundagerate()))
            && (this.getContractNo() == null ? other.getContractNo() == null : this.getContractNo().equals(other.getContractNo()))
            && (this.getMerchantPrincipal() == null ? other.getMerchantPrincipal() == null : this.getMerchantPrincipal().equals(other.getMerchantPrincipal()))
            && (this.getPrincipalTel() == null ? other.getPrincipalTel() == null : this.getPrincipalTel().equals(other.getPrincipalTel()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_INFO
     *
     * @mbggenerated Mon Mar 28 15:17:49 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMerchantid() == null) ? 0 : getMerchantid().hashCode());
        result = prime * result + ((getMerchantname() == null) ? 0 : getMerchantname().hashCode());
        result = prime * result + ((getMerchantdesc() == null) ? 0 : getMerchantdesc().hashCode());
        result = prime * result + ((getIsencrypt() == null) ? 0 : getIsencrypt().hashCode());
        result = prime * result + ((getEncryptAlgorithm() == null) ? 0 : getEncryptAlgorithm().hashCode());
        result = prime * result + ((getIssignature() == null) ? 0 : getIssignature().hashCode());
        result = prime * result + ((getSignatureAlgorithm() == null) ? 0 : getSignatureAlgorithm().hashCode());
        result = prime * result + ((getPublicKeyFile() == null) ? 0 : getPublicKeyFile().hashCode());
        result = prime * result + ((getKeyFileType() == null) ? 0 : getKeyFileType().hashCode());
        result = prime * result + ((getEncryptType() == null) ? 0 : getEncryptType().hashCode());
        result = prime * result + ((getSignatureType() == null) ? 0 : getSignatureType().hashCode());
        result = prime * result + ((getKeyStoreFile() == null) ? 0 : getKeyStoreFile().hashCode());
        result = prime * result + ((getKeyStoreAlias() == null) ? 0 : getKeyStoreAlias().hashCode());
        result = prime * result + ((getKeyStorePassword() == null) ? 0 : getKeyStorePassword().hashCode());
        result = prime * result + ((getCountryCode() == null) ? 0 : getCountryCode().hashCode());
        result = prime * result + ((getCurrencyType() == null) ? 0 : getCurrencyType().hashCode());
        result = prime * result + ((getMerplatacctalias() == null) ? 0 : getMerplatacctalias().hashCode());
        result = prime * result + ((getProtocolno() == null) ? 0 : getProtocolno().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        result = prime * result + ((getPoundageflag() == null) ? 0 : getPoundageflag().hashCode());
        result = prime * result + ((getPoundagerate() == null) ? 0 : getPoundagerate().hashCode());
        result = prime * result + ((getContractNo() == null) ? 0 : getContractNo().hashCode());
        result = prime * result + ((getMerchantPrincipal() == null) ? 0 : getMerchantPrincipal().hashCode());
        result = prime * result + ((getPrincipalTel() == null) ? 0 : getPrincipalTel().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_INFO
     *
     * @mbggenerated Mon Mar 28 15:17:49 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", merchantname=").append(merchantname);
        sb.append(", merchantdesc=").append(merchantdesc);
        sb.append(", isencrypt=").append(isencrypt);
        sb.append(", encryptAlgorithm=").append(encryptAlgorithm);
        sb.append(", issignature=").append(issignature);
        sb.append(", signatureAlgorithm=").append(signatureAlgorithm);
        sb.append(", publicKeyFile=").append(publicKeyFile);
        sb.append(", keyFileType=").append(keyFileType);
        sb.append(", encryptType=").append(encryptType);
        sb.append(", signatureType=").append(signatureType);
        sb.append(", keyStoreFile=").append(keyStoreFile);
        sb.append(", keyStoreAlias=").append(keyStoreAlias);
        sb.append(", keyStorePassword=").append(keyStorePassword);
        sb.append(", countryCode=").append(countryCode);
        sb.append(", currencyType=").append(currencyType);
        sb.append(", merplatacctalias=").append(merplatacctalias);
        sb.append(", protocolno=").append(protocolno);
        sb.append(", valid=").append(valid);
        sb.append(", poundageflag=").append(poundageflag);
        sb.append(", poundagerate=").append(poundagerate);
        sb.append(", contractNo=").append(contractNo);
        sb.append(", merchantPrincipal=").append(merchantPrincipal);
        sb.append(", principalTel=").append(principalTel);
        sb.append("]");
        return sb.toString();
    }
}