package cn.msec.cbpay.entity;

import cn.msec.ojpa.api.annotations.Tab;
import cn.msec.ojpa.msc.mysql.CustomDateSerializer;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="B_MERCHANT_PERMISSION")
@AllArgsConstructor
@NoArgsConstructor
public class BMerchantPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_PERMISSION.MERCHANTID
     *
     * @mbggenerated Tue May 03 11:14:40 CST 2016
     */
    private String merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_PERMISSION.TRANCODE
     *
     * @mbggenerated Tue May 03 11:14:40 CST 2016
     */
    private String trancode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_PERMISSION.VALID
     *
     * @mbggenerated Tue May 03 11:14:40 CST 2016
     */
    private String valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_PERMISSION.MERCHANTID
     *
     * @return the value of B_MERCHANT_PERMISSION.MERCHANTID
     *
     * @mbggenerated Tue May 03 11:14:40 CST 2016
     */
    public String getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_PERMISSION.MERCHANTID
     *
     * @param merchantid the value for B_MERCHANT_PERMISSION.MERCHANTID
     *
     * @mbggenerated Tue May 03 11:14:40 CST 2016
     */
    public void setMerchantid(String merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_PERMISSION.TRANCODE
     *
     * @return the value of B_MERCHANT_PERMISSION.TRANCODE
     *
     * @mbggenerated Tue May 03 11:14:40 CST 2016
     */
    public String getTrancode() {
        return trancode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_PERMISSION.TRANCODE
     *
     * @param trancode the value for B_MERCHANT_PERMISSION.TRANCODE
     *
     * @mbggenerated Tue May 03 11:14:40 CST 2016
     */
    public void setTrancode(String trancode) {
        this.trancode = trancode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_PERMISSION.VALID
     *
     * @return the value of B_MERCHANT_PERMISSION.VALID
     *
     * @mbggenerated Tue May 03 11:14:40 CST 2016
     */
    public String getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_PERMISSION.VALID
     *
     * @param valid the value for B_MERCHANT_PERMISSION.VALID
     *
     * @mbggenerated Tue May 03 11:14:40 CST 2016
     */
    public void setValid(String valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_PERMISSION
     *
     * @mbggenerated Tue May 03 11:14:41 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BMerchantPermission other = (BMerchantPermission) that;
        return (this.getMerchantid() == null ? other.getMerchantid() == null : this.getMerchantid().equals(other.getMerchantid()))
            && (this.getTrancode() == null ? other.getTrancode() == null : this.getTrancode().equals(other.getTrancode()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_PERMISSION
     *
     * @mbggenerated Tue May 03 11:14:41 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMerchantid() == null) ? 0 : getMerchantid().hashCode());
        result = prime * result + ((getTrancode() == null) ? 0 : getTrancode().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_PERMISSION
     *
     * @mbggenerated Tue May 03 11:14:41 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", merchantid=").append(merchantid);
        sb.append(", trancode=").append(trancode);
        sb.append(", valid=").append(valid);
        sb.append("]");
        return sb.toString();
    }
}