package cn.msec.cbpay.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
public class BMerchantOrderKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.MERCHANTID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.ORDERID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.ORDERDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String orderdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.MERCHANTID
     *
     * @return the value of B_MERCHANT_ORDER.MERCHANTID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.MERCHANTID
     *
     * @param merchantid the value for B_MERCHANT_ORDER.MERCHANTID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setMerchantid(String merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.ORDERID
     *
     * @return the value of B_MERCHANT_ORDER.ORDERID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.ORDERID
     *
     * @param orderid the value for B_MERCHANT_ORDER.ORDERID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.ORDERDATE
     *
     * @return the value of B_MERCHANT_ORDER.ORDERDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.ORDERDATE
     *
     * @param orderdate the value for B_MERCHANT_ORDER.ORDERDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setOrderdate(String orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BMerchantOrderKey other = (BMerchantOrderKey) that;
        return (this.getMerchantid() == null ? other.getMerchantid() == null : this.getMerchantid().equals(other.getMerchantid()))
            && (this.getOrderid() == null ? other.getOrderid() == null : this.getOrderid().equals(other.getOrderid()))
            && (this.getOrderdate() == null ? other.getOrderdate() == null : this.getOrderdate().equals(other.getOrderdate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMerchantid() == null) ? 0 : getMerchantid().hashCode());
        result = prime * result + ((getOrderid() == null) ? 0 : getOrderid().hashCode());
        result = prime * result + ((getOrderdate() == null) ? 0 : getOrderdate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", merchantid=").append(merchantid);
        sb.append(", orderid=").append(orderid);
        sb.append(", orderdate=").append(orderdate);
        sb.append("]");
        return sb.toString();
    }
}