package cn.msec.cbpay.entity;



import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import cn.msec.ojpa.api.annotations.Tab;

@Tab(name="B_MERCHANT_ORDER")
@AllArgsConstructor
@NoArgsConstructor
public class BMerchantOrder extends BMerchantOrderKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.PAYJNLNO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String payjnlno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.PAYTIME
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.ORDERTIME
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.CLIENTIP
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String clientip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.PURCHASERID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String purchaserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.VALIDUNIT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String validunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.VALIDNUM
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String validnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.ORDERDESC
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String orderdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.ORDERAMOUNT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private BigDecimal orderamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.CURRENCY
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.MERCHANTPOUNDAGE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private BigDecimal merchantpoundage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.PURCHASEAMOUNT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private BigDecimal purchaseamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.CHANNEL
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.ACCEPTANCERATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private BigDecimal acceptancerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.ACCEPTANCEMOUNT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private BigDecimal acceptancemount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.ACCEPTANCYCURRENCY
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String acceptancycurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.ACCEPTANCYPOUNDAGE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private BigDecimal acceptancypoundage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.ORDERSTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String orderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.PAGERETURNURL
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String pagereturnurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.OFFLINENOTIFYURL
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String offlinenotifyurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.PAYORDERID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String payorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.BUYBATNO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String buybatno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.BUYBATSTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String buybatstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.BUYBATRATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private BigDecimal buybatrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.UPORDOWNMOUNT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private BigDecimal upordownmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.PAYBATNO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String paybatno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.PAYBATSTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String paybatstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.MOUNTCHANGENO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String mountchangeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.MOUNTCHANGESTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String mountchangestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.SETTLEBATNO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String settlebatno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.SETTLEBATSTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String settlebatstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.USERID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.TRADE_TYPE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.BUYBATDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String buybatdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.PAYCARD
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String paycard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.PAYDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String paydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.TRADE_CODE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String tradeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.IS_REF
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String isRef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.PAYBATDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String paybatdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.PRODUCTID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.PRODUCTNAME
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.PRODUCTDESC
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String productdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.SHOWURL
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String showurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.ISRESPONSE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String isresponse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.RCVTIME
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String rcvtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.RCVDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String rcvdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.TMSMP
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String tmsmp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_MERCHANT_ORDER.INVOICENO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    private String invoiceno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.PAYJNLNO
     *
     * @return the value of B_MERCHANT_ORDER.PAYJNLNO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getPayjnlno() {
        return payjnlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.PAYJNLNO
     *
     * @param payjnlno the value for B_MERCHANT_ORDER.PAYJNLNO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setPayjnlno(String payjnlno) {
        this.payjnlno = payjnlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.PAYTIME
     *
     * @return the value of B_MERCHANT_ORDER.PAYTIME
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.PAYTIME
     *
     * @param paytime the value for B_MERCHANT_ORDER.PAYTIME
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setPaytime(String paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.ORDERTIME
     *
     * @return the value of B_MERCHANT_ORDER.ORDERTIME
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.ORDERTIME
     *
     * @param ordertime the value for B_MERCHANT_ORDER.ORDERTIME
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setOrdertime(String ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.CLIENTIP
     *
     * @return the value of B_MERCHANT_ORDER.CLIENTIP
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getClientip() {
        return clientip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.CLIENTIP
     *
     * @param clientip the value for B_MERCHANT_ORDER.CLIENTIP
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setClientip(String clientip) {
        this.clientip = clientip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.PURCHASERID
     *
     * @return the value of B_MERCHANT_ORDER.PURCHASERID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getPurchaserid() {
        return purchaserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.PURCHASERID
     *
     * @param purchaserid the value for B_MERCHANT_ORDER.PURCHASERID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setPurchaserid(String purchaserid) {
        this.purchaserid = purchaserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.VALIDUNIT
     *
     * @return the value of B_MERCHANT_ORDER.VALIDUNIT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getValidunit() {
        return validunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.VALIDUNIT
     *
     * @param validunit the value for B_MERCHANT_ORDER.VALIDUNIT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setValidunit(String validunit) {
        this.validunit = validunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.VALIDNUM
     *
     * @return the value of B_MERCHANT_ORDER.VALIDNUM
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getValidnum() {
        return validnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.VALIDNUM
     *
     * @param validnum the value for B_MERCHANT_ORDER.VALIDNUM
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setValidnum(String validnum) {
        this.validnum = validnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.ORDERDESC
     *
     * @return the value of B_MERCHANT_ORDER.ORDERDESC
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getOrderdesc() {
        return orderdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.ORDERDESC
     *
     * @param orderdesc the value for B_MERCHANT_ORDER.ORDERDESC
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setOrderdesc(String orderdesc) {
        this.orderdesc = orderdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.ORDERAMOUNT
     *
     * @return the value of B_MERCHANT_ORDER.ORDERAMOUNT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public BigDecimal getOrderamount() {
        return orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.ORDERAMOUNT
     *
     * @param orderamount the value for B_MERCHANT_ORDER.ORDERAMOUNT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setOrderamount(BigDecimal orderamount) {
        this.orderamount = orderamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.CURRENCY
     *
     * @return the value of B_MERCHANT_ORDER.CURRENCY
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.CURRENCY
     *
     * @param currency the value for B_MERCHANT_ORDER.CURRENCY
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.MERCHANTPOUNDAGE
     *
     * @return the value of B_MERCHANT_ORDER.MERCHANTPOUNDAGE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public BigDecimal getMerchantpoundage() {
        return merchantpoundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.MERCHANTPOUNDAGE
     *
     * @param merchantpoundage the value for B_MERCHANT_ORDER.MERCHANTPOUNDAGE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setMerchantpoundage(BigDecimal merchantpoundage) {
        this.merchantpoundage = merchantpoundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.PURCHASEAMOUNT
     *
     * @return the value of B_MERCHANT_ORDER.PURCHASEAMOUNT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public BigDecimal getPurchaseamount() {
        return purchaseamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.PURCHASEAMOUNT
     *
     * @param purchaseamount the value for B_MERCHANT_ORDER.PURCHASEAMOUNT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setPurchaseamount(BigDecimal purchaseamount) {
        this.purchaseamount = purchaseamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.CHANNEL
     *
     * @return the value of B_MERCHANT_ORDER.CHANNEL
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.CHANNEL
     *
     * @param channel the value for B_MERCHANT_ORDER.CHANNEL
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.ACCEPTANCERATE
     *
     * @return the value of B_MERCHANT_ORDER.ACCEPTANCERATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public BigDecimal getAcceptancerate() {
        return acceptancerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.ACCEPTANCERATE
     *
     * @param acceptancerate the value for B_MERCHANT_ORDER.ACCEPTANCERATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setAcceptancerate(BigDecimal acceptancerate) {
        this.acceptancerate = acceptancerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.ACCEPTANCEMOUNT
     *
     * @return the value of B_MERCHANT_ORDER.ACCEPTANCEMOUNT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public BigDecimal getAcceptancemount() {
        return acceptancemount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.ACCEPTANCEMOUNT
     *
     * @param acceptancemount the value for B_MERCHANT_ORDER.ACCEPTANCEMOUNT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setAcceptancemount(BigDecimal acceptancemount) {
        this.acceptancemount = acceptancemount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.ACCEPTANCYCURRENCY
     *
     * @return the value of B_MERCHANT_ORDER.ACCEPTANCYCURRENCY
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getAcceptancycurrency() {
        return acceptancycurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.ACCEPTANCYCURRENCY
     *
     * @param acceptancycurrency the value for B_MERCHANT_ORDER.ACCEPTANCYCURRENCY
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setAcceptancycurrency(String acceptancycurrency) {
        this.acceptancycurrency = acceptancycurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.ACCEPTANCYPOUNDAGE
     *
     * @return the value of B_MERCHANT_ORDER.ACCEPTANCYPOUNDAGE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public BigDecimal getAcceptancypoundage() {
        return acceptancypoundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.ACCEPTANCYPOUNDAGE
     *
     * @param acceptancypoundage the value for B_MERCHANT_ORDER.ACCEPTANCYPOUNDAGE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setAcceptancypoundage(BigDecimal acceptancypoundage) {
        this.acceptancypoundage = acceptancypoundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.ORDERSTATUS
     *
     * @return the value of B_MERCHANT_ORDER.ORDERSTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.ORDERSTATUS
     *
     * @param orderstatus the value for B_MERCHANT_ORDER.ORDERSTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setOrderstatus(String orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.PAGERETURNURL
     *
     * @return the value of B_MERCHANT_ORDER.PAGERETURNURL
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getPagereturnurl() {
        return pagereturnurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.PAGERETURNURL
     *
     * @param pagereturnurl the value for B_MERCHANT_ORDER.PAGERETURNURL
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setPagereturnurl(String pagereturnurl) {
        this.pagereturnurl = pagereturnurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.OFFLINENOTIFYURL
     *
     * @return the value of B_MERCHANT_ORDER.OFFLINENOTIFYURL
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getOfflinenotifyurl() {
        return offlinenotifyurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.OFFLINENOTIFYURL
     *
     * @param offlinenotifyurl the value for B_MERCHANT_ORDER.OFFLINENOTIFYURL
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setOfflinenotifyurl(String offlinenotifyurl) {
        this.offlinenotifyurl = offlinenotifyurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.PAYORDERID
     *
     * @return the value of B_MERCHANT_ORDER.PAYORDERID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getPayorderid() {
        return payorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.PAYORDERID
     *
     * @param payorderid the value for B_MERCHANT_ORDER.PAYORDERID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setPayorderid(String payorderid) {
        this.payorderid = payorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.BUYBATNO
     *
     * @return the value of B_MERCHANT_ORDER.BUYBATNO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getBuybatno() {
        return buybatno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.BUYBATNO
     *
     * @param buybatno the value for B_MERCHANT_ORDER.BUYBATNO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setBuybatno(String buybatno) {
        this.buybatno = buybatno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.BUYBATSTATUS
     *
     * @return the value of B_MERCHANT_ORDER.BUYBATSTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getBuybatstatus() {
        return buybatstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.BUYBATSTATUS
     *
     * @param buybatstatus the value for B_MERCHANT_ORDER.BUYBATSTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setBuybatstatus(String buybatstatus) {
        this.buybatstatus = buybatstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.BUYBATRATE
     *
     * @return the value of B_MERCHANT_ORDER.BUYBATRATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public BigDecimal getBuybatrate() {
        return buybatrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.BUYBATRATE
     *
     * @param buybatrate the value for B_MERCHANT_ORDER.BUYBATRATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setBuybatrate(BigDecimal buybatrate) {
        this.buybatrate = buybatrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.UPORDOWNMOUNT
     *
     * @return the value of B_MERCHANT_ORDER.UPORDOWNMOUNT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public BigDecimal getUpordownmount() {
        return upordownmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.UPORDOWNMOUNT
     *
     * @param upordownmount the value for B_MERCHANT_ORDER.UPORDOWNMOUNT
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setUpordownmount(BigDecimal upordownmount) {
        this.upordownmount = upordownmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.PAYBATNO
     *
     * @return the value of B_MERCHANT_ORDER.PAYBATNO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getPaybatno() {
        return paybatno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.PAYBATNO
     *
     * @param paybatno the value for B_MERCHANT_ORDER.PAYBATNO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setPaybatno(String paybatno) {
        this.paybatno = paybatno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.PAYBATSTATUS
     *
     * @return the value of B_MERCHANT_ORDER.PAYBATSTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getPaybatstatus() {
        return paybatstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.PAYBATSTATUS
     *
     * @param paybatstatus the value for B_MERCHANT_ORDER.PAYBATSTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setPaybatstatus(String paybatstatus) {
        this.paybatstatus = paybatstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.MOUNTCHANGENO
     *
     * @return the value of B_MERCHANT_ORDER.MOUNTCHANGENO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getMountchangeno() {
        return mountchangeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.MOUNTCHANGENO
     *
     * @param mountchangeno the value for B_MERCHANT_ORDER.MOUNTCHANGENO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setMountchangeno(String mountchangeno) {
        this.mountchangeno = mountchangeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.MOUNTCHANGESTATUS
     *
     * @return the value of B_MERCHANT_ORDER.MOUNTCHANGESTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getMountchangestatus() {
        return mountchangestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.MOUNTCHANGESTATUS
     *
     * @param mountchangestatus the value for B_MERCHANT_ORDER.MOUNTCHANGESTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setMountchangestatus(String mountchangestatus) {
        this.mountchangestatus = mountchangestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.SETTLEBATNO
     *
     * @return the value of B_MERCHANT_ORDER.SETTLEBATNO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getSettlebatno() {
        return settlebatno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.SETTLEBATNO
     *
     * @param settlebatno the value for B_MERCHANT_ORDER.SETTLEBATNO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setSettlebatno(String settlebatno) {
        this.settlebatno = settlebatno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.SETTLEBATSTATUS
     *
     * @return the value of B_MERCHANT_ORDER.SETTLEBATSTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getSettlebatstatus() {
        return settlebatstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.SETTLEBATSTATUS
     *
     * @param settlebatstatus the value for B_MERCHANT_ORDER.SETTLEBATSTATUS
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setSettlebatstatus(String settlebatstatus) {
        this.settlebatstatus = settlebatstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.USERID
     *
     * @return the value of B_MERCHANT_ORDER.USERID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.USERID
     *
     * @param userid the value for B_MERCHANT_ORDER.USERID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.TRADE_TYPE
     *
     * @return the value of B_MERCHANT_ORDER.TRADE_TYPE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.TRADE_TYPE
     *
     * @param tradeType the value for B_MERCHANT_ORDER.TRADE_TYPE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.BUYBATDATE
     *
     * @return the value of B_MERCHANT_ORDER.BUYBATDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getBuybatdate() {
        return buybatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.BUYBATDATE
     *
     * @param buybatdate the value for B_MERCHANT_ORDER.BUYBATDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setBuybatdate(String buybatdate) {
        this.buybatdate = buybatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.PAYCARD
     *
     * @return the value of B_MERCHANT_ORDER.PAYCARD
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getPaycard() {
        return paycard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.PAYCARD
     *
     * @param paycard the value for B_MERCHANT_ORDER.PAYCARD
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setPaycard(String paycard) {
        this.paycard = paycard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.PAYDATE
     *
     * @return the value of B_MERCHANT_ORDER.PAYDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.PAYDATE
     *
     * @param paydate the value for B_MERCHANT_ORDER.PAYDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setPaydate(String paydate) {
        this.paydate = paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.TRADE_CODE
     *
     * @return the value of B_MERCHANT_ORDER.TRADE_CODE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getTradeCode() {
        return tradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.TRADE_CODE
     *
     * @param tradeCode the value for B_MERCHANT_ORDER.TRADE_CODE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setTradeCode(String tradeCode) {
        this.tradeCode = tradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.IS_REF
     *
     * @return the value of B_MERCHANT_ORDER.IS_REF
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getIsRef() {
        return isRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.IS_REF
     *
     * @param isRef the value for B_MERCHANT_ORDER.IS_REF
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setIsRef(String isRef) {
        this.isRef = isRef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.PAYBATDATE
     *
     * @return the value of B_MERCHANT_ORDER.PAYBATDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getPaybatdate() {
        return paybatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.PAYBATDATE
     *
     * @param paybatdate the value for B_MERCHANT_ORDER.PAYBATDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setPaybatdate(String paybatdate) {
        this.paybatdate = paybatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.PRODUCTID
     *
     * @return the value of B_MERCHANT_ORDER.PRODUCTID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.PRODUCTID
     *
     * @param productid the value for B_MERCHANT_ORDER.PRODUCTID
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setProductid(String productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.PRODUCTNAME
     *
     * @return the value of B_MERCHANT_ORDER.PRODUCTNAME
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.PRODUCTNAME
     *
     * @param productname the value for B_MERCHANT_ORDER.PRODUCTNAME
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setProductname(String productname) {
        this.productname = productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.PRODUCTDESC
     *
     * @return the value of B_MERCHANT_ORDER.PRODUCTDESC
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getProductdesc() {
        return productdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.PRODUCTDESC
     *
     * @param productdesc the value for B_MERCHANT_ORDER.PRODUCTDESC
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setProductdesc(String productdesc) {
        this.productdesc = productdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.SHOWURL
     *
     * @return the value of B_MERCHANT_ORDER.SHOWURL
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getShowurl() {
        return showurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.SHOWURL
     *
     * @param showurl the value for B_MERCHANT_ORDER.SHOWURL
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setShowurl(String showurl) {
        this.showurl = showurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.ISRESPONSE
     *
     * @return the value of B_MERCHANT_ORDER.ISRESPONSE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getIsresponse() {
        return isresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.ISRESPONSE
     *
     * @param isresponse the value for B_MERCHANT_ORDER.ISRESPONSE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setIsresponse(String isresponse) {
        this.isresponse = isresponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.RCVTIME
     *
     * @return the value of B_MERCHANT_ORDER.RCVTIME
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getRcvtime() {
        return rcvtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.RCVTIME
     *
     * @param rcvtime the value for B_MERCHANT_ORDER.RCVTIME
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setRcvtime(String rcvtime) {
        this.rcvtime = rcvtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.RCVDATE
     *
     * @return the value of B_MERCHANT_ORDER.RCVDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getRcvdate() {
        return rcvdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.RCVDATE
     *
     * @param rcvdate the value for B_MERCHANT_ORDER.RCVDATE
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setRcvdate(String rcvdate) {
        this.rcvdate = rcvdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.TMSMP
     *
     * @return the value of B_MERCHANT_ORDER.TMSMP
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getTmsmp() {
        return tmsmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.TMSMP
     *
     * @param tmsmp the value for B_MERCHANT_ORDER.TMSMP
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setTmsmp(String tmsmp) {
        this.tmsmp = tmsmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_MERCHANT_ORDER.INVOICENO
     *
     * @return the value of B_MERCHANT_ORDER.INVOICENO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public String getInvoiceno() {
        return invoiceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_MERCHANT_ORDER.INVOICENO
     *
     * @param invoiceno the value for B_MERCHANT_ORDER.INVOICENO
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    public void setInvoiceno(String invoiceno) {
        this.invoiceno = invoiceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BMerchantOrder other = (BMerchantOrder) that;
        return (this.getMerchantid() == null ? other.getMerchantid() == null : this.getMerchantid().equals(other.getMerchantid()))
            && (this.getOrderid() == null ? other.getOrderid() == null : this.getOrderid().equals(other.getOrderid()))
            && (this.getOrderdate() == null ? other.getOrderdate() == null : this.getOrderdate().equals(other.getOrderdate()))
            && (this.getPayjnlno() == null ? other.getPayjnlno() == null : this.getPayjnlno().equals(other.getPayjnlno()))
            && (this.getPaytime() == null ? other.getPaytime() == null : this.getPaytime().equals(other.getPaytime()))
            && (this.getOrdertime() == null ? other.getOrdertime() == null : this.getOrdertime().equals(other.getOrdertime()))
            && (this.getClientip() == null ? other.getClientip() == null : this.getClientip().equals(other.getClientip()))
            && (this.getPurchaserid() == null ? other.getPurchaserid() == null : this.getPurchaserid().equals(other.getPurchaserid()))
            && (this.getValidunit() == null ? other.getValidunit() == null : this.getValidunit().equals(other.getValidunit()))
            && (this.getValidnum() == null ? other.getValidnum() == null : this.getValidnum().equals(other.getValidnum()))
            && (this.getOrderdesc() == null ? other.getOrderdesc() == null : this.getOrderdesc().equals(other.getOrderdesc()))
            && (this.getOrderamount() == null ? other.getOrderamount() == null : this.getOrderamount().equals(other.getOrderamount()))
            && (this.getCurrency() == null ? other.getCurrency() == null : this.getCurrency().equals(other.getCurrency()))
            && (this.getMerchantpoundage() == null ? other.getMerchantpoundage() == null : this.getMerchantpoundage().equals(other.getMerchantpoundage()))
            && (this.getPurchaseamount() == null ? other.getPurchaseamount() == null : this.getPurchaseamount().equals(other.getPurchaseamount()))
            && (this.getChannel() == null ? other.getChannel() == null : this.getChannel().equals(other.getChannel()))
            && (this.getAcceptancerate() == null ? other.getAcceptancerate() == null : this.getAcceptancerate().equals(other.getAcceptancerate()))
            && (this.getAcceptancemount() == null ? other.getAcceptancemount() == null : this.getAcceptancemount().equals(other.getAcceptancemount()))
            && (this.getAcceptancycurrency() == null ? other.getAcceptancycurrency() == null : this.getAcceptancycurrency().equals(other.getAcceptancycurrency()))
            && (this.getAcceptancypoundage() == null ? other.getAcceptancypoundage() == null : this.getAcceptancypoundage().equals(other.getAcceptancypoundage()))
            && (this.getOrderstatus() == null ? other.getOrderstatus() == null : this.getOrderstatus().equals(other.getOrderstatus()))
            && (this.getPagereturnurl() == null ? other.getPagereturnurl() == null : this.getPagereturnurl().equals(other.getPagereturnurl()))
            && (this.getOfflinenotifyurl() == null ? other.getOfflinenotifyurl() == null : this.getOfflinenotifyurl().equals(other.getOfflinenotifyurl()))
            && (this.getPayorderid() == null ? other.getPayorderid() == null : this.getPayorderid().equals(other.getPayorderid()))
            && (this.getBuybatno() == null ? other.getBuybatno() == null : this.getBuybatno().equals(other.getBuybatno()))
            && (this.getBuybatstatus() == null ? other.getBuybatstatus() == null : this.getBuybatstatus().equals(other.getBuybatstatus()))
            && (this.getBuybatrate() == null ? other.getBuybatrate() == null : this.getBuybatrate().equals(other.getBuybatrate()))
            && (this.getUpordownmount() == null ? other.getUpordownmount() == null : this.getUpordownmount().equals(other.getUpordownmount()))
            && (this.getPaybatno() == null ? other.getPaybatno() == null : this.getPaybatno().equals(other.getPaybatno()))
            && (this.getPaybatstatus() == null ? other.getPaybatstatus() == null : this.getPaybatstatus().equals(other.getPaybatstatus()))
            && (this.getMountchangeno() == null ? other.getMountchangeno() == null : this.getMountchangeno().equals(other.getMountchangeno()))
            && (this.getMountchangestatus() == null ? other.getMountchangestatus() == null : this.getMountchangestatus().equals(other.getMountchangestatus()))
            && (this.getSettlebatno() == null ? other.getSettlebatno() == null : this.getSettlebatno().equals(other.getSettlebatno()))
            && (this.getSettlebatstatus() == null ? other.getSettlebatstatus() == null : this.getSettlebatstatus().equals(other.getSettlebatstatus()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getTradeType() == null ? other.getTradeType() == null : this.getTradeType().equals(other.getTradeType()))
            && (this.getBuybatdate() == null ? other.getBuybatdate() == null : this.getBuybatdate().equals(other.getBuybatdate()))
            && (this.getPaycard() == null ? other.getPaycard() == null : this.getPaycard().equals(other.getPaycard()))
            && (this.getPaydate() == null ? other.getPaydate() == null : this.getPaydate().equals(other.getPaydate()))
            && (this.getTradeCode() == null ? other.getTradeCode() == null : this.getTradeCode().equals(other.getTradeCode()))
            && (this.getIsRef() == null ? other.getIsRef() == null : this.getIsRef().equals(other.getIsRef()))
            && (this.getPaybatdate() == null ? other.getPaybatdate() == null : this.getPaybatdate().equals(other.getPaybatdate()))
            && (this.getProductid() == null ? other.getProductid() == null : this.getProductid().equals(other.getProductid()))
            && (this.getProductname() == null ? other.getProductname() == null : this.getProductname().equals(other.getProductname()))
            && (this.getProductdesc() == null ? other.getProductdesc() == null : this.getProductdesc().equals(other.getProductdesc()))
            && (this.getShowurl() == null ? other.getShowurl() == null : this.getShowurl().equals(other.getShowurl()))
            && (this.getIsresponse() == null ? other.getIsresponse() == null : this.getIsresponse().equals(other.getIsresponse()))
            && (this.getRcvtime() == null ? other.getRcvtime() == null : this.getRcvtime().equals(other.getRcvtime()))
            && (this.getRcvdate() == null ? other.getRcvdate() == null : this.getRcvdate().equals(other.getRcvdate()))
            && (this.getTmsmp() == null ? other.getTmsmp() == null : this.getTmsmp().equals(other.getTmsmp()))
            && (this.getInvoiceno() == null ? other.getInvoiceno() == null : this.getInvoiceno().equals(other.getInvoiceno()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMerchantid() == null) ? 0 : getMerchantid().hashCode());
        result = prime * result + ((getOrderid() == null) ? 0 : getOrderid().hashCode());
        result = prime * result + ((getOrderdate() == null) ? 0 : getOrderdate().hashCode());
        result = prime * result + ((getPayjnlno() == null) ? 0 : getPayjnlno().hashCode());
        result = prime * result + ((getPaytime() == null) ? 0 : getPaytime().hashCode());
        result = prime * result + ((getOrdertime() == null) ? 0 : getOrdertime().hashCode());
        result = prime * result + ((getClientip() == null) ? 0 : getClientip().hashCode());
        result = prime * result + ((getPurchaserid() == null) ? 0 : getPurchaserid().hashCode());
        result = prime * result + ((getValidunit() == null) ? 0 : getValidunit().hashCode());
        result = prime * result + ((getValidnum() == null) ? 0 : getValidnum().hashCode());
        result = prime * result + ((getOrderdesc() == null) ? 0 : getOrderdesc().hashCode());
        result = prime * result + ((getOrderamount() == null) ? 0 : getOrderamount().hashCode());
        result = prime * result + ((getCurrency() == null) ? 0 : getCurrency().hashCode());
        result = prime * result + ((getMerchantpoundage() == null) ? 0 : getMerchantpoundage().hashCode());
        result = prime * result + ((getPurchaseamount() == null) ? 0 : getPurchaseamount().hashCode());
        result = prime * result + ((getChannel() == null) ? 0 : getChannel().hashCode());
        result = prime * result + ((getAcceptancerate() == null) ? 0 : getAcceptancerate().hashCode());
        result = prime * result + ((getAcceptancemount() == null) ? 0 : getAcceptancemount().hashCode());
        result = prime * result + ((getAcceptancycurrency() == null) ? 0 : getAcceptancycurrency().hashCode());
        result = prime * result + ((getAcceptancypoundage() == null) ? 0 : getAcceptancypoundage().hashCode());
        result = prime * result + ((getOrderstatus() == null) ? 0 : getOrderstatus().hashCode());
        result = prime * result + ((getPagereturnurl() == null) ? 0 : getPagereturnurl().hashCode());
        result = prime * result + ((getOfflinenotifyurl() == null) ? 0 : getOfflinenotifyurl().hashCode());
        result = prime * result + ((getPayorderid() == null) ? 0 : getPayorderid().hashCode());
        result = prime * result + ((getBuybatno() == null) ? 0 : getBuybatno().hashCode());
        result = prime * result + ((getBuybatstatus() == null) ? 0 : getBuybatstatus().hashCode());
        result = prime * result + ((getBuybatrate() == null) ? 0 : getBuybatrate().hashCode());
        result = prime * result + ((getUpordownmount() == null) ? 0 : getUpordownmount().hashCode());
        result = prime * result + ((getPaybatno() == null) ? 0 : getPaybatno().hashCode());
        result = prime * result + ((getPaybatstatus() == null) ? 0 : getPaybatstatus().hashCode());
        result = prime * result + ((getMountchangeno() == null) ? 0 : getMountchangeno().hashCode());
        result = prime * result + ((getMountchangestatus() == null) ? 0 : getMountchangestatus().hashCode());
        result = prime * result + ((getSettlebatno() == null) ? 0 : getSettlebatno().hashCode());
        result = prime * result + ((getSettlebatstatus() == null) ? 0 : getSettlebatstatus().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getTradeType() == null) ? 0 : getTradeType().hashCode());
        result = prime * result + ((getBuybatdate() == null) ? 0 : getBuybatdate().hashCode());
        result = prime * result + ((getPaycard() == null) ? 0 : getPaycard().hashCode());
        result = prime * result + ((getPaydate() == null) ? 0 : getPaydate().hashCode());
        result = prime * result + ((getTradeCode() == null) ? 0 : getTradeCode().hashCode());
        result = prime * result + ((getIsRef() == null) ? 0 : getIsRef().hashCode());
        result = prime * result + ((getPaybatdate() == null) ? 0 : getPaybatdate().hashCode());
        result = prime * result + ((getProductid() == null) ? 0 : getProductid().hashCode());
        result = prime * result + ((getProductname() == null) ? 0 : getProductname().hashCode());
        result = prime * result + ((getProductdesc() == null) ? 0 : getProductdesc().hashCode());
        result = prime * result + ((getShowurl() == null) ? 0 : getShowurl().hashCode());
        result = prime * result + ((getIsresponse() == null) ? 0 : getIsresponse().hashCode());
        result = prime * result + ((getRcvtime() == null) ? 0 : getRcvtime().hashCode());
        result = prime * result + ((getRcvdate() == null) ? 0 : getRcvdate().hashCode());
        result = prime * result + ((getTmsmp() == null) ? 0 : getTmsmp().hashCode());
        result = prime * result + ((getInvoiceno() == null) ? 0 : getInvoiceno().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B_MERCHANT_ORDER
     *
     * @mbggenerated Wed Jun 15 16:50:27 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", payjnlno=").append(payjnlno);
        sb.append(", paytime=").append(paytime);
        sb.append(", ordertime=").append(ordertime);
        sb.append(", clientip=").append(clientip);
        sb.append(", purchaserid=").append(purchaserid);
        sb.append(", validunit=").append(validunit);
        sb.append(", validnum=").append(validnum);
        sb.append(", orderdesc=").append(orderdesc);
        sb.append(", orderamount=").append(orderamount);
        sb.append(", currency=").append(currency);
        sb.append(", merchantpoundage=").append(merchantpoundage);
        sb.append(", purchaseamount=").append(purchaseamount);
        sb.append(", channel=").append(channel);
        sb.append(", acceptancerate=").append(acceptancerate);
        sb.append(", acceptancemount=").append(acceptancemount);
        sb.append(", acceptancycurrency=").append(acceptancycurrency);
        sb.append(", acceptancypoundage=").append(acceptancypoundage);
        sb.append(", orderstatus=").append(orderstatus);
        sb.append(", pagereturnurl=").append(pagereturnurl);
        sb.append(", offlinenotifyurl=").append(offlinenotifyurl);
        sb.append(", payorderid=").append(payorderid);
        sb.append(", buybatno=").append(buybatno);
        sb.append(", buybatstatus=").append(buybatstatus);
        sb.append(", buybatrate=").append(buybatrate);
        sb.append(", upordownmount=").append(upordownmount);
        sb.append(", paybatno=").append(paybatno);
        sb.append(", paybatstatus=").append(paybatstatus);
        sb.append(", mountchangeno=").append(mountchangeno);
        sb.append(", mountchangestatus=").append(mountchangestatus);
        sb.append(", settlebatno=").append(settlebatno);
        sb.append(", settlebatstatus=").append(settlebatstatus);
        sb.append(", userid=").append(userid);
        sb.append(", tradeType=").append(tradeType);
        sb.append(", buybatdate=").append(buybatdate);
        sb.append(", paycard=").append(paycard);
        sb.append(", paydate=").append(paydate);
        sb.append(", tradeCode=").append(tradeCode);
        sb.append(", isRef=").append(isRef);
        sb.append(", paybatdate=").append(paybatdate);
        sb.append(", productid=").append(productid);
        sb.append(", productname=").append(productname);
        sb.append(", productdesc=").append(productdesc);
        sb.append(", showurl=").append(showurl);
        sb.append(", isresponse=").append(isresponse);
        sb.append(", rcvtime=").append(rcvtime);
        sb.append(", rcvdate=").append(rcvdate);
        sb.append(", tmsmp=").append(tmsmp);
        sb.append(", invoiceno=").append(invoiceno);
        sb.append("]");
        return sb.toString();
    }
}