package cn.msec.cbpay.entity;

import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import cn.msec.ojpa.api.annotations.Tab;

@Tab(name="B_SELL_EXG_CTRL")
@AllArgsConstructor
@NoArgsConstructor
public class BSellExgCtrl extends BSellExgCtrlKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.PAYTIME
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.QUOTECHNL
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String quotechnl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.REMIT_CCY
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String remitCcy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.REMIT_AMT
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private BigDecimal remitAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.COST_TYPE
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String costType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.PAYEE_ACCT_NO
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String payeeAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.PAYEE_CLIENT_NAME
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String payeeClientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.PAYEE_ADDRESS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String payeeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.PAYER_ACCT_NO
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String payerAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.PAYER_CLIENT_NAME
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String payerClientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.PAYER_ADDRESS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String payerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.PAYEE_ACCT_OPEN_BRANCH_ID
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String payeeAcctOpenBranchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.REMARK
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.CLEAR_BANK_BIC
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String clearBankBic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.PROCESS_MSG
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String processMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.PROCESS_STATUS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String processStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.FAIL_REASON
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String failReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.CHKSTATUS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String chkstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.FILENAME
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.BUSS_STATUS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private String bussStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B_SELL_EXG_CTRL.TOT_NUM
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    private Short totNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.PAYTIME
     *
     * @return the value of B_SELL_EXG_CTRL.PAYTIME
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.PAYTIME
     *
     * @param paytime the value for B_SELL_EXG_CTRL.PAYTIME
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setPaytime(String paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.QUOTECHNL
     *
     * @return the value of B_SELL_EXG_CTRL.QUOTECHNL
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getQuotechnl() {
        return quotechnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.QUOTECHNL
     *
     * @param quotechnl the value for B_SELL_EXG_CTRL.QUOTECHNL
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setQuotechnl(String quotechnl) {
        this.quotechnl = quotechnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.REMIT_CCY
     *
     * @return the value of B_SELL_EXG_CTRL.REMIT_CCY
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getRemitCcy() {
        return remitCcy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.REMIT_CCY
     *
     * @param remitCcy the value for B_SELL_EXG_CTRL.REMIT_CCY
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setRemitCcy(String remitCcy) {
        this.remitCcy = remitCcy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.REMIT_AMT
     *
     * @return the value of B_SELL_EXG_CTRL.REMIT_AMT
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public BigDecimal getRemitAmt() {
        return remitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.REMIT_AMT
     *
     * @param remitAmt the value for B_SELL_EXG_CTRL.REMIT_AMT
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setRemitAmt(BigDecimal remitAmt) {
        this.remitAmt = remitAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.COST_TYPE
     *
     * @return the value of B_SELL_EXG_CTRL.COST_TYPE
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getCostType() {
        return costType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.COST_TYPE
     *
     * @param costType the value for B_SELL_EXG_CTRL.COST_TYPE
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setCostType(String costType) {
        this.costType = costType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.PAYEE_ACCT_NO
     *
     * @return the value of B_SELL_EXG_CTRL.PAYEE_ACCT_NO
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getPayeeAcctNo() {
        return payeeAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.PAYEE_ACCT_NO
     *
     * @param payeeAcctNo the value for B_SELL_EXG_CTRL.PAYEE_ACCT_NO
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setPayeeAcctNo(String payeeAcctNo) {
        this.payeeAcctNo = payeeAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.PAYEE_CLIENT_NAME
     *
     * @return the value of B_SELL_EXG_CTRL.PAYEE_CLIENT_NAME
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getPayeeClientName() {
        return payeeClientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.PAYEE_CLIENT_NAME
     *
     * @param payeeClientName the value for B_SELL_EXG_CTRL.PAYEE_CLIENT_NAME
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setPayeeClientName(String payeeClientName) {
        this.payeeClientName = payeeClientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.PAYEE_ADDRESS
     *
     * @return the value of B_SELL_EXG_CTRL.PAYEE_ADDRESS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getPayeeAddress() {
        return payeeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.PAYEE_ADDRESS
     *
     * @param payeeAddress the value for B_SELL_EXG_CTRL.PAYEE_ADDRESS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setPayeeAddress(String payeeAddress) {
        this.payeeAddress = payeeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.PAYER_ACCT_NO
     *
     * @return the value of B_SELL_EXG_CTRL.PAYER_ACCT_NO
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getPayerAcctNo() {
        return payerAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.PAYER_ACCT_NO
     *
     * @param payerAcctNo the value for B_SELL_EXG_CTRL.PAYER_ACCT_NO
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setPayerAcctNo(String payerAcctNo) {
        this.payerAcctNo = payerAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.PAYER_CLIENT_NAME
     *
     * @return the value of B_SELL_EXG_CTRL.PAYER_CLIENT_NAME
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getPayerClientName() {
        return payerClientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.PAYER_CLIENT_NAME
     *
     * @param payerClientName the value for B_SELL_EXG_CTRL.PAYER_CLIENT_NAME
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setPayerClientName(String payerClientName) {
        this.payerClientName = payerClientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.PAYER_ADDRESS
     *
     * @return the value of B_SELL_EXG_CTRL.PAYER_ADDRESS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getPayerAddress() {
        return payerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.PAYER_ADDRESS
     *
     * @param payerAddress the value for B_SELL_EXG_CTRL.PAYER_ADDRESS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setPayerAddress(String payerAddress) {
        this.payerAddress = payerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.PAYEE_ACCT_OPEN_BRANCH_ID
     *
     * @return the value of B_SELL_EXG_CTRL.PAYEE_ACCT_OPEN_BRANCH_ID
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getPayeeAcctOpenBranchId() {
        return payeeAcctOpenBranchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.PAYEE_ACCT_OPEN_BRANCH_ID
     *
     * @param payeeAcctOpenBranchId the value for B_SELL_EXG_CTRL.PAYEE_ACCT_OPEN_BRANCH_ID
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setPayeeAcctOpenBranchId(String payeeAcctOpenBranchId) {
        this.payeeAcctOpenBranchId = payeeAcctOpenBranchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.REMARK
     *
     * @return the value of B_SELL_EXG_CTRL.REMARK
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.REMARK
     *
     * @param remark the value for B_SELL_EXG_CTRL.REMARK
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.CLEAR_BANK_BIC
     *
     * @return the value of B_SELL_EXG_CTRL.CLEAR_BANK_BIC
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getClearBankBic() {
        return clearBankBic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.CLEAR_BANK_BIC
     *
     * @param clearBankBic the value for B_SELL_EXG_CTRL.CLEAR_BANK_BIC
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setClearBankBic(String clearBankBic) {
        this.clearBankBic = clearBankBic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.PROCESS_MSG
     *
     * @return the value of B_SELL_EXG_CTRL.PROCESS_MSG
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getProcessMsg() {
        return processMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.PROCESS_MSG
     *
     * @param processMsg the value for B_SELL_EXG_CTRL.PROCESS_MSG
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setProcessMsg(String processMsg) {
        this.processMsg = processMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.PROCESS_STATUS
     *
     * @return the value of B_SELL_EXG_CTRL.PROCESS_STATUS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.PROCESS_STATUS
     *
     * @param processStatus the value for B_SELL_EXG_CTRL.PROCESS_STATUS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setProcessStatus(String processStatus) {
        this.processStatus = processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.FAIL_REASON
     *
     * @return the value of B_SELL_EXG_CTRL.FAIL_REASON
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getFailReason() {
        return failReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.FAIL_REASON
     *
     * @param failReason the value for B_SELL_EXG_CTRL.FAIL_REASON
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setFailReason(String failReason) {
        this.failReason = failReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.CHKSTATUS
     *
     * @return the value of B_SELL_EXG_CTRL.CHKSTATUS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getChkstatus() {
        return chkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.CHKSTATUS
     *
     * @param chkstatus the value for B_SELL_EXG_CTRL.CHKSTATUS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setChkstatus(String chkstatus) {
        this.chkstatus = chkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.STAMP
     *
     * @return the value of B_SELL_EXG_CTRL.STAMP
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
//    @JsonSerialize(using = CustomDateSerializer.class)
//    public Date getStamp() {
//        return stamp;
//    }
    

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.STAMP
     *
     * @param stamp the value for B_SELL_EXG_CTRL.STAMP
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.FILENAME
     *
     * @return the value of B_SELL_EXG_CTRL.FILENAME
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.FILENAME
     *
     * @param filename the value for B_SELL_EXG_CTRL.FILENAME
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.BUSS_STATUS
     *
     * @return the value of B_SELL_EXG_CTRL.BUSS_STATUS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public String getBussStatus() {
        return bussStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.BUSS_STATUS
     *
     * @param bussStatus the value for B_SELL_EXG_CTRL.BUSS_STATUS
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setBussStatus(String bussStatus) {
        this.bussStatus = bussStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B_SELL_EXG_CTRL.TOT_NUM
     *
     * @return the value of B_SELL_EXG_CTRL.TOT_NUM
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public Short getTotNum() {
        return totNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B_SELL_EXG_CTRL.TOT_NUM
     *
     * @param totNum the value for B_SELL_EXG_CTRL.TOT_NUM
     *
     * @mbggenerated Thu May 05 14:51:53 CST 2016
     */
    public void setTotNum(Short totNum) {
        this.totNum = totNum;
    }
    

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("BSellExgCtrl [paytime=");
		builder.append(paytime);
		builder.append(", quotechnl=");
		builder.append(quotechnl);
		builder.append(", remitCcy=");
		builder.append(remitCcy);
		builder.append(", remitAmt=");
		builder.append(remitAmt);
		builder.append(", costType=");
		builder.append(costType);
		builder.append(", payeeAcctNo=");
		builder.append(payeeAcctNo);
		builder.append(", payeeClientName=");
		builder.append(payeeClientName);
		builder.append(", payeeAddress=");
		builder.append(payeeAddress);
		builder.append(", payerAcctNo=");
		builder.append(payerAcctNo);
		builder.append(", payerClientName=");
		builder.append(payerClientName);
		builder.append(", payerAddress=");
		builder.append(payerAddress);
		builder.append(", payeeAcctOpenBranchId=");
		builder.append(payeeAcctOpenBranchId);
		builder.append(", remark=");
		builder.append(remark);
		builder.append(", clearBankBic=");
		builder.append(clearBankBic);
		builder.append(", processMsg=");
		builder.append(processMsg);
		builder.append(", processStatus=");
		builder.append(processStatus);
		builder.append(", failReason=");
		builder.append(failReason);
		builder.append(", chkstatus=");
		builder.append(chkstatus);
		builder.append(", filename=");
		builder.append(filename);
		builder.append(", bussStatus=");
		builder.append(bussStatus);
		builder.append(", totNum=");
		builder.append(totNum);
		builder.append("]");
		return builder.toString();
	}
}