package cn.msec.cbpay.entity;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import cn.msec.ojpa.api.annotations.Tab;

@Tab(name="T_APP_CONTAIN")
@AllArgsConstructor
@NoArgsConstructor
public class TAppContain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APP_CONTAIN.APPID
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APP_CONTAIN.CONTAINTYPE
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    private String containtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APP_CONTAIN.IP
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_APP_CONTAIN.VALID
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    private String valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APP_CONTAIN.APPID
     *
     * @return the value of T_APP_CONTAIN.APPID
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APP_CONTAIN.APPID
     *
     * @param appid the value for T_APP_CONTAIN.APPID
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APP_CONTAIN.CONTAINTYPE
     *
     * @return the value of T_APP_CONTAIN.CONTAINTYPE
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    public String getContaintype() {
        return containtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APP_CONTAIN.CONTAINTYPE
     *
     * @param containtype the value for T_APP_CONTAIN.CONTAINTYPE
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    public void setContaintype(String containtype) {
        this.containtype = containtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APP_CONTAIN.IP
     *
     * @return the value of T_APP_CONTAIN.IP
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APP_CONTAIN.IP
     *
     * @param ip the value for T_APP_CONTAIN.IP
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_APP_CONTAIN.VALID
     *
     * @return the value of T_APP_CONTAIN.VALID
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    public String getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_APP_CONTAIN.VALID
     *
     * @param valid the value for T_APP_CONTAIN.VALID
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    public void setValid(String valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_APP_CONTAIN
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TAppContain other = (TAppContain) that;
        return (this.getAppid() == null ? other.getAppid() == null : this.getAppid().equals(other.getAppid()))
            && (this.getContaintype() == null ? other.getContaintype() == null : this.getContaintype().equals(other.getContaintype()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_APP_CONTAIN
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAppid() == null) ? 0 : getAppid().hashCode());
        result = prime * result + ((getContaintype() == null) ? 0 : getContaintype().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_APP_CONTAIN
     *
     * @mbggenerated Wed Jul 06 17:21:01 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", appid=").append(appid);
        sb.append(", containtype=").append(containtype);
        sb.append(", ip=").append(ip);
        sb.append(", valid=").append(valid);
        sb.append("]");
        return sb.toString();
    }
}