package cn.msec.msc.mysqlgens.admin.entity;

import cn.msec.ojpa.api.annotations.Tab;
import cn.msec.ojpa.msc.mysql.CustomDateSerializer;
import java.math.BigDecimal;
import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="T_SYS_BRANCH")
@AllArgsConstructor
@NoArgsConstructor
public class SysBranch extends SysBranchKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BRANCH.BRANCH_ID
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private String branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BRANCH.BRANCH_DESC
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private String branchDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BRANCH.BRANCH_NAME
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private String branchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BRANCH.BRANCH_MANAGER
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private String branchManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BRANCH.MOBILE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BRANCH.BEGIN_TIME
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BRANCH.END_TIME
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BRANCH.PARENT_ID
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BRANCH.LEAF_FLAG
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private BigDecimal leafFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BRANCH.BRANCH_SEQ
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private BigDecimal branchSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_BRANCH.LEVEL1
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private BigDecimal level1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BRANCH.BRANCH_ID
     *
     * @return the value of T_SYS_BRANCH.BRANCH_ID
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BRANCH.BRANCH_ID
     *
     * @param branchId the value for T_SYS_BRANCH.BRANCH_ID
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BRANCH.BRANCH_DESC
     *
     * @return the value of T_SYS_BRANCH.BRANCH_DESC
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public String getBranchDesc() {
        return branchDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BRANCH.BRANCH_DESC
     *
     * @param branchDesc the value for T_SYS_BRANCH.BRANCH_DESC
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setBranchDesc(String branchDesc) {
        this.branchDesc = branchDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BRANCH.BRANCH_NAME
     *
     * @return the value of T_SYS_BRANCH.BRANCH_NAME
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BRANCH.BRANCH_NAME
     *
     * @param branchName the value for T_SYS_BRANCH.BRANCH_NAME
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BRANCH.BRANCH_MANAGER
     *
     * @return the value of T_SYS_BRANCH.BRANCH_MANAGER
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public String getBranchManager() {
        return branchManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BRANCH.BRANCH_MANAGER
     *
     * @param branchManager the value for T_SYS_BRANCH.BRANCH_MANAGER
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setBranchManager(String branchManager) {
        this.branchManager = branchManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BRANCH.MOBILE
     *
     * @return the value of T_SYS_BRANCH.MOBILE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BRANCH.MOBILE
     *
     * @param mobile the value for T_SYS_BRANCH.MOBILE
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BRANCH.BEGIN_TIME
     *
     * @return the value of T_SYS_BRANCH.BEGIN_TIME
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BRANCH.BEGIN_TIME
     *
     * @param beginTime the value for T_SYS_BRANCH.BEGIN_TIME
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BRANCH.END_TIME
     *
     * @return the value of T_SYS_BRANCH.END_TIME
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @JsonSerialize(using = CustomDateSerializer.class)
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BRANCH.END_TIME
     *
     * @param endTime the value for T_SYS_BRANCH.END_TIME
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BRANCH.PARENT_ID
     *
     * @return the value of T_SYS_BRANCH.PARENT_ID
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BRANCH.PARENT_ID
     *
     * @param parentId the value for T_SYS_BRANCH.PARENT_ID
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BRANCH.LEAF_FLAG
     *
     * @return the value of T_SYS_BRANCH.LEAF_FLAG
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public BigDecimal getLeafFlag() {
        return leafFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BRANCH.LEAF_FLAG
     *
     * @param leafFlag the value for T_SYS_BRANCH.LEAF_FLAG
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setLeafFlag(BigDecimal leafFlag) {
        this.leafFlag = leafFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BRANCH.BRANCH_SEQ
     *
     * @return the value of T_SYS_BRANCH.BRANCH_SEQ
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public BigDecimal getBranchSeq() {
        return branchSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BRANCH.BRANCH_SEQ
     *
     * @param branchSeq the value for T_SYS_BRANCH.BRANCH_SEQ
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setBranchSeq(BigDecimal branchSeq) {
        this.branchSeq = branchSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_BRANCH.LEVEL1
     *
     * @return the value of T_SYS_BRANCH.LEVEL1
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public BigDecimal getLevel1() {
        return level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_BRANCH.LEVEL1
     *
     * @param level1 the value for T_SYS_BRANCH.LEVEL1
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setLevel1(BigDecimal level1) {
        this.level1 = level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BRANCH
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysBranch other = (SysBranch) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBranchId() == null ? other.getBranchId() == null : this.getBranchId().equals(other.getBranchId()))
            && (this.getBranchDesc() == null ? other.getBranchDesc() == null : this.getBranchDesc().equals(other.getBranchDesc()))
            && (this.getBranchName() == null ? other.getBranchName() == null : this.getBranchName().equals(other.getBranchName()))
            && (this.getBranchManager() == null ? other.getBranchManager() == null : this.getBranchManager().equals(other.getBranchManager()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getBeginTime() == null ? other.getBeginTime() == null : this.getBeginTime().equals(other.getBeginTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getLeafFlag() == null ? other.getLeafFlag() == null : this.getLeafFlag().equals(other.getLeafFlag()))
            && (this.getBranchSeq() == null ? other.getBranchSeq() == null : this.getBranchSeq().equals(other.getBranchSeq()))
            && (this.getLevel1() == null ? other.getLevel1() == null : this.getLevel1().equals(other.getLevel1()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BRANCH
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBranchId() == null) ? 0 : getBranchId().hashCode());
        result = prime * result + ((getBranchDesc() == null) ? 0 : getBranchDesc().hashCode());
        result = prime * result + ((getBranchName() == null) ? 0 : getBranchName().hashCode());
        result = prime * result + ((getBranchManager() == null) ? 0 : getBranchManager().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getBeginTime() == null) ? 0 : getBeginTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getLeafFlag() == null) ? 0 : getLeafFlag().hashCode());
        result = prime * result + ((getBranchSeq() == null) ? 0 : getBranchSeq().hashCode());
        result = prime * result + ((getLevel1() == null) ? 0 : getLevel1().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_BRANCH
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", branchId=").append(branchId);
        sb.append(", branchDesc=").append(branchDesc);
        sb.append(", branchName=").append(branchName);
        sb.append(", branchManager=").append(branchManager);
        sb.append(", mobile=").append(mobile);
        sb.append(", beginTime=").append(beginTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", parentId=").append(parentId);
        sb.append(", leafFlag=").append(leafFlag);
        sb.append(", branchSeq=").append(branchSeq);
        sb.append(", level1=").append(level1);
        sb.append("]");
        return sb.toString();
    }
}