package cn.msec.msc.mysqlgens.admin.entity;

import cn.msec.ojpa.api.annotations.Tab;
import cn.msec.ojpa.msc.mysql.CustomDateSerializer;
import java.math.BigDecimal;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import org.codehaus.jackson.map.annotate.JsonSerialize;

@Tab(name="T_SYS_MENU")
@AllArgsConstructor
@NoArgsConstructor
public class SysMenu extends SysMenuKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.MENU_NAME
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.MENU_DESC
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private String menuDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.MENU_SEQ
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private BigDecimal menuSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.MENU_URL
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.PARENT_ID
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private BigDecimal parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.LEAF_FLAG
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private BigDecimal leafFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.LEVEL1
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private BigDecimal level1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SYS_MENU.ICON
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.MENU_NAME
     *
     * @return the value of T_SYS_MENU.MENU_NAME
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.MENU_NAME
     *
     * @param menuName the value for T_SYS_MENU.MENU_NAME
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.MENU_DESC
     *
     * @return the value of T_SYS_MENU.MENU_DESC
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.MENU_DESC
     *
     * @param menuDesc the value for T_SYS_MENU.MENU_DESC
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.MENU_SEQ
     *
     * @return the value of T_SYS_MENU.MENU_SEQ
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public BigDecimal getMenuSeq() {
        return menuSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.MENU_SEQ
     *
     * @param menuSeq the value for T_SYS_MENU.MENU_SEQ
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setMenuSeq(BigDecimal menuSeq) {
        this.menuSeq = menuSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.MENU_URL
     *
     * @return the value of T_SYS_MENU.MENU_URL
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.MENU_URL
     *
     * @param menuUrl the value for T_SYS_MENU.MENU_URL
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.PARENT_ID
     *
     * @return the value of T_SYS_MENU.PARENT_ID
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public BigDecimal getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.PARENT_ID
     *
     * @param parentId the value for T_SYS_MENU.PARENT_ID
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setParentId(BigDecimal parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.LEAF_FLAG
     *
     * @return the value of T_SYS_MENU.LEAF_FLAG
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public BigDecimal getLeafFlag() {
        return leafFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.LEAF_FLAG
     *
     * @param leafFlag the value for T_SYS_MENU.LEAF_FLAG
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setLeafFlag(BigDecimal leafFlag) {
        this.leafFlag = leafFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.LEVEL1
     *
     * @return the value of T_SYS_MENU.LEVEL1
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public BigDecimal getLevel1() {
        return level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.LEVEL1
     *
     * @param level1 the value for T_SYS_MENU.LEVEL1
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setLevel1(BigDecimal level1) {
        this.level1 = level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SYS_MENU.ICON
     *
     * @return the value of T_SYS_MENU.ICON
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SYS_MENU.ICON
     *
     * @param icon the value for T_SYS_MENU.ICON
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_MENU
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysMenu other = (SysMenu) that;
        return (this.getMenuId() == null ? other.getMenuId() == null : this.getMenuId().equals(other.getMenuId()))
            && (this.getMenuName() == null ? other.getMenuName() == null : this.getMenuName().equals(other.getMenuName()))
            && (this.getMenuDesc() == null ? other.getMenuDesc() == null : this.getMenuDesc().equals(other.getMenuDesc()))
            && (this.getMenuSeq() == null ? other.getMenuSeq() == null : this.getMenuSeq().equals(other.getMenuSeq()))
            && (this.getMenuUrl() == null ? other.getMenuUrl() == null : this.getMenuUrl().equals(other.getMenuUrl()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getLeafFlag() == null ? other.getLeafFlag() == null : this.getLeafFlag().equals(other.getLeafFlag()))
            && (this.getLevel1() == null ? other.getLevel1() == null : this.getLevel1().equals(other.getLevel1()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_MENU
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMenuId() == null) ? 0 : getMenuId().hashCode());
        result = prime * result + ((getMenuName() == null) ? 0 : getMenuName().hashCode());
        result = prime * result + ((getMenuDesc() == null) ? 0 : getMenuDesc().hashCode());
        result = prime * result + ((getMenuSeq() == null) ? 0 : getMenuSeq().hashCode());
        result = prime * result + ((getMenuUrl() == null) ? 0 : getMenuUrl().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getLeafFlag() == null) ? 0 : getLeafFlag().hashCode());
        result = prime * result + ((getLevel1() == null) ? 0 : getLevel1().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SYS_MENU
     *
     * @mbggenerated Thu Dec 31 10:48:44 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuName=").append(menuName);
        sb.append(", menuDesc=").append(menuDesc);
        sb.append(", menuSeq=").append(menuSeq);
        sb.append(", menuUrl=").append(menuUrl);
        sb.append(", parentId=").append(parentId);
        sb.append(", leafFlag=").append(leafFlag);
        sb.append(", level1=").append(level1);
        sb.append(", icon=").append(icon);
        sb.append("]");
        return sb.toString();
    }
}