package org.inn.baner.persist.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.inn.baner.bean.AcCore;
import org.inn.baner.bean.AcCoreExample;

public interface AcCoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_core
     *
     * @mbggenerated
     */
    @SelectProvider(type=AcCoreSqlProvider.class, method="countByExample")
    int countByExample(AcCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_core
     *
     * @mbggenerated
     */
    @DeleteProvider(type=AcCoreSqlProvider.class, method="deleteByExample")
    int deleteByExample(AcCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_core
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ac_core",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_core
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ac_core (id, acno, ",
        "acname, ownerid, ownername, ",
        "balance, ccy, stat, ",
        "actype, createtime, ",
        "updatetime, remark)",
        "values (#{id,jdbcType=VARCHAR}, #{acno,jdbcType=VARCHAR}, ",
        "#{acname,jdbcType=VARCHAR}, #{ownerid,jdbcType=CHAR}, #{ownername,jdbcType=VARCHAR}, ",
        "#{balance,jdbcType=DECIMAL}, #{ccy,jdbcType=CHAR}, #{stat,jdbcType=CHAR}, ",
        "#{actype,jdbcType=CHAR}, #{createtime,jdbcType=TIMESTAMP}, ",
        "#{updatetime,jdbcType=TIMESTAMP}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(AcCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_core
     *
     * @mbggenerated
     */
    @InsertProvider(type=AcCoreSqlProvider.class, method="insertSelective")
    int insertSelective(AcCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_core
     *
     * @mbggenerated
     */
    @SelectProvider(type=AcCoreSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="acno", property="acno", jdbcType=JdbcType.VARCHAR),
        @Result(column="acname", property="acname", jdbcType=JdbcType.VARCHAR),
        @Result(column="ownerid", property="ownerid", jdbcType=JdbcType.CHAR),
        @Result(column="ownername", property="ownername", jdbcType=JdbcType.VARCHAR),
        @Result(column="balance", property="balance", jdbcType=JdbcType.DECIMAL),
        @Result(column="ccy", property="ccy", jdbcType=JdbcType.CHAR),
        @Result(column="stat", property="stat", jdbcType=JdbcType.CHAR),
        @Result(column="actype", property="actype", jdbcType=JdbcType.CHAR),
        @Result(column="createtime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updatetime", property="updatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<AcCore> selectByExample(AcCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_core
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, acno, acname, ownerid, ownername, balance, ccy, stat, actype, createtime, ",
        "updatetime, remark",
        "from ac_core",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="acno", property="acno", jdbcType=JdbcType.VARCHAR),
        @Result(column="acname", property="acname", jdbcType=JdbcType.VARCHAR),
        @Result(column="ownerid", property="ownerid", jdbcType=JdbcType.CHAR),
        @Result(column="ownername", property="ownername", jdbcType=JdbcType.VARCHAR),
        @Result(column="balance", property="balance", jdbcType=JdbcType.DECIMAL),
        @Result(column="ccy", property="ccy", jdbcType=JdbcType.CHAR),
        @Result(column="stat", property="stat", jdbcType=JdbcType.CHAR),
        @Result(column="actype", property="actype", jdbcType=JdbcType.CHAR),
        @Result(column="createtime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updatetime", property="updatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    AcCore selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_core
     *
     * @mbggenerated
     */
    @UpdateProvider(type=AcCoreSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AcCore record, @Param("example") AcCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_core
     *
     * @mbggenerated
     */
    @UpdateProvider(type=AcCoreSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AcCore record, @Param("example") AcCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_core
     *
     * @mbggenerated
     */
    @UpdateProvider(type=AcCoreSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AcCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_core
     *
     * @mbggenerated
     */
    @Update({
        "update ac_core",
        "set acno = #{acno,jdbcType=VARCHAR},",
          "acname = #{acname,jdbcType=VARCHAR},",
          "ownerid = #{ownerid,jdbcType=CHAR},",
          "ownername = #{ownername,jdbcType=VARCHAR},",
          "balance = #{balance,jdbcType=DECIMAL},",
          "ccy = #{ccy,jdbcType=CHAR},",
          "stat = #{stat,jdbcType=CHAR},",
          "actype = #{actype,jdbcType=CHAR},",
          "createtime = #{createtime,jdbcType=TIMESTAMP},",
          "updatetime = #{updatetime,jdbcType=TIMESTAMP},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(AcCore record);
}