package org.inn.baner.persist.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.inn.baner.bean.Activity;
import org.inn.baner.bean.ActivityExample;

public interface ActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @SelectProvider(type=ActivitySqlProvider.class, method="countByExample")
    int countByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @DeleteProvider(type=ActivitySqlProvider.class, method="deleteByExample")
    int deleteByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @Delete({
        "delete from activity",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @Insert({
        "insert into activity (id, name, ",
        "actitype, total, quota, ",
        "minamount, maxamount, ",
        "createtime, starttime, ",
        "endtime, updatetime, ",
        "stat, listimg, linkaddress, ",
        "merno, mername, ",
        "remark)",
        "values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{actitype,jdbcType=CHAR}, #{total,jdbcType=DECIMAL}, #{quota,jdbcType=INTEGER}, ",
        "#{minamount,jdbcType=DECIMAL}, #{maxamount,jdbcType=DECIMAL}, ",
        "#{createtime,jdbcType=TIMESTAMP}, #{starttime,jdbcType=TIMESTAMP}, ",
        "#{endtime,jdbcType=TIMESTAMP}, #{updatetime,jdbcType=TIMESTAMP}, ",
        "#{stat,jdbcType=CHAR}, #{listimg,jdbcType=VARCHAR}, #{linkaddress,jdbcType=VARCHAR}, ",
        "#{merno,jdbcType=VARCHAR}, #{mername,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR})"
    })
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @InsertProvider(type=ActivitySqlProvider.class, method="insertSelective")
    int insertSelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @SelectProvider(type=ActivitySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="actitype", property="actitype", jdbcType=JdbcType.CHAR),
        @Result(column="total", property="total", jdbcType=JdbcType.DECIMAL),
        @Result(column="quota", property="quota", jdbcType=JdbcType.INTEGER),
        @Result(column="minamount", property="minamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="maxamount", property="maxamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="createtime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="starttime", property="starttime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="endtime", property="endtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updatetime", property="updatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="stat", property="stat", jdbcType=JdbcType.CHAR),
        @Result(column="listimg", property="listimg", jdbcType=JdbcType.VARCHAR),
        @Result(column="linkaddress", property="linkaddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="merno", property="merno", jdbcType=JdbcType.VARCHAR),
        @Result(column="mername", property="mername", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    List<Activity> selectByExample(ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, actitype, total, quota, minamount, maxamount, createtime, starttime, ",
        "endtime, updatetime, stat, listimg, linkaddress, merno, mername, remark",
        "from activity",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="actitype", property="actitype", jdbcType=JdbcType.CHAR),
        @Result(column="total", property="total", jdbcType=JdbcType.DECIMAL),
        @Result(column="quota", property="quota", jdbcType=JdbcType.INTEGER),
        @Result(column="minamount", property="minamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="maxamount", property="maxamount", jdbcType=JdbcType.DECIMAL),
        @Result(column="createtime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="starttime", property="starttime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="endtime", property="endtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updatetime", property="updatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="stat", property="stat", jdbcType=JdbcType.CHAR),
        @Result(column="listimg", property="listimg", jdbcType=JdbcType.VARCHAR),
        @Result(column="linkaddress", property="linkaddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="merno", property="merno", jdbcType=JdbcType.VARCHAR),
        @Result(column="mername", property="mername", jdbcType=JdbcType.VARCHAR),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    Activity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @UpdateProvider(type=ActivitySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Activity record, @Param("example") ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @UpdateProvider(type=ActivitySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Activity record, @Param("example") ActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @UpdateProvider(type=ActivitySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @Update({
        "update activity",
        "set name = #{name,jdbcType=VARCHAR},",
          "actitype = #{actitype,jdbcType=CHAR},",
          "total = #{total,jdbcType=DECIMAL},",
          "quota = #{quota,jdbcType=INTEGER},",
          "minamount = #{minamount,jdbcType=DECIMAL},",
          "maxamount = #{maxamount,jdbcType=DECIMAL},",
          "createtime = #{createtime,jdbcType=TIMESTAMP},",
          "starttime = #{starttime,jdbcType=TIMESTAMP},",
          "endtime = #{endtime,jdbcType=TIMESTAMP},",
          "updatetime = #{updatetime,jdbcType=TIMESTAMP},",
          "stat = #{stat,jdbcType=CHAR},",
          "listimg = #{listimg,jdbcType=VARCHAR},",
          "linkaddress = #{linkaddress,jdbcType=VARCHAR},",
          "merno = #{merno,jdbcType=VARCHAR},",
          "mername = #{mername,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Activity record);
}