package org.inn.baner.bean;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentid
     *
     * @mbg.generated
     */
    private String commentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.postid
     *
     * @mbg.generated
     */
    private String postid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.creatormobileno
     *
     * @mbg.generated
     */
    private String creatormobileno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parentcommentid
     *
     * @mbg.generated
     */
    private String parentcommentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.context
     *
     * @mbg.generated
     */
    private byte[] context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentid
     *
     * @return the value of comment.commentid
     *
     * @mbg.generated
     */
    public String getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentid
     *
     * @param commentid the value for comment.commentid
     *
     * @mbg.generated
     */
    public void setCommentid(String commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.postid
     *
     * @return the value of comment.postid
     *
     * @mbg.generated
     */
    public String getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.postid
     *
     * @param postid the value for comment.postid
     *
     * @mbg.generated
     */
    public void setPostid(String postid) {
        this.postid = postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.creatormobileno
     *
     * @return the value of comment.creatormobileno
     *
     * @mbg.generated
     */
    public String getCreatormobileno() {
        return creatormobileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.creatormobileno
     *
     * @param creatormobileno the value for comment.creatormobileno
     *
     * @mbg.generated
     */
    public void setCreatormobileno(String creatormobileno) {
        this.creatormobileno = creatormobileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parentcommentid
     *
     * @return the value of comment.parentcommentid
     *
     * @mbg.generated
     */
    public String getParentcommentid() {
        return parentcommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parentcommentid
     *
     * @param parentcommentid the value for comment.parentcommentid
     *
     * @mbg.generated
     */
    public void setParentcommentid(String parentcommentid) {
        this.parentcommentid = parentcommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.createtime
     *
     * @return the value of comment.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.createtime
     *
     * @param createtime the value for comment.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.context
     *
     * @return the value of comment.context
     *
     * @mbg.generated
     */
    public byte[] getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.context
     *
     * @param context the value for comment.context
     *
     * @mbg.generated
     */
    public void setContext(byte[] context) {
        this.context = context;
    }
}