package org.inn.baner.bean;

public class LabelSubject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label_subject.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label_subject.labelid
     *
     * @mbg.generated
     */
    private String labelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label_subject.subjectid
     *
     * @mbg.generated
     */
    private String subjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label_subject.subject
     *
     * @mbg.generated
     */
    private String subject;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label_subject.id
     *
     * @return the value of label_subject.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label_subject.id
     *
     * @param id the value for label_subject.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label_subject.labelid
     *
     * @return the value of label_subject.labelid
     *
     * @mbg.generated
     */
    public String getLabelid() {
        return labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label_subject.labelid
     *
     * @param labelid the value for label_subject.labelid
     *
     * @mbg.generated
     */
    public void setLabelid(String labelid) {
        this.labelid = labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label_subject.subjectid
     *
     * @return the value of label_subject.subjectid
     *
     * @mbg.generated
     */
    public String getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label_subject.subjectid
     *
     * @param subjectid the value for label_subject.subjectid
     *
     * @mbg.generated
     */
    public void setSubjectid(String subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label_subject.subject
     *
     * @return the value of label_subject.subject
     *
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label_subject.subject
     *
     * @param subject the value for label_subject.subject
     *
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }
}