package org.inn.baner.bean;

public class Label {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.labelid
     *
     * @mbg.generated
     */
    private String labelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.labelname
     *
     * @mbg.generated
     */
    private String labelname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.weight
     *
     * @mbg.generated
     */
    private Integer weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.labelid
     *
     * @return the value of label.labelid
     *
     * @mbg.generated
     */
    public String getLabelid() {
        return labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.labelid
     *
     * @param labelid the value for label.labelid
     *
     * @mbg.generated
     */
    public void setLabelid(String labelid) {
        this.labelid = labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.labelname
     *
     * @return the value of label.labelname
     *
     * @mbg.generated
     */
    public String getLabelname() {
        return labelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.labelname
     *
     * @param labelname the value for label.labelname
     *
     * @mbg.generated
     */
    public void setLabelname(String labelname) {
        this.labelname = labelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.weight
     *
     * @return the value of label.weight
     *
     * @mbg.generated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.weight
     *
     * @param weight the value for label.weight
     *
     * @mbg.generated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
}