package org.inn.baner.bean;

import java.util.Date;

public class Mer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mer.merno
     *
     * @mbggenerated
     */
    private String merno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mer.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mer.mertype
     *
     * @mbggenerated
     */
    private String mertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mer.superidno
     *
     * @mbggenerated
     */
    private String superidno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mer.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mer.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mer.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mer.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mer.merno
     *
     * @return the value of mer.merno
     *
     * @mbggenerated
     */
    public String getMerno() {
        return merno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mer.merno
     *
     * @param merno the value for mer.merno
     *
     * @mbggenerated
     */
    public void setMerno(String merno) {
        this.merno = merno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mer.name
     *
     * @return the value of mer.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mer.name
     *
     * @param name the value for mer.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mer.mertype
     *
     * @return the value of mer.mertype
     *
     * @mbggenerated
     */
    public String getMertype() {
        return mertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mer.mertype
     *
     * @param mertype the value for mer.mertype
     *
     * @mbggenerated
     */
    public void setMertype(String mertype) {
        this.mertype = mertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mer.superidno
     *
     * @return the value of mer.superidno
     *
     * @mbggenerated
     */
    public String getSuperidno() {
        return superidno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mer.superidno
     *
     * @param superidno the value for mer.superidno
     *
     * @mbggenerated
     */
    public void setSuperidno(String superidno) {
        this.superidno = superidno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mer.address
     *
     * @return the value of mer.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mer.address
     *
     * @param address the value for mer.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mer.createtime
     *
     * @return the value of mer.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mer.createtime
     *
     * @param createtime the value for mer.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mer.updatetime
     *
     * @return the value of mer.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mer.updatetime
     *
     * @param updatetime the value for mer.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mer.remark
     *
     * @return the value of mer.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mer.remark
     *
     * @param remark the value for mer.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}