package org.inn.baner.bean;

import java.math.BigDecimal;
import java.util.Date;

public class RedFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_flow.platflow
     *
     * @mbggenerated
     */
    private String platflow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_flow.activityno
     *
     * @mbggenerated
     */
    private String activityno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_flow.providerid
     *
     * @mbggenerated
     */
    private String providerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_flow.providername
     *
     * @mbggenerated
     */
    private String providername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_flow.consumerid
     *
     * @mbggenerated
     */
    private String consumerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_flow.consumername
     *
     * @mbggenerated
     */
    private String consumername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_flow.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_flow.ccy
     *
     * @mbggenerated
     */
    private String ccy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_flow.stat
     *
     * @mbggenerated
     */
    private String stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_flow.recordedtime
     *
     * @mbggenerated
     */
    private Date recordedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_flow.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_flow.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_flow.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_flow.platflow
     *
     * @return the value of red_flow.platflow
     *
     * @mbggenerated
     */
    public String getPlatflow() {
        return platflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_flow.platflow
     *
     * @param platflow the value for red_flow.platflow
     *
     * @mbggenerated
     */
    public void setPlatflow(String platflow) {
        this.platflow = platflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_flow.activityno
     *
     * @return the value of red_flow.activityno
     *
     * @mbggenerated
     */
    public String getActivityno() {
        return activityno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_flow.activityno
     *
     * @param activityno the value for red_flow.activityno
     *
     * @mbggenerated
     */
    public void setActivityno(String activityno) {
        this.activityno = activityno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_flow.providerid
     *
     * @return the value of red_flow.providerid
     *
     * @mbggenerated
     */
    public String getProviderid() {
        return providerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_flow.providerid
     *
     * @param providerid the value for red_flow.providerid
     *
     * @mbggenerated
     */
    public void setProviderid(String providerid) {
        this.providerid = providerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_flow.providername
     *
     * @return the value of red_flow.providername
     *
     * @mbggenerated
     */
    public String getProvidername() {
        return providername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_flow.providername
     *
     * @param providername the value for red_flow.providername
     *
     * @mbggenerated
     */
    public void setProvidername(String providername) {
        this.providername = providername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_flow.consumerid
     *
     * @return the value of red_flow.consumerid
     *
     * @mbggenerated
     */
    public String getConsumerid() {
        return consumerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_flow.consumerid
     *
     * @param consumerid the value for red_flow.consumerid
     *
     * @mbggenerated
     */
    public void setConsumerid(String consumerid) {
        this.consumerid = consumerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_flow.consumername
     *
     * @return the value of red_flow.consumername
     *
     * @mbggenerated
     */
    public String getConsumername() {
        return consumername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_flow.consumername
     *
     * @param consumername the value for red_flow.consumername
     *
     * @mbggenerated
     */
    public void setConsumername(String consumername) {
        this.consumername = consumername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_flow.amount
     *
     * @return the value of red_flow.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_flow.amount
     *
     * @param amount the value for red_flow.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_flow.ccy
     *
     * @return the value of red_flow.ccy
     *
     * @mbggenerated
     */
    public String getCcy() {
        return ccy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_flow.ccy
     *
     * @param ccy the value for red_flow.ccy
     *
     * @mbggenerated
     */
    public void setCcy(String ccy) {
        this.ccy = ccy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_flow.stat
     *
     * @return the value of red_flow.stat
     *
     * @mbggenerated
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_flow.stat
     *
     * @param stat the value for red_flow.stat
     *
     * @mbggenerated
     */
    public void setStat(String stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_flow.recordedtime
     *
     * @return the value of red_flow.recordedtime
     *
     * @mbggenerated
     */
    public Date getRecordedtime() {
        return recordedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_flow.recordedtime
     *
     * @param recordedtime the value for red_flow.recordedtime
     *
     * @mbggenerated
     */
    public void setRecordedtime(Date recordedtime) {
        this.recordedtime = recordedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_flow.createtime
     *
     * @return the value of red_flow.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_flow.createtime
     *
     * @param createtime the value for red_flow.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_flow.updatetime
     *
     * @return the value of red_flow.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_flow.updatetime
     *
     * @param updatetime the value for red_flow.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_flow.remark
     *
     * @return the value of red_flow.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_flow.remark
     *
     * @param remark the value for red_flow.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}